### ISSUE TITLE
npm 오류 관련하여 질문드립니다.

### ISSUE THREAD

**Issue by jay9455** [JJoriping/KKuTu#1003]
안녕하세요, 현재 DigitalOcean의 우분투 서버를 사용하여 구축을 진행하려 합니다.

모든 과정이 원활하게 진행되었으나, [node ./Server/lib/Game/cluster.js 0 1] 해당 명령어 입력 과정부터 오류가 발생하고 있습니다.

구글링을 해 보면 저와 같은 오류를 겪으신 분이 계시고, npm 재설치를 통해 해결했다고 하십니다.

하지만 저의 경우 npm 재설치를 해 보아도 동일한 오류가 발생하고 있고, 개인 라즈베리파이에서도 동일한 오류가 발생합니다.

혹시 해당 부분 관련하여 도움을 주실 수 있으실까요..?

오류 문구는 아래 사진과 함께 첨부하였습니다.

----------------------- 오류 내용 -----------------------

module.js:549
    throw err;
    ^

Error: Cannot find module 'colors'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/KKuTu/Server/lib/sub/jjlog.js:21:14)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

![캡처](https://user-images.githubusercontent.com/83913698/165487547-22dfa4bf-2801-4c73-b80b-5c4f62df74a6.PNG)

**Comment by chuhyeonjin** [comment]
README.md 에 나와있듯이
`./server-setup.bat`을 실행하셨나요?

**Comment by jay9455** [comment]
네 해당부분은 이미 실행했습니다.

**Comment by chuhyeonjin** [comment]
colors 모듈이 어떠한 이유로 설치가 안된것 같습니다
`Server/lib` 경로에서 `npm i colors`로 직접 colors 모듈을 설치해주세요

**Comment by jay9455** [comment]
덕분에 모듈 설치 오류는 해결했습니다.
다만 모듈 설치 이후 node ./Server/lib/Game/cluster.js 0 1 입력시 다른 오류가 발생하고 있습니다.
아래와 같은 문구가 계속 반복되는데 해당 부분도 npm의 오류인가요..?

-----------오류 내용--------------- 

[2022-04-27 10:04:06] Worker @1 13483 died
[2022-04-27 10:04:07] << KKuTu Server:8496 >>
[2022-04-27 10:04:07] ERROR OCCURRED ON THE MASTER!
:8496 [4/27/2022, 10:04:07 AM] ERROR: SyntaxError: Unexpected token *
/root/KKuTu/Server/lib/node_modules/@node-redis/client/dist/lib/client/index.js:245
    async *scanIterator(options) {
          ^

SyntaxError: Unexpected token *
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/KKuTu/Server/lib/node_modules/@node-redis/client/dist/index.js:18:18)

[2022-04-27 10:04:07] ERROR OCCURRED! This worker will die in 10 seconds.
:8496 [4/27/2022, 10:04:07 AM] ERROR: SyntaxError: Unexpected token *
/root/KKuTu/Server/lib/node_modules/@node-redis/client/dist/lib/client/index.js:245
    async *scanIterator(options) {
          ^

SyntaxError: Unexpected token *
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/KKuTu/Server/lib/node_modules/@node-redis/client/dist/index.js:18:18)

**Comment by lshqqytiger** [comment]
설치된 Node.js의 V8 엔진이 Generator Function을 지원하지 않는 것 같습니다.
어떤 버전의 Node.js를 설치하셨나요?

**Comment by jay9455** [comment]
v8.10.0 입니다.

**Comment by lshqqytiger** [comment]
v8.10.0은 async Generator 문법을 지원하지 않습니다.
v10에서 최초로 지원하기 시작한 것으로 확인되었습니다. (v10.24.1)

**Comment by jay9455** [comment]
감사합니다! 덕분해 해결했습니다😊
