### ISSUE TITLE
게임 서버가 열리지 않습니다

### ISSUE THREAD

**Issue by pasunyan** [JJoriping/KKuTu#1040]
$ node lib/Game/cluster.js 0 1
[2022-08-21 10:30:00] ERROR OCCURRED ON THE MASTER!
:8080 [8/21/2022, 10:30:00 AM] ERROR: SyntaxError: Unexpected token .
/home/ubuntu/node_modules/redis/dist/index.js:42
            ...options?.modules
                       ^

SyntaxError: Unexpected token .
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.Pub.ready (/home/ubuntu/KKuTu/Server/lib/Web/db.js:42:15)
    
게임 서버를 열려고 명령어를 입력하면 이렇게 뜨는데 해결방법 알수 있을까요 ㅠㅠㅠㅠ

**Comment by lshqqytiger** [comment]
설치된 redis 모듈 버전이 최신인 것으로 보입니다.
package.json 파일을 다시 다운로드 받고 교체한 후 npm install을 다시 실행해주세요.

**Comment by pasunyan** [comment]
해결했습니다 감사합니다!
