### ISSUE TITLE
불러오는중 앞으로 1... 에서 멈춥니다.

### ISSUE THREAD

**Issue by ttrrrrrddd** [JJoriping/KKuTu#1048]
제목그대로 입니다. 게임 서버, 웹서버는 정상작동 하는데 들어가보면 앞으로 1 에서 멈춥니다. F12 키 눌러서 확인 해 보았더니 in_kkutu.min.js:1 
 Failed to load resource: the server responded with a status of 404 (Not Found)
drkkutu.run.goorm.io/:1 
        
       Refused to execute script from 'https://drkkutu.run.goorm.io/js/in_kkutu.min.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled
이런 오류가 있었습니다. 제 힘으론 도저히 해결을 못하겠습니다. 도와주세요.

**Comment by Preta-Crowz** [comment]
#689, 리드미 읽고 구축을 다시 시도해보세요. 문법 오류도 아니고 아예 404가 뜨는 것으로 보아 필수 과정이 누락된 것 같습니다.

**Comment by lshqqytiger** [comment]
## 왜 발생하는가?
`PageHead` mixin에서 자동으로 스크립트를 페이지에 삽입하는 과정에서 `in_kkutu.min.js` 파일을 찾지 못해 발생합니다.
Grunt는 `in_kkutu.min.js` 파일을 생성하지 않습니다.

## 해결이 필수적인가?
해당 오류가 발생하더라도 끄투 동작에는 문제가 없습니다.

## 그럼에도 불구하고 해결하고 싶다면
`module.pug` 파일의 118번째 줄을 다음과 같이 수정합니다.

```pug
	- var pageName = locals.page.replace("/", "_");
	- if(pageName !== "kkutu")
		script(type='text/javascript', src='/js/in_'+pageName+'.min.js')
```

**Comment by ttrrrrrddd** [comment]
조금 기다려보니 이런 오류가 나왔습니다.
Uncaught DOMException: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.
    at h (https://drkkutu.run.goorm.io/js/in_game_kkutu.min.js:21:31262)
    at Object.success (https://drkkutu.run.goorm.io/js/in_game_kkutu.min.js:21:16650)
    at f (https://drkkutu.run.goorm.io/js/jquery.js:19:18299)
    at Object.fireWith [as resolveWith] (https://drkkutu.run.goorm.io/js/jquery.js:19:19085)
    at r (https://drkkutu.run.goorm.io/js/jquery.js:21:16009)
    at XMLHttpRequest.r (https://drkkutu.run.goorm.io/js/jquery.js:21:21631)

**Comment by lshqqytiger** [comment]
#871 을 적용하신 상태인가요?

**Comment by Preta-Crowz** [comment]
웹서버는 https를 사용하지만 게임서버가 wss가 아닌 ws를 사용하고 있는것 같습니다. 보안 연결 관련 설정을 진행해주셔야합니다.

**Comment by locozz21** [comment]
구름IDE에서 인증서가 보이지 않습니다 ㅠㅡㅠ

**Comment by lshqqytiger** [comment]
구름IDE에 의해 유저는 구름IDE 서버와 보안 연결을 하고 있지만 끄투 웹 서버에서 클라이언트에게 게임 채널과 웹 소켓 통신 시 보안 연결을 사용하지 않도록 잘못 알려주고 있습니다.
#871 을 사용하면 해결할 수 있습니다.
게임 채널 포트가 2083으로 설정되어 있는 것으로 보아 이미 #871 은 확인하신 것 같은데 `global.json` 파일에서 WAF를 사용하도록 설정하셨나요?

**Comment by locozz21** [comment]
아니요. 사용하지 않게 했습니다. 실외라 집에가서 시도해보겠습니다.

**Comment by ttrrrrrddd** [comment]
가서 SSL 모두 수정 하고 서버를 실행 했더니 이런 오류가 뜨며 켜지지 않습니다.
(게임 서버)
root@goorm:/workspace/KKUTU/KKuTu/Server(master)# node lib/Game/cluster.js 0 1
[2022-10-11 08:50:07] Error from Redis: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
[2022-10-11 08:50:07] Run with no-redis mode.
[2022-10-11 08:50:07] << KKuTu Server:null >>
[2022-10-11 08:50:07] Master DB is ready.
[2022-10-11 08:50:08] Error from Redis: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
[2022-10-11 08:50:08] Run with no-redis mode.
[2022-10-11 08:50:08] DB is ready. ^C
(웹 서버)
root@goorm:/workspace/KKUTU/KKuTu/Server(master)# node lib/Web/cluster.js 1
[2022-10-11 08:50:11] << KKuTu Web >>
[2022-10-11 08:50:12] OAuth Strategy daldalso is not loaded
[2022-10-11 08:50:12] OAuth2Strategy requires a clientID option
[2022-10-11 08:50:12] OAuth Strategy naver is not loaded
[2022-10-11 08:50:12] OAuth2Strategy requires a clientID option
[2022-10-11 08:50:12] OAuth Strategy facebook is not loaded
[2022-10-11 08:50:12] OAuth2Strategy requires a clientID option
[2022-10-11 08:50:12] OAuth Strategy google is not loaded
[2022-10-11 08:50:12] OAuth2Strategy requires a clientID option
[2022-10-11 08:50:12] OAuth Strategy twitter is not loaded
[2022-10-11 08:50:12] OAuthStrategy requires a consumerKey option
[2022-10-11 08:50:12] OAuth Strategy kakao is not loaded
[2022-10-11 08:50:12] OAuth2Strategy requires a clientID option
[2022-10-11 08:50:12] OAuth Strategy discord is not loaded
[2022-10-11 08:50:12] OAuth2Strategy requires a clientID option
[2022-10-11 08:50:12] OAuth Strategy twitch is not loaded
[2022-10-11 08:50:12] OAuth2Strategy requires a clientID option
[2022-10-11 08:50:12] OAuth Strategy github is not loaded
[2022-10-11 08:50:12] OAuth2Strategy requires a clientID option
[2022-10-11 08:50:12] OAuth Strategy line is not loaded
[2022-10-11 08:50:12] OAuth2Strategy requires a clientID option
[2022-10-11 08:50:12] OAuth Strategy instagram is not loaded
[2022-10-11 08:50:12] OAuth2Strategy requires a clientID option
[2022-10-11 08:50:12] OAuth Strategy spotify is not loaded
[2022-10-11 08:50:12] OAuth2Strategy requires a clientID option
[2022-10-11 08:50:12] Error from Redis: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
[2022-10-11 08:50:12] Run with no-redis mode.
[2022-10-11 08:50:12] Game server #1 has an error: Error: write EPROTO 140330403977088:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/recor
d/ssl3_record.c:332:

[2022-10-11 08:50:12] Game server #1 closed: 1006
[2022-10-11 08:50:12] DB is ready. ^C

**Comment by Preta-Crowz** [comment]
SSL 버전 오류, OAuth 미사용 컨픽까지 불러옴, 레디스 없음..

**Comment by locozz21** [comment]
죄송합니다. SSL은 잘 다루지 못해서요..

**Comment by lshqqytiger** [comment]
해결 되었습니다.
구름IDE가 포트를 직접 포워딩해주지 않아서 프록시로 우회하여 웹 소켓과 연결하였습니다.

**Comment by ttrrrrrddd** [comment]
해결 되었습니다. 이슈 닫겠습니다.
도와주신 분들 정말 감사합니다.
