### ISSUE TITLE
불러오는중1

### ISSUE THREAD

**Issue by frgrtyt** [JJoriping/KKuTu#1069]
안녕하세요 네이버 로그인 했는데 불러오는중1 이라고뜹니다ㅠㅠㅠ

**Comment by lshqqytiger** [comment]
F12 키를 눌러 개발자 도구를 열고 Console 탭에서 어떤 오류가 뜨는지 확인해보세요.

**Comment by CHEEY-BORIN** [comment]
#689

**Comment by turtle85917** [comment]
#689

**Comment by frgrtyt** [comment]
아무것도 안뜹니다

**Comment by frgrtyt** [comment]
[2023-01-17 13:35:15] ERROR OCCURRED ON THE MASTER! :8080 [2023-1-17 1:35:15 ├F10: PM┤] ERROR: TypeError: Cannot read property 'replace' of undefined TypeError: Cannot read property 'replace' of undefined at C:\Users\nsh02\OneDrive\바탕 화면\새 폴더 (12)\KKuTu-master\Server\lib\Game\master.js:444:51 at exports.Tail.go (C:\Users\nsh02\OneDrive\바탕 화면\새 폴더 (12)\KKuTu-master\Server\lib\sub\lizard.js:43:16) at C:\Users\nsh02\OneDrive\바탕 화면\새 폴더 (12)\KKuTu-master\Server\lib\Game\kkutu.js:463:11 at callback (C:\Users\nsh02\OneDrive\바탕 화면\새 폴더 (12)\KKuTu-master\Server\lib\sub\collection.js:316:13) at Query.preCB (C:\Users\nsh02\OneDrive\바탕 화면\새 폴더 (12)\KKuTu-master\Server\lib\sub\collection.js:298:6) at Query.handleReadyForQuery (C:\Users\nsh02\OneDrive\바탕 화면\새 폴더 (12)\KKuTu-master\Server\lib\node_modules\pg\lib\query.js:138:12) at Client._handleReadyForQuery (C:\Users\nsh02\OneDrive\바탕 화면\새 폴더 (12)\KKuTu-master\Server\lib\node_modules\pg\lib\client.js:290:19) at Connection.emit (events.js:315:20) at C:\Users\nsh02\OneDrive\바탕 화면\새 폴더 (12)\KKuTu-master\Server\lib\node_modules\pg\lib\connection.js:114:12 at Parser.parse (C:\Users\nsh02\OneDrive\바탕 화면\새 폴더 (12)\KKuTu-master\Server\lib\node_modules\pg-protocol\dist\parser.js:40:17)
[2023-01-17 13:35:40] 58.79.231.77@dnC0yxBefU kkutu, {}
[2023-01-17 13:35:40] Exit #QJ4EWu0RFt8Y7omGQsPpQDr8fmj-lDOtL4PtU0Mi5OM
[2023-01-17 13:35:40] ERROR OCCURRED ON THE MASTER! :8080 [2023-1-17 1:35:40 ├F10: PM┤] ERROR: TypeError: Cannot read property 'handleCommandComplete' of null TypeError: Cannot read property 'handleCommandComplete' of null at Client._handleCommandComplete (C:\Users\nsh02\OneDrive\바탕 화면\새 폴더 (12)\KKuTu-master\Server\lib\node_modules\pg\lib\client.js:360:22) at Connection.emit (events.js:315:20) at C:\Users\nsh02\OneDrive\바탕 화면\새 폴더 (12)\KKuTu-master\Server\lib\node_modules\pg\lib\connection.js:114:12 at Parser.parse (C:\Users\nsh02\OneDrive\바탕 화면\새 폴더 (12)\KKuTu-master\Server\lib\node_modules\pg-protocol\dist\parser.js:40:17) at Socket.&lt;anonymous> (C:\Users\nsh02\OneDrive\바탕 화면\새 폴더 (12)\KKuTu-master\Server\lib\node_modules\pg-protocol\dist\index.js:11:42) at Socket.emit (events.js:315:20) at addChunk (_stream_readable.js:295:12) at readableAddChunk (_stream_readable.js:271:9) at Socket.Readable.push (_stream_readable.js:212:10) at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
[2023-01-17 13:35:40] New user #guest__dnC0yxBefUl6KL6-NTrRRIay7jty--VQ
[2023-01-17 13:35:40] ERROR OCCURRED ON THE MASTER! :8080 [2023-1-17 1:35:40 ├F10: PM┤] ERROR: TypeError: Cannot read property 'handleRowDescription' of null TypeError: Cannot read property 'handleRowDescription' of null at Client._handleRowDescription (C:\Users\nsh02\OneDrive\바탕 화면\새 폴더 (12)\KKuTu-master\Server\lib\node_modules\pg\lib\client.js:340:22) at Connection.emit (events.js:315:20) at C:\Users\nsh02\OneDrive\바탕 화면\새 폴더 (12)\KKuTu-master\Server\lib\node_modules\pg\lib\connection.js:114:12 at Parser.parse (C:\Users\nsh02\OneDrive\바탕 화면\새 폴더 (12)\KKuTu-master\Server\lib\node_modules\pg-protocol\dist\parser.js:40:17) at Socket.&lt;anonymous> (C:\Users\nsh02\OneDrive\바탕 화면\새 폴더 (12)\KKuTu-master\Server\lib\node_modules\pg-protocol\dist\index.js:11:42) at Socket.emit (events.js:315:20) at addChunk (_stream_readable.js:295:12) at readableAddChunk (_stream_readable.js:271:9) at Socket.Readable.push (_stream_readable.js:212:10) at TCP.onStreamRead (internal/stream_base_commons.js:186:23) [2023-01-17 13:35:40] ERROR OCCURRED ON THE MASTER! :8080 [2023-1-17 1:35:40 ├F10: PM┤] ERROR: TypeError: Cannot read property 'handleRowDescription' of null TypeError: Cannot read property 'handleRowDescription' of null at Client._handleRowDescription (C:\Users\nsh02\OneDrive\바탕 화면\새 폴더 (12)\KKuTu-master\Server\lib\node_modules\pg\lib\client.js:340:22) at Connection.emit (events.js:315:20) at C:\Users\nsh02\OneDrive\바탕 화면\새 폴더 (12)\KKuTu-master\Server\lib\node_modules\pg\lib\connection.js:114:12 at Parser.parse (C:\Users\nsh02\OneDrive\바탕 화면\새 폴더 (12)\KKuTu-master\Server\lib\node_modules\pg-protocol\dist\parser.js:40:17) at Socket.&lt;anonymous> (C:\Users\nsh02\OneDrive\바탕 화면\새 폴더 (12)\KKuTu-master\Server\lib\node_modules\pg-protocol\dist\index.js:11:42) at Socket.emit (events.js:315:20) at addChunk (_stream_readable.js:295:12) at readableAddChunk (_stream_readable.js:271:9) at Socket.Readable.push (_stream_readable.js:212:10) at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
[2023-01-17 13:35:43] Exit #guest__dnC0yxBefUl6KL6-NTrRRIay7jty--VQ
[2023-01-17 13:35:43] ERROR OCCURRED ON THE MASTER! :8080 [2023-1-17 1:35:43 ├F10: PM┤] ERROR: TypeError: Cannot read property 'handleCommandComplete' of null TypeError: Cannot read property 'handleCommandComplete' of null at Client._handleCommandComplete (C:\Users\nsh02\OneDrive\바탕 화면\새 폴더 (12)\KKuTu-master\Server\lib\node_modules\pg\lib\client.js:360:22) at Connection.emit (events.js:315:20) at C:\Users\nsh02\OneDrive\바탕 화면\새 폴더 (12)\KKuTu-master\Server\lib\node_modules\pg\lib\connection.js:114:12 at Parser.parse (C:\Users\nsh02\OneDrive\바탕 화면\새 폴더 (12)\KKuTu-master\Server\lib\node_modules\pg-protocol\dist\parser.js:40:17) at Socket.&lt;anonymous> (C:\Users\nsh02\OneDrive\바탕 화면\새 폴더 (12)\KKuTu-master\Server\lib\node_modules\pg-protocol\dist\index.js:11:42) at Socket.emit (events.js:315:20) at addChunk (_stream_readable.js:295:12) at readableAddChunk (_stream_readable.js:271:9) at Socket.Readable.push (_stream_readable.js:212:10) at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
[2023-01-17 13:35:46] 58.79.231.77@dnC0yxBefU kkutu, {}
[2023-01-17 13:35:47] New user #guest__dnC0yxBefUl6KL6-NTrRRIay7jty--VQ
[2023-01-17 13:35:47] ERROR OCCURRED ON THE MASTER! :8080 [2023-1-17 1:35:47 ├F10: PM┤] ERROR: TypeError: Cannot read property 'handleRowDescription' of null TypeError: Cannot read property 'handleRowDescription' of null at Client._handleRowDescription (C:\Users\nsh02\OneDrive\바탕 화면\새 폴더 (12)\KKuTu-master\Server\lib\node_modules\pg\lib\client.js:340:22) at Connection.emit (events.js:315:20) at C:\Users\nsh02\OneDrive\바탕 화면\새 폴더 (12)\KKuTu-master\Server\lib\node_modules\pg\lib\connection.js:114:12 at Parser.parse (C:\Users\nsh02\OneDrive\바탕 화면\새 폴더 (12)\KKuTu-master\Server\lib\node_modules\pg-protocol\dist\parser.js:40:17) at Socket.&lt;anonymous> (C:\Users\nsh02\OneDrive\바탕 화면\새 폴더 (12)\KKuTu-master\Server\lib\node_modules\pg-protocol\dist\index.js:11:42) at Socket.emit (events.js:315:20) at addChunk (_stream_readable.js:295:12) at readableAddChunk (_stream_readable.js:271:9) at Socket.Readable.push (_stream_readable.js:212:10) at TCP.onStreamRead (internal/stream_base_commons.js:186:23) [2023-01-17 13:35:47] ERROR OCCURRED ON THE MASTER! :8080 [2023-1-17 1:35:47 ├F10: PM┤] ERROR: TypeError: Cannot read property 'handleRowDescription' of null TypeError: Cannot read property 'handleRowDescription' of null at Client._handleRowDescription (C:\Users\nsh02\OneDrive\바탕 화면\새 폴더 (12)\KKuTu-master\Server\lib\node_modules\pg\lib\client.js:340:22) at Connection.emit (events.js:315:20) at C:\Users\nsh02\OneDrive\바탕 화면\새 폴더 (12)\KKuTu-master\Server\lib\node_modules\pg\lib\connection.js:114:12 at Parser.parse (C:\Users\nsh02\OneDrive\바탕 화면\새 폴더 (12)\KKuTu-master\Server\lib\node_modules\pg-protocol\dist\parser.js:40:17) at Socket.&lt;anonymous> (C:\Users\nsh02\OneDrive\바탕 화면\새 폴더 (12)\KKuTu-master\Server\lib\node_modules\pg-protocol\dist\index.js:11:42) at Socket.emit (events.js:315:20) at addChunk (_stream_readable.js:295:12) at readableAddChunk (_stream_readable.js:271:9) at Socket.Readable.push (_stream_readable.js:212:10) at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
[2023-01-17 13:37:43] Exit #guest__dnC0yxBefUl6KL6-NTrRRIay7jty--VQ
[2023-01-17 13:37:43] ERROR OCCURRED ON THE MASTER! :8080 [2023-1-17 1:37:43 ├F10: PM┤] ERROR: TypeError: Cannot read property 'handleCommandComplete' of null TypeError: Cannot read property 'handleCommandComplete' of null at Client._handleCommandComplete (C:\Users\nsh02\OneDrive\바탕 화면\새 폴더 (12)\KKuTu-master\Server\lib\node_modules\pg\lib\client.js:360:22) at Connection.emit (events.js:315:20) at C:\Users\nsh02\OneDrive\바탕 화면\새 폴더 (12)\KKuTu-master\Server\lib\node_modules\pg\lib\connection.js:114:12 at Parser.parse (C:\Users\nsh02\OneDrive\바탕 화면\새 폴더 (12)\KKuTu-master\Server\lib\node_modules\pg-protocol\dist\parser.js:40:17) at Socket.&lt;anonymous> (C:\Users\nsh02\OneDrive\바탕 화면\새 폴더 (12)\KKuTu-master\Server\lib\node_modules\pg-protocol\dist\index.js:11:42) at Socket.emit (events.js:315:20) at addChunk (_stream_readable.js:295:12) at readableAddChunk (_stream_readable.js:271:9) at Socket.Readable.push (_stream_readable.js:212:10) at TCP.onStreamRead (internal/stream_base_commons.js:186:23)

**Comment by lshqqytiger** [comment]
사용하고 계신 Node.js 버전과 PostgreSQL 버전이 어떻게 되실까요?

**Comment by D3rkBlue** [comment]
handleRowDescription의 문제로 보아, Node.Js의 있는 Pg 모듈이 웹서버 간의 충돌이 일어난것 같습니다.
Server/lib 경로의 Pg 모듈을 최신 버전으로 다시 다운 받아주세요.

**Comment by frgrtyt** [comment]
어디서 다운받죠?

**Comment by frgrtyt** [comment]
갑자기 서버와에 연결이 종료돼었습니다 라고뜹니다

**Comment by lshqqytiger** [comment]
#804 에서 이미 보고된 문제입니다.
Node.js, PostgreSQL, pg 간 호환 문제이고 버전을 잘 맞춰주면 해결됩니다.
Node.js 16, PostgreSQL 11, pg 8.0.3에서 정상 작동이 확인되었습니다.

**Comment by Preta-Crowz** [comment]
#689

**Comment by frgrtyt** [comment]
모듈 어케 다운 받죠?

**Comment by Preta-Crowz** [comment]
> 끄투 서버의 정상적인 운영을 위해서는 충분한 개발 실력을 요구합니다. 부족하다고 여겨질 경우, 다른 개발자를 구하거나 외주를 맡기시기 바랍니다. 이곳에서는 기능 구현 관련 질문에 대답해드릴 이유가 없습니다.
#689, 반복적으로 본 레포지토리와 관련 없는 기초 개발에 관한 질문을 올리시는 경우 차단 등의 조치가 취해질 수 있습니다.

**Comment by lshqqytiger** [comment]
[참고](https://docs.npmjs.com/cli/v7/commands/npm-install?v=true)

**Comment by frgrtyt** [comment]
모듈을 npm install 했는데도 안됍니다ㅠㅠ

**Comment by frgrtyt** [comment]
pg 다운로드 해도 안됍니다 (최신버전)

**Comment by lshqqytiger** [comment]
그럼 여기서는 더 이상 도와드릴 길이 없습니다.
Node.js 16, PostgreSQL 11, pg 8.0.3에서 정상 작동이 확인되었으며 본 레포지토리에는 문제가 없습니다.
