### ISSUE TITLE
끄투 서버 에러

### ISSUE THREAD

**Issue by frgrtyt** [JJoriping/KKuTu#1082]
[2023-05-20 18:37:13] ERROR OCCURRED ON THE MASTER! :8080 [2023. 5. 20. 오후 6:37:13] ERROR: TypeError: Cannot read properties of undefined (reading 'replace') TypeError: Cannot read properties of undefined (reading 'replace') at C:\Users\curung13\Desktop\KKuTu-master\KKuTu-master\Server\lib\Game\master.js:444:51 at exports.Tail.go (C:\Users\curung13\Desktop\KKuTu-master\KKuTu-master\Server\lib\sub\lizard.js:43:16) at C:\Users\curung13\Desktop\KKuTu-master\KKuTu-master\Server\lib\Game\kkutu.js:463:11 at callback (C:\Users\curung13\Desktop\KKuTu-master\KKuTu-master\Server\lib\sub\collection.js:316:13) at Query.preCB (C:\Users\curung13\Desktop\KKuTu-master\KKuTu-master\Server\lib\sub\collection.js:298:6) at Query.handleReadyForQuery (C:\Users\curung13\Desktop\KKuTu-master\KKuTu-master\Server\lib\node_modules\pg\lib\query.js:138:12) at Client._handleReadyForQuery (C:\Users\curung13\Desktop\KKuTu-master\KKuTu-master\Server\lib\node_modules\pg\lib\client.js:290:19) at Connection.emit (node:events:511:28) at C:\Users\curung13\Desktop\KKuTu-master\KKuTu-master\Server\lib\node_modules\pg\lib\connection.js:114:12 at Parser.parse (C:\Users\curung13\Desktop\KKuTu-master\KKuTu-master\Server\lib\node_modules\pg-protocol\dist\parser.js:40:17) 라고뜨는데 해결방법좀요ㅠㅠㅠ

**Comment by lshqqytiger** [comment]
PR #865 적용하신 적 있으신가요?

**Comment by frgrtyt** [comment]
없습니다

**Comment by lshqqytiger** [comment]
로그인 시 사용하신 OAuth API Provider가 무엇인가요?

**Comment by frgrtyt** [comment]
네이버 를 쓰고 있었으나 자꾸 그에러 때문에 구글로 바꿧는데 InternalOAuthError: failed to fetch user profile
    at C:\Users\curung13\Desktop\KKuTu-master\KKuTu-master\Server\lib\node_modules\passport-google-oauth2\lib\oauth2.js:92:28
    at passBackControl (C:\Users\curung13\Desktop\KKuTu-master\KKuTu-master\Server\lib\node_modules\oauth\lib\oauth2.js:132:9)
    at IncomingMessage.<anonymous> (C:\Users\curung13\Desktop\KKuTu-master\KKuTu-master\Server\lib\node_modules\oauth\lib\oauth2.js:157:7)
    at IncomingMessage.emit (node:events:523:35)
    at endReadableNT (node:internal/streams/readable:1367:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) 라고 뜨네요?

**Comment by lshqqytiger** [comment]
#1065 #598

**Comment by frgrtyt** [comment]
네이버에 대한 로그인 오류도 말씀해 주셨으면 좋겠습니다

**Comment by lshqqytiger** [comment]
네이버 OAuth API 설정에서 이름/별명을 가져오도록 되어있는지, 네이버 API 서버에서 이름/별명 값을 제대로 제공하고 있는지 확인해보세요.

**Comment by frgrtyt** [comment]
구글 버전 수정했으나 똑같이 에러가 납니다

**Comment by Preta-Crowz** [comment]
어디서 값이 비는지 코드를 보고, 로그를 찍어봅시다.
로깅은 디버깅의 기본입니다.

**Comment by frgrtyt** [comment]
최신버전 구글 oauth2 모듈을 사용하니 해결 됐습니다 수고하셨습니다 감사합니다
