### ISSUE TITLE
ssl 문의

### ISSUE THREAD

**Issue by curung** [JJoriping/KKuTu#1086]
이렇게 뜨네요...
internal/modules/cjs/loader.js:844 throw err; ^ SyntaxError: C:\Users\nsh02\Downloads\KKuTu-master\KKuTu-master\Server\lib\sub\
global.json: Unexpected token U in JSON at position 700 at JSON.parse (&lt;anonymous>) at Object.Module._extensions..json (internal/modules/cjs/loader.js:841:27) at Module.load (internal/modules/cjs/loader.js:685:32) at Function.Module._load (internal/modules/cjs/loader.js:620:12) at Module.require (internal/modules/cjs/loader.js:723:19) at require (internal/modules/cjs/helpers.js:14:16) at Object.&lt;anonymous> (C:\Users\nsh02\Downloads\KKuTu-master\KKuTu-master\Server\lib\const.js:19:14) at Module._compile (internal/modules/cjs/loader.js:816:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10) at Module.load (internal/modules/cjs/loader.js:685:32)
G: CLOSED WITH CODE 1
internal/modules/cjs/loader.js:844 throw err; ^ Synt
axError: C:\Users\nsh02\Downloads\KKuTu-master\KKuTu-master\Server\lib\sub\global.json: Unexpected token U in JSON at position 700 at JSON.parse (&lt;anonymous>) at Object.Module._extensions..json (internal/modules/cjs/loader.js:841:27) at Module.load (internal/modules/cjs/loader.js:685:32) at Function.Module._load (i
nternal/modules/cjs/loader.js:620:12) at Module.require (internal/modules/cjs/loader.js:723:19) at require (internal/modules/cjs/helpers.js:14:16) at Object.&lt;anonymous> (C:\Users\nsh02\Downloads\KKuTu-master\KKuTu-master\Server\lib\const.js:19:14) at Module._compile (internal/modules/cjs/loader.js:816:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10) at Module.load (internal/modules/cjs/loader.js:685:32)
G: CLOSED WITH CODE 1
internal/modules/cjs/loader.js:844 throw err; ^ SyntaxError: C:\Users\nsh02\Downloads\KKuTu-master\KKuTu-master\Server\lib\sub\global.json: Unexpected token U in JSON at position 700 at JSON.parse (&lt;anonymous>) at
Object.Module._extensions..json (internal/modules/cjs/loader.js:841:27) at Module.load (internal/modules/cjs/loader.js:685:32) at Function.Module._load (internal/modules/cjs/loader.js:620:12) at Module.require (internal/modules/cjs/loader.js:723:19) at require (internal/modules/cjs/helpers.js:14:16) at Object.&lt;anonymous> (C:\Users\nsh02\Downloads\KKuTu-master\KKuTu-master\Server\lib\const.js:19:14) at Module._compile (internal/modules/cjs/loader.js:816:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10) at Module.load (internal/modules/cjs/loader.js:685:32)
G: CLOSED WITH CODE 1
internal/modules/cjs/loader.js:844 throw err; ^ SyntaxError: C:\Users\nsh02\Downloads\KKuTu-master\KKuTu-master\Server\lib\sub\global.json: U
nexpected token U in JSON at position 700 at JSON.parse (&lt;anonymous>) at Object.Module._extensions..json (internal/modules/cjs/loader.js:841:27) at Module.load (internal/modules/cjs/loader.js:685:32) at Function.Module._load (internal/modules/cjs/loader.js:620:12) at Module.require (internal/modules/cjs/loader.js:723:19) at require (internal/modules/cjs/helpers.js:14:16) at O
bject.&lt;anonymous> (C:\Users\nsh02\Downloads\KKuTu-master\KKuTu-master\Server\lib\Web\db.js:22:15) at Module._compile (internal/modules/cjs/loader.js:816:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10) at Module.load (internal/modules/cjs/loader.js:685:32)
Worker 8940 died
W: CLOSED WITH CODE 0

**Comment by lshqqytiger** [comment]
global.json 파일에 문법 오류가 있습니다.
\\Users => \\\\Users 또는 /Users와 같이 수정.
