### ISSUE TITLE
그림퀴즈를 추가 후 갑자기 서버 매니저에 에러가 뜨며 워커가 죽습니다

### ISSUE THREAD

**Issue by aslhanball** [JJoriping/KKuTu#1103]
[2024-01-12 21:30:45] ERROR OCCURRED! This worker will die in 10 seconds. :8496 [2024-1-12 9:30:45 ├F10: PM┤] ERROR: Error: Cannot find module '../const' Require stack: - C:\Users\모자이크\Desktop\KKuTu-master\KKuTu-master\Server\lib\Game\games\drawing.js - C:\Users\모자이크\Desktop\KKuTu-master\KKuTu-master\Server\lib\Game\kkutu.js - C:\Users\모자이크\Desktop\KKuTu-master\KKuTu-master\Server\lib\Game\master.js - C:\Users\모자이크\Desktop\KKuTu-master\KKuTu-master\Server\lib\Game\slave.js - C:\Users\모자이크\Desktop\KKuTu-master\KKuTu-master\Server\lib\Game\cluster.js Error: Cannot find module '../const' Require stack: - C:\Users\모자이크\Desktop\KKuTu-master\KKuTu-master\Server\lib\Game\games\drawing.js - C:\Users\모자이크\Desktop\KKuTu-master\KKuTu-master\Server\lib\Game\kkutu.js - C:\Users\모자이크\Desktop\KKuTu-master\KKuTu-master\Server\lib\Game\master.js - C:\Users\모자이크\Desktop\KKuTu-master\KKuTu-master\Server\lib\Game\slave.js - C:\Users\모자이크\Desktop\KKuTu-master\KKuTu-master\Server\lib\Game\cluster.js at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15) at Function.Module._load (internal/modules/cjs/loader.js:667:27) at Module.require (internal/modules/cjs/loader.js:887:19) at require (internal/modules/cjs/helpers.js:74:18) at Object.&lt;anonymous> (C:\Users\모자이크\Desktop\KKuTu-master\KKuTu-master\Server\lib\Game\games\drawing.js:25:15) at Module._compile (internal/modules/cjs/loader.js:999:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10) at Module.load (internal/modules/cjs/loader.js:863:32) at Function.Module._load (internal/modules/cjs/loader.js:708:14) at Module.require (internal/modules/cjs/loader.js:887:19)

**Comment by mjonthemoon** [comment]
모든 변경 내용을 올바르게 적용했는지 확인해 주세요. 또 특정 PR로 인해 발생한 오류는 [해당 PR](https://github.com/JJoriping/KKuTu/pull/326)에 남겨 주세요.
