### ISSUE TITLE
Server error

### ISSUE THREAD

**Issue by aws2680** [JJoriping/KKuTu#124]
Error: bind EADDRINUSE null:80
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at listenOnMasterHandle (net.js:1339:16)
    at rr (internal/cluster/child.js:111:12)
    at Worker.send (internal/cluster/child.js:78:7)
    at process.onInternalMessage (internal/cluster/utils.js:42:8)
    at emitTwo (events.js:111:20)
    at process.emit (events.js:194:7)
    at process.nextTick (internal/child_process.js:766:12)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)

**Comment by JJoriping** [comment]
이슈 #107 을 참고해 보세요.
