### ISSUE TITLE
네이버 아이디로 로그인 (Oauth) 관련해서 질문 하나 드려봅니다.

### ISSUE THREAD

**Issue by Yukeu** [JJoriping/KKuTu#125]
Oauth 로그인까지 성공하고 정보제공 동의를 마치고 리다이렉트 되는데 

이런 문자가 출력됩니다.

ReferenceError: (네이버 클라이언트 키) is not defined
   at Object.exports.login (C:\Users\subtitle\Downloads\KKuTu-master\Server\lib\sub\jauth.js:40:15)
    at C:\Users\subtitle\Downloads\KKuTu-master\Server\lib\Web\main.js:265:8
    at Layer.handle [as handle_request] (C:\Users\subtitle\Downloads\KKuTu-master\Server\lib\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\subtitle\Downloads\KKuTu-master\Server\lib\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\subtitle\Downloads\KKuTu-master\Server\lib\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\subtitle\Downloads\KKuTu-master\Server\lib\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\subtitle\Downloads\KKuTu-master\Server\lib\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\Users\subtitle\Downloads\KKuTu-master\Server\lib\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\subtitle\Downloads\KKuTu-master\Server\lib\node_modules\express\lib\router\index.js:275:10)
    at Immediate.<anonymous> (C:\Users\subtitle\Downloads\KKuTu-master\Server\lib\node_modules\express-session\index.js:489:7)

어떻게 하라는건지 잘 모르겠습니다 ㅠㅠ 키가 정의되지 않았다는 것 까지는 알 수 있겠습니다만 ㅠㅠ 그 이후로는...

**Comment by Yukeu** [comment]
(서버환경은 제 컴퓨터를 DNS 서버로 연결해서 하고 있습니다.)

**Comment by JJoriping** [comment]
안녕하세요. `NAVER_ID` 자리에 따옴표 없이 네이버 앱 아이디를 입력한 것으로 추측됩니다. 네이버 앱 아이디는 파일 `./Server/lib/sub/jauth.js`의 19번째 줄에 적혀 있는 `"네이버 앱 아이디"` 자리에 따옴표를 없애지 않고 입력해 주세요.

**Comment by Yukeu** [comment]
앗! 어느순간 지워졌었네요.. 이거때문에 얼마나 헤맸는지.. 감사합니다!

**Comment by Yukeu** [comment]
해결 됐으니까 이 이슈는 닫겠습니다.
