### ISSUE TITLE
node lib/Web/cluster.js 1  을 쳤을시 오류가 발생

### ISSUE THREAD

**Issue by KoreanMJ** [JJoriping/KKuTu#198]
리눅스 환경에서 구축중에 서버를 켰을때

mj@MJ ~/바탕화면/Game/KKuTu/Server $ node lib/Web/cluster.js 1
[2017-11-14 21:42:37] << KKuTu Web >>
[2017-11-14 21:42:37] Game server #1 connected
[2017-11-14 21:42:37] DB is ready.
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: bind EACCES null:80
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at cb (net.js:1327:16)
    at rr (cluster.js:625:14)
    at Worker.<anonymous> (cluster.js:594:9)
    at process.<anonymous> (cluster.js:766:8)
    at emitTwo (events.js:111:20)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:787:12)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
Worker 18218 died
이라고 뜨고

lib/Game/cluster.js 0 1을 쳤을때는
mj@MJ ~/바탕화면/Game/KKuTu/Server $ node lib/Game/cluster.js 0 1
[2017-11-14 21:40:49] Master DB is ready.
[2017-11-14 21:40:49] << KKuTu Server:8496 >>
[2017-11-14 21:40:49] DB is ready.
와 같이 잘 켜집니다.

위에 lib/web/cluster.js 1을 쳤을때 저런 문구가 나오는데 어떻게 해결하나요?

**Comment by small-sunshines** [comment]
리눅스에서는 80 포트를 root 권한 없이 사용할 수 없습니다. nginx를 통한 리버스 프록시 구축이나, node.js 를 root 권한으로 실행시키는 방법이 있습니다만, express.js 로 구성된 끄투를 바로 root 권한으로 실행시키는 것은 권장하지 않습니다.
