### ISSUE TITLE
끄투 웹서버 오류

### ISSUE THREAD

**Issue by hatty163** [JJoriping/KKuTu#205]
_http_outgoing.js:503
    throw new errors.Error('ERR_HTTP_HEADERS_SENT', 'set');
    ^

Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at validateHeader (_http_outgoing.js:503:11)
    at ServerResponse.setHeader (_http_outgoing.js:510:3)
    at ServerResponse.header (C:\Users\Administrator\Desktop\KKuTu\Server\lib\node_modules\express\lib\response.js:767:10)
    at ServerResponse.contentType (C:\Users\Administrator\Desktop\KKuTu\Server\lib\node_modules\express\lib\response.js:595:15)
    at ServerResponse.sendStatus (C:\Users\Administrator\Desktop\KKuTu\Server\lib\node_modules\express\lib\response.js:357:8)
    at onKKuTuDB (C:\Users\Administrator\Desktop\KKuTu\Server\lib\Web\routes\admin.js:171:18)
    at Timeout._onTimeout (C:\Users\Administrator\Desktop\KKuTu\Server\lib\Web\routes\admin.js:151:6)
    at ontimeout (timers.js:485:15)
    at tryOnTimeout (timers.js:302:5)
    at Timer.listOnTimeout (timers.js:262:5)
Worker 3372 died

웹서버에서 갑자기 이런 에러가 발생하네요. 끄투 소스 문제인거 같아 올려봅니다. 무엇이 문제인가요?

**Comment by JJoriping** [comment]
소스 코드를 어떻게 수정했는지는 알 수 없습니다만, 해당 오류는 메소드 `writeHead()`, `sendStatus()` 등으로 메시지를 클라이언트로 전송한 이후에 또 다시 메시지를 전송하려 했을 때 발생합니다.

**Comment by hatty163** [comment]
해결되었습니다. 감사합니다.
