### ISSUE TITLE
네이버 아이디로 로그인에(Oauth) 관련해서 질문 드립니다.

### ISSUE THREAD

**Issue by vkdlfl** [JJoriping/KKuTu#207]
#125 에서 쪼리핑님이 " 를 지우지 않고 해야 된다 하셨는데 저는 " 가 있는데도
ReferenceError: (클라이언트 키) is not defined
    at Object.exports.logout (C:\Users\USER\Desktop\KKuTu-master.vol1\Server\lib\sub\jauth.js:176:15)
    at C:\Users\USER\Desktop\KKuTu-master.vol1\Server\lib\Web\main.js:255:8
    at Layer.handle [as handle_request] (C:\Users\USER\Desktop\KKuTu-master.vol1\Server\lib\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\USER\Desktop\KKuTu-master.vol1\Server\lib\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\USER\Desktop\KKuTu-master.vol1\Server\lib\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\USER\Desktop\KKuTu-master.vol1\Server\lib\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\USER\Desktop\KKuTu-master.vol1\Server\lib\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\Users\USER\Desktop\KKuTu-master.vol1\Server\lib\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\USER\Desktop\KKuTu-master.vol1\Server\lib\node_modules\express\lib\router\index.js:275:10)
    at Immediate.<anonymous> (C:\Users\USER\Desktop\KKuTu-master.vol1\Server\lib\node_modules\express-session\index.js:489:7)
가 뜨는데 어떻게 해야되죠?

**Comment by JJoriping** [comment]
안녕하세요. 파일 `./Server/lib/sub/jauth.js`의 176번째 줄에도 따옴표가 들어가 있는지 확인해 보세요.

**Comment by small-sunshines** [comment]
이번에 새로 업데이트된 부분을 참고해주세요.

auth.json을 통해 Oauth 환경을 더욱 간단히 설정할 수 있습니다.
