### ISSUE TITLE
run.bat 실행안됨

### ISSUE THREAD

**Issue by edisondl** [JJoriping/KKuTu#219]
D:\KKUTu\master\KKuTu-master\Server>run.bat

D:\KKUTu\master\KKuTu-master\Server>npm start

> kkutu-server@2.5.0 start D:\KKUTu\master\KKuTu-master\Server
> electron .

D:\KKUTu\master\KKuTu-master\Server\node_modules\electron\index.js:9
  throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again')
  ^

Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
    at Object.<anonymous> (D:\KKUTu\master\KKuTu-master\Server\node_modules\electron\index.js:9:9)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\KKUTu\master\KKuTu-master\Server\node_modules\electron\cli.js:3:16)
    at Module._compile (module.js:635:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kkutu-server@2.5.0 start: `electron .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the kkutu-server@2.5.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\myPC\AppData\Roaming\npm-cache\_logs\2017-12-07T11_45_16_086Z-debug.log

run.bat 파일을 실행 하면 나는 오류입니다.ㅜㅐㅇㄷ.ㅓㄴ.재설치 해봤는데 이러네요.
어디가 문제일까요?

**Comment by CraftyDragon678** [comment]
node.js가 아니라 npm이용해서 Electron을 다시 재설치 해보시겠어요?

**Comment by edisondl** [comment]
음...죄송한데 어떻게 설치하는지 아시나요?

**Comment by CraftyDragon678** [comment]
npm uninstall electron
npm install electron

**Comment by edisondl** [comment]
그래도 동일한 오류가 발생하고 설치하면 node install.js 에서 멈추네요.

**Comment by CraftyDragon678** [comment]
node install.js가 뭐죠? install.js파일은 없는데...

**Comment by edisondl** [comment]
C:\Users\myPC>D:
D:\>cd D:\KKUTu\master\KKuTu-master\Server\node_modules
D:\KKUTu\master\KKuTu-master\Server\node_modules>npm install electron
> electron@1.7.9 postinstall D:\KKUTu\master\KKuTu-master\Server\node_modules\electron
> node install.js

이렇게 되네요.
저기서 딱 멈춥니다.

**Comment by edisondl** [comment]
아 다 재설치 하니까 되네요.
감사합니다!
