### ISSUE TITLE
인기 단어 파일의 경로에 대해

### ISSUE THREAD

**Issue by kjs6170** [JJoriping/KKuTu#248]
기본 셋팅을 기준으로 global.json에 입력되어 있는 인기 단어 파일의 주소(/kkutu/data/kkutuhot.json)가 정확히 어느 경로를 나타내는 것인지를 모르겠습니다. 파일을 나름대로 이곳 저곳에 작성해 보았습니다만 관리 페이지에서 인기 단어 조회시 file 변수 자체가 정의되지 못하고 서버가 계속해서 뻗네요.
-----
오류:
D:\bu\kkutufinal\KKuTu-master\Server\lib\Web\routes\admin.js:118 var data = JSON.parse(file.toString()); ^ TypeError: Cannot read property 'toString' of undefined at ReadFileContext.callback (D:\bu\kkutufinal\KKuTu-master\Server\lib\Web\routes\admin.js:118:30) at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)
-----

아니면 다른 문제가 있는 것인가요?

p.s. 오류를 붙여넣으면서 서식에 오류가 생겼는지 글씨가 지나치게 커진 점은 죄송합니다(...).

**Comment by kjs6170** [comment]
오류를 붙여넣으면서 서식에 오류가 생겼는지 글씨가 지나치게 커진 점은 죄송합니다(...).

**Comment by kjs6170** [comment]
해결.
