### ISSUE TITLE
끄투서버가 자꾸 멈춥니다

### ISSUE THREAD

**Issue by Emily23805** [JJoriping/KKuTu#252]
[2018-01-08 14:08:45] &lt;&lt; KKuTu Server:8496 >>
[2018-01-08 14:08:45] &lt;&lt; KKuTu Web >>
TypeError: OAuth2Strategy requires a clientID option at Strategy.OAuth2Strategy (C:\KKuTu-master\Server\lib\node_modules\passport-oauth2\lib\strategy.js:82:34) at new Strategy (C:\KKuTu-master\Server\lib\node_modules\passport-facebook\lib\strategy.js:54:18) at glob.then (C:\KKuTu-master\Server\lib\Web\routes\login.js:75:26) at &lt;anonymous>
[2018-01-08 14:08:45] Error from Redis: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
[2018-01-08 14:08:45] Run with no-redis mode.
[2018-01-08 14:08:46] Master DB is ready.
[2018-01-08 14:08:46] New web server #1
[2018-01-08 14:08:46] Game server #1 connected
[2018-01-08 14:08:46] Error from Redis: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
[2018-01-08 14:08:46] Run with no-redis mode.
[2018-01-08 14:08:46] DB is ready.
[2018-01-08 14:08:46] Error from Redis: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
[2018-01-08 14:08:46] Run with no-redis mode.
[2018-01-08 14:08:46] DB is ready.
events.js:183 throw er; // Unhandled 'error' event ^ Error: bind EACCES null:80 at Object._errnoException (util.js:1022:11) at _exceptionWithHostPort (util.js:1044:20) at listenOnMasterHandle (net.js:1411:16) at rr (internal/cluster/child.js:111:12) at Worker.send (internal/cluster/child.js:78:7) at process.onInternalMessage (internal/cluster/utils.js:42:8) at emitTwo (events.js:131:20) at process.emit (events.js:214:7) at emit (internal/child_process.js:772:12) at _combinedTickCallback (internal/process/next_tick.js:141:11)
[2018-01-08 14:08:46] Exit web server #1
Worker 19852 died
W: CLOSED WITH CODE 0

모든 80또는8080포트를 쓰는 모든 서비스를 껏음에도 자꾸 이 에러가 뜹니다

**Comment by small-sunshines** [comment]
우선 사용하지 않는 SNS의 파일을 사용하지 않도록 바꿔주세요.

파일이름 앞이나 뒤에 DISABLE 를 붙여

DISABLE.auth_kakao.js

또는

auth_kakao.js.DISABLE

같은 식으로 파일이름을 바꿔주신 뒤 다시 서버를 켜주시면 됩니다.

두번째로 Redis 를 사용하시는 것인데요..

필요 없으시다면 궂이 사용하지 않으셔도 됩니다만, 사용하시는 것을 권장드립니다.

제가 알려드린 두 사항을 조치하면 서버가 멈추는 일은 자주 없을것입니다.
