### ISSUE TITLE
끄투 서버 거의 다만들어졌는데...

### ISSUE THREAD

**Issue by bokmook** [JJoriping/KKuTu#269]
끄투 서버 거의다만들어졌는데 이게뜨네요 ㅠㅠ
TypeError: OAuth2Strategy requires a clientID option at Strategy.OAuth2Strategy (경로가림\KKuTu-master\Server\lib\node_modules\passport-oauth2\lib\strategy.js:82:34) at new Strategy (경로가림\KKuTu-master\Server\lib\node_modules\passport-facebook\lib\strategy.js:54:18) at glob.then (
(경로가림\KKuTu-master\Server\lib\Web\routes\login.js:75:26) at &lt;anonymous>
[2018-02-19 18:00:41] Error from Redis: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
[2018-02-19 18:00:41] Run with no-redis mode.
[2018-02-19 18:00:41] Error when connect to PostgreSQL server: error: password authentication failed for user "postgres"
[2018-02-19 18:00:42] Error from Redis: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379 [2018-02-19 18:00:42] Run with no-redis mode.
[2018-02-19 18:00:42] Error when connect to PostgreSQL server: error: password authentication failed for user "postgres"
[2018-02-19 18:00:42] Game server #1 has an error: Error: connect ECONNREFUSED 127.0.0.2:8080
[2018-02-19 18:00:42] Game server #1 closed: 1006
[2018-02-19 18:00:42] Error from Redis: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379 [2018-02-19 18:00:42] Run with no-redis mode.
[2018-02-19 18:00:42] Error when connect to PostgreSQL server: error: password authentication failed for user "postgres"

급해요 ㅠㅠ

**Comment by small-sunshines** [comment]
#268 참고해주세요.

**Comment by ps2cho** [comment]
포트를 8080에서 다른걸로 바꾸셔야합니다. 그리고 #268에 나온것도 하세요.

**Comment by bokmook** [comment]
@ps2cho 포트를 8080에서 무엇으로 바꿔야하나요?

**Comment by ps2cho** [comment]
아무거나 상관없습니다

**Comment by ps2cho** [comment]
똑같은게 있으면 안되니까 안되면 여러개 시도해보세요. 네 숫자면 되요
