### ISSUE TITLE
방금 새로 서버 열었는데 감자서버 오프라인이라네요

### ISSUE THREAD

**Issue by ps2cho** [JJoriping/KKuTu#270]
사이트는 열렸는데 감자 서버가 안열렸다고 뜹니다. 어케 해야하나요?

**Comment by CraftyDragon678** [comment]
로그를 보여주실 수 있나요?

**Comment by ps2cho** [comment]
game-server #1 closed: 1006

**Comment by hatty163** [comment]
전체 로그를 보여주셔야 도와드릴 수 있습니다 @ps2cho

**Comment by ps2cho** [comment]
[2018-02-21 11:44:21] &lt;&lt; KKuTu Server:8496 >>
[2018-02-21 11:44:21] &lt;&lt; KKuTu Web >>
TypeError: OAuth2Strategy requires a clientID option at Strategy.OAuth2Strategy (D:\Users\user\Downloads\KKuTu-master\Server\lib\node_modules\passport-oauth2\lib\strategy.js:82:34) at new Strategy (D:\Users\user\Downloads\KKuTu-master\Server\lib\node_modules\passport-facebook\lib\strategy.js:54:18) at glob.then (D:\Users\user\Downloads\KKuTu-master\Server\lib\Web\routes\login.js:75:26) at &lt;anonymous>
[2018-02-21 11:44:22] Game server #1 has an error: Error: read ECONNRESET
[2018-02-21 11:44:22] Game server #1 closed: 1006
[2018-02-21 11:44:22] Error from Redis: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
[2018-02-21 11:44:22] Run with no-redis mode.
[2018-02-21 11:44:22] Error from Redis: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
[2018-02-21 11:44:22] Run with no-redis mode.
[2018-02-21 11:44:22] DB is ready. [2018-02-21 11:44:22] Master DB is ready.
[2018-02-21 11:44:22] Error on ws: Error: listen EADDRINUSE 0.0.0.0:8080
[2018-02-21 11:44:23] Error from Redis: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379 [2018-02-21 11:44:23] Run with no-redis mode.
[2018-02-21 11:44:23] DB is ready.

**Comment by hatty163** [comment]
OAuth 파일을 설정하실 때, 사용하지 않는 파일은 모두 `auth_XXXX.js` 파일 확장자 뒤에 DISABLE을 붙여 `auth_XXXX.js.DISABLED`로 만들어 주셔야 합니다.

**Comment by ps2cho** [comment]
좀더 자세히 말씀해주실수있나요? oAuth가 어디에 있나요?

**Comment by ps2cho** [comment]
해보았는데 여전히 감자서버가 열리지않네요

**Comment by ps2cho** [comment]
TypeError: OAuth2Strategy requires a clientID option at Strategy.OAuth2Strategy (D:\Users\user\Downloads\KKuTu-master\Server\lib\node_modules\passport-oauth2\lib\strategy.js:82:34) at new Strategy (D:\Users\user\Downloads\KKuTu-master\Server\lib\node_modules\passport-facebook\lib\strategy.js:54:18) at glob.then (D:\Users\user\Downloads\KKuTu-master\Server\lib\Web\routes\login.js:75:26) at <anonymous>

이 에러는 없어졌네요

**Comment by TheRealTolspac** [comment]
redis가 6379포트를 개방하지 않은 것으로 보이는데
redis를 다운받으셔서 서버를 키면 해결됩니다.
