### ISSUE TITLE
로그인 추가하는데 scope부분에서 SyntaxError 발생

### ISSUE THREAD

**Issue by SJang1** [JJoriping/KKuTu#320]
(끄투경로)\Server\lib\Web\auth\auth_twitchtv.js scope: ['channel_read', 'user_read'] ^^^^^ SyntaxError: Unexpected identifier at createScript (vm.js:80:10) at Object.runInThisContext (vm.js:139:10) at Module._compile (module.js:616:28) at Object.Module._extensions..js (module.js:663:10) at Module.load (module.js:565:32) at tryModuleLoad (module.js:505:12) at Function.Module._load (module.js:497:3) at Module.require (module.js:596:17) at require (internal/module.js:11:18) at glob.then (끄투경로)\Server\lib\Web\routes\login.js:69:24)

해당 오류가 발생합니다.
(만들고 있는 로그인은 twitchtv며, \Server\lib\Web\auth\auth_twitchtv.js의 내용은
![image](https://user-images.githubusercontent.com/29011440/44082369-f8db47fa-9feb-11e8-8943-f54f59d403b4.png)
입니다.

**Comment by SJang1** [comment]
이 문제는 해결했으나, 이어서 이런 오류가 발생합니다.
Error when querying: SELECT * FROM users WHERE "_id"=(아이디) LIMIT 1 [2018-08-15 15:48:02] Context: error: operator does not exist: character varying = integer

**Comment by SJang1** [comment]
passReqToCallback: true뒤 , 붙이는걸 깜빡하고 있던걸로 해결완료
