### ISSUE TITLE
이거...(Windows)

### ISSUE THREAD

**Issue by swoo5571** [JJoriping/KKuTu#327]
TypeError: OAuth2Strategy requires a clientID option at Strategy.OAuth2Strategy (E:\KKuTu-master\KKuTu-master\Server\lib\node_modules\passport-oauth2\lib\strategy.js:82:34) at new Strategy (E:\KKuTu-master\KKuTu-master\Server\lib\node_modules\passport-google-oauth2\lib\oauth2.js:48:18) at glob.then (E:\KKuTu-master\KKuTu-master\Server\lib\Web\routes\login.js:75:26)
[2018-08-19 00:19:12] Error from Redis: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
[2018-08-19 00:19:12] Run with no-redis mode.
[2018-08-19 00:19:12] Error when connect to PostgreSQL server: error: password authentication failed for user "postgres"
[2018-08-19 00:19:12] Error from Redis: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
[2018-08-19 00:19:12] Run with no-redis mode.
[2018-08-19 00:19:12] Error when connect to PostgreSQL server: error: password authentication failed for user "postgres"
[2018-08-19 00:19:12] Game server #1 has an error: Error: connect ECONNREFUSED 127.0.0.2:8080
[2018-08-19 00:19:12] Game server #1 closed: 1006
[2018-08-19 00:19:12] Error from Redis: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379 [2018-08-19 00:19:12] Run with no-redis mode.
[2018-08-19 00:19:12] Error when connect to PostgreSQL server: error: password authentication failed for user "postgres"

**Comment by swoo5571** [comment]
아 그리고 국립국어원 그 한국어 단어 뜻 나오게 하는 것도 어떻게 하는지 알려주세요

**Comment by UnderC** [comment]
global.json에서 데이터베이스의 비밀번호를 입력을 안하셨거나 비밀번호가 맞지 않아서 생기는 오류입니다.

**Comment by swoo5571** [comment]
음..영어 단어 뜻은 있는데 한국어 뜻. 그니깐, 국립국어원에서 사전 정보를 어떻게 설정하죠?

**Comment by Preta-Crowz** [comment]
> 음..영어 단어 뜻은 있는데 한국어 뜻. 그니깐, 국립국어원에서 사전 정보를 어떻게 설정하죠?

국립국어원에 허락을 맡은 이후에, 직접 추가해야합니다.

**Comment by Preta-Crowz** [comment]
깜빡하고 말 안했는데, 다른 문제가 생겼을 경우에는 이슈를 새로 열어주셔야 처리가 수월합니다
