### ISSUE TITLE
그퀴 구축중 오류

### ISSUE THREAD

**Issue by ps2cho** [JJoriping/KKuTu#331]
ERROR OCCURRED ON THE MASTER! :2757 [2018-8-19 16:30:38] ERROR: Error: Cannot find module '../const' Error: Cannot find module '../const' at Function.Module._resolveFilename (module.js:547:15) at Function.Module._load (module.js:474:25) at Module.require (module.js:596:17) at require (internal/module.js:11:18) at Object.&lt;anonymous> (C:\Users\golds\Documents\KKuTu-master\Server\lib\Game\games\drawing.js:25:15) at Module._compile (module.js:652:30) at Object.Module._extensions..js (module.js:663:10) at Module.load (module.js:565:32) at tryModuleLoad (module.js:505:12) at Function.Module._load (module.js:497:3)
[2018-08-19 16:30:38] ERROR OCCURRED! This worker will die in 10 seconds. :2757 [2018-8-19 16:30:38] ERROR: Error: Cannot find module '../const' Error: Cannot find module '../const' at Function.Module._resolveFilename (module.js:547:15) at Function.Module._load (module.js:474:25) at Module.require (module.js:596:17) at require (internal/module.js:11:18) at Object.&lt;anonymous> (C:\Users\golds\Documents\KKuTu-master\Server\lib\Game\games\drawing.js:25:15) at Module._compile (module.js:652:30) at Object.Module._extensions..js (module.js:663:10) at Module.load (module.js:565:32) at tryModuleLoad (module.js:505:12) at Function.Module._load (module.js:497:3)

어케 하나요?

**Comment by small-sunshines** [comment]
PR 계속 봐주세요. 본 에러와 다른 에러도 수정되었습니다.

그리고 그퀴는 정식 출시되지 않았습니다.
