### ISSUE TITLE
서버 실행 누르면 다음과 같은 오류가 나옵니다.

### ISSUE THREAD

**Issue by Xenon2000** [JJoriping/KKuTu#334]
일단 글씨가 깨지고, 서버버킷은 초록불이 들어오지만 들어가는건 불가능 하네요

[2018-08-28 16:54:28] [36m&lt;&lt; KKuTu Server:8496 >>[39m
[2018-08-28 16:54:28] [36m&lt;&lt; KKuTu Web >>[39m
TypeError: OAuth2Strategy requires a clientID option at Strategy.OAuth2Strategy (C:\Users\204\Desktop\KKuTu-master\Server\lib\node_modules\passport-oauth2\lib\strategy.js:82:34) at new Strategy (C:\Users\204\Desktop\KKuTu-master\Server\lib\node_modules\passport-facebook\lib\strategy.js:54:18) at glob.then (C:\Users\204\Desktop\KKuTu-master\Server\lib\Web\routes\login.js:75:26)
[2018-08-28 16:54:29] [41mError from Redis: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379[49m
[2018-08-28 16:54:29] [33mRun with no-redis mode.[39m
[2018-08-28 16:54:29] [41mError when connect to PostgreSQL server: error: ������ "postgres"�� password ������ �����߽��ϴ�[49m
[2018-08-28 16:54:29] [41mError from Redis: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379[49m [2018-08-28 16:54:29] [33mRun with no-redis mode.[39m
[2018-08-28 16:54:29] [41mError when connect to PostgreSQL server: error: ������ "postgres"�� password ������ �����߽��ϴ�[49m
[2018-08-28 16:54:29] [43m[30mGame server #1 has an error: Error: connect ECONNREFUSED 127.0.0.2:8080[39m[49m
[2018-08-28 16:54:29] [41mGame server #1 closed: 1006[49m
[2018-08-28 16:54:30] [41mError from Redis: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379[49m [2018-08-28 16:54:30] [33mRun with no-redis mode.[39m
[2018-08-28 16:54:30] [41mError when connect to PostgreSQL server: error: ������ "postgres"�� password ������ �����߽��ϴ�[49m

**Comment by small-sunshines** [comment]
PostgreSQL 비밀번호를 확인해주세요. PostgreSQL 접속중 계정 관련 오류로 에러가 난 부분입니다.
