### ISSUE TITLE
실행시 오류

### ISSUE THREAD

**Issue by openkiwi-kang** [JJoriping/KKuTu#343]
의존성이 설치가 안되고 오류발생
module.js:549
    throw err;
    ^

Error: Cannot find module 'colors'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pi/kkutu/KKuTu/Server/lib/sub/jjlog.js:21:14)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

**Comment by minesna** [comment]
Server-setup.bat(일꺼에요 아마...)
실행하셨나요?

**Comment by openkiwi-kang** [comment]
네 npm 설치를 않했어욬
