### ISSUE TITLE
게임서버는되는데 webserver 는 ..

### ISSUE THREAD

**Issue by openkiwi-kang** [JJoriping/KKuTu#344]
module.js:549
    throw err;
    ^

Error: Cannot find module 'redis'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pi/kkutu/KKuTu/Server/lib/Web/main.js:28:14)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
Worker 9270 died

![image](https://user-images.githubusercontent.com/40848621/45407857-9d512500-b6a5-11e8-934b-d9ffb58ef444.png)
이건게임서버요

**Comment by kdwkr** [comment]
명령프롬포트(cmd)창에
```cmd
npm i redis
```
를 입력하여 redis 모듈을 설치하시면 됩니다.

기본적으로 프로그래밍을 할때 나는 오류는 대부분 구글에서 오류 메세지를 검색하시면 해결 방법을 찾을 수 있습니다.

**Comment by kdwkr** [comment]
README.md 읽어보신거 맞나요. install.bat 실행 하셨는지요
