### ISSUE TITLE
저는 그 데이터 배이스 세팅 하는 거 자체 가 안됩니다

### ISSUE THREAD

**Issue by ttakkku** [JJoriping/KKuTu#391]
cmd 에 들어가서 다 했는데  그 비밀번호가 안된다고 하네요 그 없다고 뜨는 게 아나라  그  무슨 이상한 말을 쓰고 끝납니다;;
?ㅻ쪟:  "main" ?대쫫???곗씠?곕쿋?댁뒪???대? ?덉쓬 이러게 에레가 납니다

**Comment by ttakkku** [comment]
그리고 이건 무슨 에레인가요??
[2018-12-01 17:41:18] Error from Redis: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
[2018-12-01 17:41:18] Run with no-redis mode.
[2018-12-01 17:41:18] Master DB is ready.
[2018-12-01 17:41:18] Error when querying: UPDATE users SET "server"='' WHERE "server"='0' [2018-12-01 17:41:18] Context: error: "users" 이름의 릴레이션(relation)이 없습니다
[2018-12-01 17:41:18] Error when querying: SELECT * FROM kkutu_shop WHERE TRUE [2018-12-01 17:41:18] Context: error: "kkutu_shop" 이름의 릴레이션(relation)이 없습니다
TypeError: OAuth2Strategy requires a clientID option at Strategy.OAuth2Strategy (C:\Users\k2005\Desktop\KKuTu-master\Server\lib\node_modules\passport-oauth2\lib\strategy.js:82:34) at new Strategy (C:\Users\k2005\Desktop\KKuTu-master\Server\lib\node_modules\passport-facebook\lib\strategy.js:54:18) at glob.then (C:\Users\k2005\Desktop\KKuTu-master\Server\lib\Web\routes\login.js:75:26)
[2018-12-01 17:41:19] New web server #1
[2018-12-01 17:41:19] Game server #1 connected
[2018-12-01 17:41:19] Error from Redis: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379 [2018-12-01 17:41:19] Run with no-redis mode.
[2018-12-01 17:41:19] DB is ready.
[2018-12-01 17:41:19] Error when querying: SELECT * FROM kkutu_shop WHERE TRUE
[2018-12-01 17:41:19] Context: error: "kkutu_shop" 이름의 릴레이션(relation)이 없습니다
[2018-12-01 17:41:20] Error from Redis: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379 [2018-12-01 17:41:20] Run with no-redis mode.
[2018-12-01 17:41:20] DB is ready.
[2018-12-01 17:41:20] Error when querying: SELECT * FROM kkutu_shop_desc WHERE TRUE [2018-12-01 17:41:20] Context: error: "kkutu_shop_desc" 이름의 릴레이션(relation)이 없습니다

**Comment by minesna** [comment]
"main" db에 INSERT가 잘못된거 같습니다..
DB 삭제후 다시시도 해보세요

**Comment by kkutulove** [comment]
메인 DB는 어떤폴더에있나요?

**Comment by lorlol701** [comment]
db.sql 말씀하시는 건가요?
