### ISSUE TITLE
웹 서버가 자꾸 닫힙니다.

### ISSUE THREAD

**Issue by usb9245** [JJoriping/KKuTu#395]
![image](https://user-images.githubusercontent.com/34123108/49692942-bdf82080-fba9-11e8-9134-a2563d5a882a.png)
서버 운영체제는 Ubuntu 18.04.1 LTS입니다.

**Comment by usb9245** [comment]
참고로 이렇게 뜹니다
```ubuntu@ip-172-26-8-231:~/KKuTu-master/Server$ node lib/Web/cluster.js 1
[2018-12-09 03:07:55] << KKuTu Web >>
[2018-12-09 03:07:56] Game server #1 connected
[2018-12-09 03:07:56] DB is ready.
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: bind EACCES null:80
    at listenOnMasterHandle (net.js:1325:16)
    at rr (internal/cluster/child.js:126:12)
    at Worker.send (internal/cluster/child.js:93:7)
    at process.onInternalMessage (internal/cluster/utils.js:45:8)
    at process.emit (events.js:194:15)
    at emit (internal/child_process.js:828:12)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
Emitted 'error' event at:
    at listenOnMasterHandle (net.js:1326:21)
    at rr (internal/cluster/child.js:126:12)
    [... lines matching original stack trace ...]
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
Worker 7915 died
ubuntu@ip-172-26-8-231:~/KKuTu-master/Server$

**Comment by Preta-Crowz** [comment]
80번 포트 바인딩 실패로 보입니다. 포트가 사용 중은 아닌지 확인하세요.

**Comment by usb9245** [comment]
![image](https://user-images.githubusercontent.com/34123108/49693062-c0a84500-fbac-11e8-8ea2-f7e7a1bf8477.png)
사용중은 아닙니다
