### ISSUE TITLE
2가지 질문 하겠습니다

### ISSUE THREAD

**Issue by 3110222F** [JJoriping/KKuTu#421]
환영합니다.
[2019-01-11 22:22:07] &lt;&lt; KKuTu Web >>
[2019-01-11 22:22:07] &lt;&lt; KKuTu Server:8496 >>
C:\Users\GoUSER\Desktop\HappyPlus\KKuTu-master\Server\lib\Web\auth\auth_naver.js:13 clientSecret: config.naver.4KpXqrjtTE, ^^ SyntaxError: Invalid or unexpected token at new Script (vm.js:84:7) at createScript (vm.js:264:10) at Object.runInThisContext (vm.js:312:10) at Module._compile (internal/modules/cjs/loader.js:684:28) at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10) at Module.load (internal/modules/cjs/loader.js:620:32) at tryModuleLoad (internal/modules/cjs/loader.js:560:12) at Function.Module._load (internal/modules/cjs/loader.js:552:3) at Module.require (internal/modules/cjs/loader.js:657:17) at require (internal/modules/cjs/helpers.js:22:18)
[2019-01-11 22:22:08] Error from Redis: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
[2019-01-11 22:22:08] Run with no-redis mode.
[2019-01-11 22:22:08] Master DB is ready.
[2019-01-11 22:22:09] Error from Redis: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
[2019-01-11 22:22:09] Run with no-redis mode.
[2019-01-11 22:22:09] DB is ready.
[2019-01-11 22:22:09] New web server #1
[2019-01-11 22:22:09] Game server #1 connected
[2019-01-11 22:22:09] Error from Redis: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
[2019-01-11 22:22:09] Run with no-redis mode.
[2019-01-11 22:22:09] DB is ready.

라고 뜹니다
저는 2가지 질문을 하겠습니다
1.저위에 auth오류는 어떻게 해야 해결되나요?
2.redis를 깔았는데 왜 또 깔라고 나오는 거죠?
![image](https://user-images.githubusercontent.com/31878663/51036148-90aaf200-15ef-11e9-90f9-5c7366530f99.png)

감사합니다.

**Comment by Preta-Crowz** [comment]
1. auth_naver.js를 기본값으로 돌리고, auth.json에 값을 입력해주어야합니다.
2. 레디스가 실행 중인지 확인해보세요.

**Comment by lshqqytiger** [comment]
클라이언트 시크릿 노출되셨습니다.
