### ISSUE TITLE
이 오류 해결법좀 알려주세요

### ISSUE THREAD

**Issue by Explorer4563** [JJoriping/KKuTu#449]
[2019-01-29 18:11:49] &lt;&lt; KKuTu Web >>
[2019-01-29 18:11:49] &lt;&lt; KKuTu Server:8496 >>
TypeError: OAuth2Strategy requires a clientID option at Strategy.OAuth2Strategy (C:\Users\maks0\Desktop\KKuTu\Server\lib\node_modules\passport-oauth2\lib\strategy.js:82:34) at new Strategy (C:\Users\maks0\Desktop\KKuTu\Server\lib\node_modules\passport-facebook\lib\strategy.js:54:18) at glob.then (C:\Users\maks0\Desktop\KKuTu\Server\lib\Web\routes\login.js:75:26)
[2019-01-29 18:11:49] Game server #1 has an error: Error: unexpected server response (404)
[2019-01-29 18:11:49] Game server #1 closed: 1006
[2019-01-29 18:11:50] Error from Redis: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
[2019-01-29 18:11:50] Run with no-redis mode.
[2019-01-29 18:11:50] Master DB is ready.
[2019-01-29 18:11:50] Error on ws: Error: listen EADDRINUSE: address already in use 0.0.0.0:8080
[2019-01-29 18:11:50] Error when querying: UPDATE users SET "server"='' WHERE "server"='0'
[2019-01-29 18:11:50] Context: error: "users" 이름의 릴레이션(relation)이 없습니다
[2019-01-29 18:11:50] Error when querying: SELECT * FROM kkutu_shop WHERE TRUE [2019-01-29 18:11:50] Context: error: "kkutu_shop" 이름의 릴레이션(relation)이 없습니다
[2019-01-29 18:11:50] Error from Redis: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379 [2019-01-29 18:11:50] Run with no-redis mode.
[2019-01-29 18:11:50] DB is ready.
[2019-01-29 18:11:50] Error when querying: SELECT * FROM kkutu_shop WHERE TRUE [2019-01-29 18:11:50] Context: error: "kkutu_shop" 이름의 릴레이션(relation)이 없습니다
[2019-01-29 18:11:50] Error from Redis: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
[2019-01-29 18:11:50] Run with no-redis mode.
[2019-01-29 18:11:50] DB is ready.
[2019-01-29 18:11:50] Error when querying: SELECT * FROM kkutu_shop_desc WHERE TRUE [2019-01-29 18:11:50] Context: error: "kkutu_shop_desc" 이름의 릴레이션(relation)이 없습니다

이렇게 오류가 뜨면서 서버가 안열립니다 오류 해결법좀..

**Comment by UnderC** [comment]
DB 작업을 하지 않으신것으로 확인됩니다.
http://blog.jjo.kr/220935346136
이 블로그를 보시면서 따라하시면 될 것 같습니다

**Comment by Explorer4563** [comment]
12번째 작업이 안됩니다 .

**Comment by Explorer4563** [comment]
C:/Users/maks0/Desktop/KKuTu: Permission denied 
이렇게 cmd에 오류가 떠요...

**Comment by lshqqytiger** [comment]
#418 과 동일한 문제입니다. 사용하지 않는 로그인 방식에는 .DIS 를 붙여주세요.

예시) auth_facebook.js.DIS

**Comment by lshqqytiger** [comment]
#418 과 같은 문제입니다. 사용하지 않는 로그인 방식에는 .DIS를 붙여주세요.

예시) auth_naver.js.DIS

**Comment by Explorer4563** [comment]
알겠습니다 그런데 클라이언트ID와 시크릿코드는 어떻게 얻을수있나요 네이버를 기준으로요..

**Comment by lshqqytiger** [comment]
구글에서 직접 찾아보세요.

https://developers.naver.com/products/login/api/

**Comment by Explorer4563** [comment]
이슈 에 나온대로 TCP UDP 에 80 , 8090 , 8506 ( 저는 8080으로 안하고 8090으로하였습니다 포트를 )
이렇게헀는데 저는 localhost , 192.168.XX.XXX ( 번호가림 ) http://mohumkkutu.kro.kr/
했는데 되는데 다른사람이 할때는 안됍니다... 포트가 잘못된것인가요?

**Comment by UnderC** [comment]
내부 아이피(192.168.12.104) 와 연결이 된것으로 확인됩니다.
외부 아이피로 도메인을 다시 연결해 주세요

**Comment by Explorer4563** [comment]
![default](https://user-images.githubusercontent.com/47138537/52164007-2d176e80-272e-11e9-822b-f6d42636df79.png)

다른사람은 이제 잘 접속이 돼는데 저는 왜 도메인으로 들어가지지가 않을까요 ..

**Comment by Explorer4563** [comment]
아직도 안들어가지네요...
T.T
