### ISSUE TITLE
관리페이지에서 상점DB다루기에서 options 2개 불가능한가요

### ISSUE THREAD

**Issue by Explorer4563** [JJoriping/KKuTu#455]
아이템에 gif설정 옵션과 추가 경험치 설정을 넣고싶은데 옵션에 {} 이 괄호 안에 1개밖에 못넣더군요 
{}를 추가해서 하는방법도 안되고 2개를 동시에 넣어도 안되고 그냥 옵션에 2개이상의 옵션이 있으면 
SyntaxError: Unexpected token { in JSON at position 12 at JSON.parse (&lt;anonymous>) at C:\Users\maks0\Desktop\KKuTu\Server\lib\Web\routes\admin.js:253:28 at Array.forEach (&lt;anonymous>) at C:\Users\maks0\Desktop\KKuTu\Server\lib\Web\routes\admin.js:252:7 at Layer.handle [as handle_request] (C:\Users\maks0\Desktop\KKuTu\Server\lib\node_modules\express\lib\router\layer.js:95:5) at next (C:\Users\maks0\Desktop\KKuTu\Server\lib\node_modules\express\lib\router\route.js:137:13) at Route.dispatch (C:\Users\maks0\Desktop\KKuTu\Server\lib\node_modules\express\lib\router\route.js:112:3) at Layer.handle [as handle_request] (C:\Users\maks0\Desktop\KKuTu\Server\lib\node_modules\express\lib\router\layer.js:95:5) at C:\Users\maks0\Desktop\KKuTu\Server\lib\node_modules\express\lib\router\index.js:281:22 at Function.process_params (C:\Users\maks0\Desktop\KKuTu\Server\lib\node_modules\express\lib\router\index.js:335:12)
이런식으로 오류 가 뜹니다

**Comment by Explorer4563** [comment]
감사합니다

**Comment by Explorer4563** [comment]
> 아이템에 gif설정 옵션과 추가 경험치 설정을 넣고싶은데 옵션에 {} 이 괄호 안에 1개밖에 못넣더군요
> {}를 추가해서 하는방법도 안되고 2개를 동시에 넣어도 안되고 그냥 옵션에 2개이상의 옵션이 있으면
> SyntaxError: Unexpected token { in JSON at position 12 at JSON.parse (<anonymous>) at C:\Users\maks0\Desktop\KKuTu\Server\lib\Web\routes\admin.js:253:28 at Array.forEach (<anonymous>) at C:\Users\maks0\Desktop\KKuTu\Server\lib\Web\routes\admin.js:252:7 at Layer.handle [as handle_request] (C:\Users\maks0\Desktop\KKuTu\Server\lib\node_modules\express\lib\router\layer.js:95:5) at next (C:\Users\maks0\Desktop\KKuTu\Server\lib\node_modules\express\lib\router\route.js:137:13) at Route.dispatch (C:\Users\maks0\Desktop\KKuTu\Server\lib\node_modules\express\lib\router\route.js:112:3) at Layer.handle [as handle_request] (C:\Users\maks0\Desktop\KKuTu\Server\lib\node_modules\express\lib\router\layer.js:95:5) at C:\Users\maks0\Desktop\KKuTu\Server\lib\node_modules\express\lib\router\index.js:281:22 at Function.process_params (C:\Users\maks0\Desktop\KKuTu\Server\lib\node_modules\express\lib\router\index.js:335:12)
> 이런식으로 오류 가 뜹니다
