### ISSUE TITLE
run.bat 에서 오류가 납니다.

### ISSUE THREAD

**Issue by ener25** [JJoriping/KKuTu#464]
환영합니다.
[2019-02-22 21:54:16] &lt;&lt; KKuTu Web >>
[2019-02-22 21:54:16] &lt;&lt; KKuTu Server:8496 >>
TypeError: OAuth2Strategy requires a clientID option at Strategy.OAuth2Strategy (C:\Users\babse\Desktop\code\KKuTu-master\Server\lib\node_modules\passport-oauth2\lib\strategy.js:82:34) at new Strategy (C:\Users\babse\Desktop\code\KKuTu-master\Server\lib\node_modules\passport-facebook\lib\strategy.js:54:18) at glob.then (C:\Users\babse\Desktop\code\KKuTu-master\Server\lib\Web\routes\login.js:75:26) at &lt;anonymous>
[2019-02-22 21:54:17] Error from Redis: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
[2019-02-22 21:54:17] Run with no-redis mode.
[2019-02-22 21:54:17] Master DB is ready.
[2019-02-22 21:54:17] Error from Redis: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379 [2019-02-22 21:54:17] Run with no-redis mode.
[2019-02-22 21:54:17] DB is ready.
[2019-02-22 21:54:17] New web server #1
[2019-02-22 21:54:17] Game server #1 connected
[2019-02-22 21:54:17] Error from Redis: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379 [2019-02-22 21:54:17] Run with no-redis mode.
[2019-02-22 21:54:17] DB is ready.
events.js:182 throw er; // Unhandled 'error' event ^ Error: bind EACCES null:80 at Object._errnoException (util.js:1041:11) at _exceptionWithHostPort (util.js:1064:20) at listenOnMasterHandle (net.js:1402:16) at rr (internal/cluster/child.js:111:12) at Worker.send (internal/cluster/child.js:78:7) at process.onInternalMessage (internal/cluster/utils.js:42:8) at emitTwo (events.js:130:20) at process.emit (events.js:213:7) at emit (internal/child_process.js:774:12) at _combinedTickCallback (internal/process/next_tick.js:141:11)
[2019-02-22 21:54:17] Exit web server #1
Worker 32312 died
W: CLOSED WITH CODE 0

**Comment by lshqqytiger** [comment]
사용하지 않는 로그인 옵션의 자바스크립트 파일에는 끝에 .DIS를 붙여 비활성화하세요. 예) auth_facebook.js.DIS

**Comment by andjsrk** [comment]
redis는 https://github.com/MicrosoftArchive/redis/releases 에서 설치하세요.

**Comment by Preta-Crowz** [comment]
1. 레디스 관련 문제는 무시하셔도 됩니다. 단, 랭킹 등 일부 기능이 비활성화됩니다.
2. 80번 포트가 이미 사용중인 것으로 보입니다. 사용중인 프로세스를 찾아 종료 후 다시 켜주세요.
3. 사용하지 않는 로그인 옵션의 js파일은 앞에 `d_`를 붙이는 등의 방식으로 비활성화해주세요.

**Comment by ener25** [comment]
사용하는 포트를 바꾸는 방법은 없나요?

**Comment by ener25** [comment]
events.js:182 throw er; // Unhandled 'error' event ^ Error: bind EACCES null:80 at Object._errnoException (util.js:1041:11) at _exceptionWithHostPort (util.js:1064:20) at listenOnMasterHandle (net.js:1402:16) at rr (internal/cluster/child.js:111:12) at Worker.send (internal/cluster/child.js:78:7) at process.onInternalMessage (internal/cluster/utils.js:42:8) at emitTwo (events.js:130:20) at process.emit (events.js:213:7) at emit (internal/child_process.js:774:12) at _combinedTickCallback (internal/process/next_tick.js:141:11)
[2019-02-25 16:06:39] Exit web server #1
Worker 14996 died
W: CLOSED WITH CODE 0

해제 후에도 이러네요...

**Comment by Preta-Crowz** [comment]
파일을 수정해야하는데, 위치는 직접 찾으셔야 할 듯 합니다.
그 외에 명령 프롬프트에 `netstat -ano | findstr :80`을 입력하여 사용 중인 프로세스 번호를 확인이 가능하며, 해당 번호의 프로세스를 종료하여 해결 할 수도 있습니다.

**Comment by ener25** [comment]
해당 프로세스 번호로 조회한 결과 System 인 것을 찾아냈는데 이거 어떻게 해야 하나요?
시스템을 종료시킬 수도 없고...

**Comment by Preta-Crowz** [comment]
시스템에서 80을 사용 중일 경우 파일을 수정하여 다른 포트를 사용하는 것 외엔 없습니다.
