### ISSUE TITLE
서버가 자꾸 오류를 뿜으면서 꺼집니다.

### ISSUE THREAD

**Issue by lshqqytiger** [JJoriping/KKuTu#477]
사실 닉네임 변경 기능을 구현하려다가 생긴 일이긴 하지만 이곳 말고는 딱히 도움을 받을 곳이 없어서 결국 여기에 이슈를 올리게 되었습니다.

(생략)
function process(req, accessToken, MainDB, $p, done) {
    $p.token = accessToken;
    $p.sid = req.session.id;

    let now = Date.now();
    $p.sid = req.session.id;
    req.session.admin = GLOBAL.ADMIN.includes($p.id);
    req.session.authType = $p.authType;
    MainDB.session.upsert([ '_id', req.session.id ]).set({
        'profile': $p,
        'createdAt': now
    }).on();
	MainDB.users.findOne([ '_id', $p.id ]).on(($body) => {
	if ($body.nickname) $p.title = $body.nickname;
	req.session.profile = $p;
	MainDB.users.update(['_id', $p.id]).set(['lastLogin', now]).on();
	MainDB.session.upsert(['_id', req.session.id]).set({
		'profile': $p,
		'createdAt': now
	}).on();
		done(null, $p);
	});
}
(생략)

login.js를 이렇게 수정했고 users 테이블에 nickname 컬럼도 추가해 줬습니다. 닉네임 변경도 잘만 됩니다. 그런데 가끔 콘솔에 이런 오류가 뜨면서 서버가 꺼져버립니다.

C:\Users\user\Desktop\Private\KKuTu-master\Server\lib\Web\routes\login.js:41 if ($body.nickname) $p.title = $body.nickname; ^ TypeError: Cannot read property 'nickname' of undefined at MainDB.users.findOne.on (C:\Users\user\Desktop\Private\KKuTu-master\Server\lib\Web\routes\login.js:41:19) at callback (C:\Users\user\Desktop\Private\KKuTu-master\Server\lib\sub\collection.js:316:13) at Result.preCB (C:\Users\user\Desktop\Private\KKuTu-master\Server\lib\sub\collection.js:298:6) at Result.Query.handleReadyForQuery (C:\Users\user\Desktop\Private\KKuTu-master\Server\lib\node_modules\pg\lib\query.js:144:10) at Connection.&lt;anonymous> (C:\Users\user\Desktop\Private\KKuTu-master\Server\lib\node_modules\pg\lib\client.js:180:19) at Connection.emit (events.js:182:13) at Socket.&lt;anonymous> (C:\Users\user\Desktop\Private\KKuTu-master\Server\lib\node_modules\pg\lib\connection.js:133:12) at Socket.emit (events.js:182:13) at addChunk (_stream_readable.js:283:12) at readableAddChunk (_stream_readable.js:264:11)

대체 무슨 문제일까요..대충 읽어보니 nickname을 읽어올 수 없다는거 같은데 분명 컬럼도 만들어 줬고 (타입은 text) 닉네임 변경도 문제없이 되는데...

예전부터 적용해보고 싶었던 기능이었는데 정작 해보니 오류가 뜨니까 힘이 쫙 빠집니다..

**Comment by lshqqytiger** [comment]
해결했습니다. 이슈 닫습니다.
