### ISSUE TITLE
서버 오류에 관하여 질문합니다.

### ISSUE THREAD

**Issue by swoo5571** [JJoriping/KKuTu#483]
App threw an error during load
Error: Cannot find module 'colors'
    at Module._resolveFilename (module.js:485:15)
    at Function.Module._resolveFilename (C:\Users\<사용자 이름>\Desktop\KKuTu-master\Server\node_modules\electron\dist\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\<사용자 이름>\Desktop\KKuTu-master\Server\lib\sub\jjlog.js:21:14)
    at Object.<anonymous> (C:\Users\<사용자 이름>\Desktop\KKuTu-master\Server\lib\sub\jjlog.js:58:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
Pug interceptor registered successfully

이렇게 뜨는데 혹시 해결법 알 수 있을까요
run.bat을 켰는데 저 오류가 뜹니다.

**Comment by Preta-Crowz** [comment]
colors 모듈이 빠졌습니다. 서버 구축을 다시 진행하시거나, 모듈을 추가해주세요.
