### ISSUE TITLE
오류가 뜨면서 게임 서버가 열리지 않습니다.

### ISSUE THREAD

**Issue by lshqqytiger** [JJoriping/KKuTu#502]
[2019-05-24 16:05:32] &lt;&lt; KKuTu Web >>
[2019-05-24 16:05:32] Master DB is ready.
[2019-05-24 16:05:32] &lt;&lt; KKuTu Server:null >>
[2019-05-24 16:05:32] OAuth Strategy naver loaded successfully.
[2019-05-24 16:05:32] OAuth Strategy google loaded successfully.
[2019-05-24 16:05:32] OAuth Strategy kakao loaded successfully.
[2019-05-24 16:05:32] OAuth Strategy discord loaded successfully.
[2019-05-24 16:05:32] OAuth Strategy twitch loaded successfully.
[2019-05-24 16:05:32] OAuth Strategy line loaded successfully.
[2019-05-24 16:05:32] OAuth Strategy instagram loaded successfully.
[2019-05-24 16:05:32] OAuth Strategy spotify loaded successfully.
[2019-05-24 16:05:32] OAuth Strategy youtube loaded successfully.
[2019-05-24 16:05:32] OAuth Strategy github loaded successfully.
[2019-05-24 16:05:32] Game server #1 connected
[2019-05-24 16:05:32] DB is ready.
[2019-05-24 16:05:32] ERROR OCCURRED ON THE MASTER! :8080 [2019-5-24 16:05:32] ERROR: TypeError: Cannot read property 'url' of undefined TypeError: Cannot read property 'url' of undefined at WebSocketServer.&lt;anonymous> (C:\Users\user\Desktop\Private\KKuTu-master\Server\lib\Game\master.js:335:32) at WebSocketServer.emit (events.js:182:13) at handleUpgrade (C:\Users\user\Desktop\Private\KKuTu-master\Server\lib\node_modules\ws\lib\websocket-server.js:90:18) at WebSocketServer.completeUpgrade (C:\Users\user\Desktop\Private\KKuTu-master\Server\lib\node_modules\ws\lib\websocket-server.js:321:5) at WebSocketServer.handleUpgrade (C:\Users\user\Desktop\Private\KKuTu-master\Server\lib\node_modules\ws\lib\websocket-server.js:245:10) at Server.upgrade (C:\Users\user\Desktop\Private\KKuTu-master\Server\lib\node_modules\ws\lib\websocket-server.js:89:16) at Server.emit (events.js:182:13) at onParserExecuteCommon (_http_server.js:535:14) at onParserExecute (_http_server.js:482:3)
[2019-05-24 16:05:32] DB is ready.

뭔가 잘못 건드려서 이렇게 된거 같은데 무슨 문제일까요..

**Comment by andjsrk** [comment]
master.js의 url 부분이 문제가 있는 것 같은데요.

**Comment by lshqqytiger** [comment]
새로 setup하니 해결되었습니다.
