### ISSUE TITLE
이런 오류가 뜹니다...

### ISSUE THREAD

**Issue by yangis1019** [JJoriping/KKuTu#505]
[2019-05-28 06:12:29] &lt;&lt; KKuTu Web >>
[2019-05-28 06:12:29] &lt;&lt; KKuTu Server:8496 >>
TypeError: OAuth2Strategy requires a clientID option at Strategy.OAuth2Strategy (D:\KKUTU\KKuTu-master\Server\lib\node_modules\passport-oauth2\lib\strategy.js:82:34) at new Strategy (D:\KKUTU\KKuTu-master\Server\lib\node_modules\passport-facebook\lib\strategy.js:54:18) at glob.then (D:\KKUTU\KKuTu-master\Server\lib\Web\routes\login.js:75:26)
[2019-05-28 06:12:30] Error from Redis: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
[2019-05-28 06:12:30] Run with no-redis mode.
[2019-05-28 06:12:31] Error from Redis: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
[2019-05-28 06:12:31] Run with no-redis mode.
[2019-05-28 06:12:31] Error when connect to PostgreSQL server: error: ����� "postgres"�� password ������ �����߽��ϴ�
[2019-05-28 06:12:31] Error when connect to PostgreSQL server: error: ����� "postgres"�� password ������ �����߽��ϴ�
[2019-05-28 06:12:31] Game server #1 has an error: Error: connect ECONNREFUSED 127.0.0.2:8080
[2019-05-28 06:12:31] Game server #1 closed: 1006
[2019-05-28 06:12:31] Error from Redis: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379 [2019-05-28 06:12:31] Run with no-redis mode.
[2019-05-28 06:12:31] Error when connect to PostgreSQL server: error: ����� "postgres"�� password ������ �����߽��ϴ�

어떻게 하면 되나요?
로컬호스트에 구축할 예정입니다.

**Comment by lshqqytiger** [comment]
사용하지 않는 auth 파일들을 삭제하시거나 .disabled를 붙여주세요. 그리고 global.json 파일이 존재하는지 (.inc 가 예제 파일), PostgreSQL 비밀번호는 틀리지 않았는지 확인해주세요.

**Comment by 5tarlight** [comment]
auth 인증에 실패해서, Redis가 없어서, PostgreSQL 비밀번호가 일치 하지 않아서 인것 같습니다.
위의 auth 오류와 redis문제는 문제가 되지 않지만 PostgreSQL은 꼭 올바른 정보를 넣어 주셔야 합니다

**Comment by lorlol701** [comment]
#504를 참고해보세요.
