### ISSUE TITLE
서버 실행중 오류가 뜹니다

### ISSUE THREAD

**Issue by kiase** [JJoriping/KKuTu#506]
internal/modules/cjs/loader.js:723 throw err; ^ SyntaxError: D:\KKuTu-master\Server\lib\sub\global.json: Unexpected token S in JS
ON at position 496 at JSON.parse (&lt;anonymous>) at Object.Module._extensions..json (internal/modules/cjs/loader.js:720:27) at Module.load (internal/modules/cjs/loader.js:600:32) at tryModuleLoad (internal/modules/cjs/loader.js:539:12) at Function.Module._load (internal/modules/cjs/loader.js:531:3) at Module.require (internal/modules/cjs/loader.js:637:17) at require (internal/modules/cjs/helpers.js:22:18) at Object.&lt;anonymous> (D:\KKuTu-master\Server\lib\const.js:19:14) at Module._compile (internal/modules/cjs/loader.js:701:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
G: CLOSED WITH CODE 1
internal/modules/cjs/loader.js:723
throw err; ^ SyntaxError: D:\KKuTu-master\Server\lib\sub\global.json: Unexpected token S in JSON at position 496 at JSON.parse (&lt;anonymous>) at Object.Module._extensions..json (internal/modules/cjs/loader.js:720:27) at Module.load (internal/modules/cjs/loader.js:600:32) at tryModuleLoad (internal/modules/cjs/loader.js:539:12) at Function.Module._load (internal/modules/cjs/loader.js:531:3) at Module.require (internal/modules/cjs/loader.js:637:17) at require (internal/modules/cjs/helpers.js:22:18) at Object.&lt;anonymous> (D:\KKuTu-maste
r\Server\lib\Web\db.js:22:15) at Module._compile (internal/modules/cjs/loader.js:701:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
Worker 4356 died
W: CLOSED WITH CODE 0

이것을 해결해야 하는데 어떻게 해야할지 모르겠네요..

**Comment by lshqqytiger** [comment]
global.json에 문법 오류가 있습니다. 확인해주세요.

**Comment by kiase** [comment]
문법 고쳤는데 
[2019-05-30 22:02:42] &lt;&lt; KKuTu Web >>
[2019-05-30 22:02:42] &lt;&lt; KKuTu Server:null >>
TypeError: OAuth2Strategy requires a clientID option at Strategy.OAuth2Strategy (D:\KKuTu-master\Server\lib\node_modules\passport-oauth2\lib\strategy.js:82:34) at new Strategy (D:\KKuTu-master\Server\lib\node_modules\passport-facebook\lib\strategy.js:54:18) at glob.then (D:\KKuTu-master\Server\lib\Web\routes\login.js:75:26)
[2019-05-30 22:02:44] Error from Redis: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
[2019-05-30 22:02:44] Run with no-redis mode.
[2019-05-30 22:02:44] Master DB is ready.
[2019-05-30 22:02:44] Error from Redis: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
[2019-05-30 22:02:44] Run with no-redis mode.
[2019-05-30 22:02:44] DB is ready.
[2019-05-30 22:02:45] New web server #1
[2019-05-30 22:02:45] Game server #1 connected
[2019-05-30 22:02:45] Error from Redis: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379 [2019-05-30 22:02:45] Run with no-redis mode.
[2019-05-30 22:02:45] DB is ready.
이게 나옵니다 이건 어떻게 해야하죠..
