### ISSUE TITLE
구글 로그인시 redirect_uri_mismatch

### ISSUE THREAD

**Issue by hyusan12334** [JJoriping/KKuTu#525]
![11](https://user-images.githubusercontent.com/53594682/62347200-d996a980-b533-11e9-94d6-1240fd30ba0c.png)
![22](https://user-images.githubusercontent.com/53594682/62347212-df8c8a80-b533-11e9-9306-022234097129.png)
![33](https://user-images.githubusercontent.com/53594682/62347218-e4513e80-b533-11e9-9ec2-8c44ee281905.png)

이유 모를 리다이렉트 url 미스매치가 뜹니다
어딜 고쳐야 하나요?

**Comment by lshqqytiger** [comment]
리디렉션 (리다이렉션) URL에 http://hyutu.ml/login/callback/google 을 추가하세요.

**Comment by hyusan12334** [comment]
이젠
InternalOAuthError: failed to fetch user profile
    at C:\Users\Administrator\Desktop\KKuTu-master\KKuTu-master\Server\lib\node_modules\passport-google-oauth2\lib\oauth2.js:92:28
    at passBackControl (C:\Users\Administrator\Desktop\KKuTu-master\KKuTu-master\Server\lib\node_modules\oauth\lib\oauth2.js:132:9)
    at IncomingMessage.<anonymous> (C:\Users\Administrator\Desktop\KKuTu-master\KKuTu-master\Server\lib\node_modules\oauth\lib\oauth2.js:157:7)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
이게뜨네요

**Comment by lorlol701** [comment]
Google + API가 꺼져 있지 않은지 확인해보세요.

**Comment by andjsrk** [comment]
사용자 인증 정보의 OAuth 동의 화면에서 범위에 email과 profile을 추가해보세요.

**Comment by hyusan12334** [comment]
해결했습니다. 감사합니다
