### ISSUE TITLE
맥에서 서버가 열리지 않습니다 (ws부분인것 같은대..)

### ISSUE THREAD

**Issue by yunho0508** [JJoriping/KKuTu#54]
맥에서 끄투 서버를 열려고 하면 게임 서버는 잘 열리지만 왭서버에서는

```
/Users/helloyunho/Downloads/KKuTu-master/Server/lib/node_modules/ws/lib/WebSocket.js:219
    else throw new Error('not opened');
         ^

Error: not opened
    at WebSocket.send (/Users/helloyunho/Downloads/KKuTu-master/Server/lib/node_modules/ws/lib/WebSocket.js:219:16)
    at /Users/helloyunho/Downloads/KKuTu-master/Server/lib/Web/main.js:94:26
    at Array.forEach (native)
    at Timeout._onTimeout (/Users/helloyunho/Downloads/KKuTu-master/Server/lib/Web/main.js:93:15)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
Worker 10980 died
```

이러면서 안열립니다.

리눅스로 가상머신 했을때는 잘 되었지만 가상머신 내에서만 접속이 가능해서 포기했습니다...

**Comment by ryush00** [comment]
루트 권한으로 실행시켜보세요.

**Comment by yunho0508** [comment]
지금까지 루트로 실행했었습니다 ㅠㅠ(sudo)

**Comment by JJoriping** [comment]
웹 서버에서 게임 서버의 상태 등을 확인할 수 있도록 웹 서버가 게임 서버 쪽으로 웹소켓 클라이언트를 물리는데 이 클라이언트가 게임 서버에 연결되지 않은 것 같습니다. 웹 서버가 게임 서버에 접근하는 경우 게임 서버의 로그에서 `New web server #...`과 같은 메시지가 출력되니 참고해 주시고 맥 환경은 제가 다루어 본 적이 없는지라 이 이상은 저도 잘 모르겠습니다.

**Comment by yunho0508** [comment]
gameServers[i] = new GameClient(KEY, `http://127.0.0.2:${v}/${KEY}`);


이부분에서 뭔가 문제가 있는거 같은대 

`if(socket.upgradeReq.headers.host.match(/^127.0.0.2:/)){`

이부분과 윗부분에 127.0.0.2 를 127.0.0.1로 바꾸니 둘다 접속은 했다는대 게임 서버에서는 유저가 들어왔다고 하며

왭서버에서는 
```
/Users/helloyunho/Downloads/KKuTu-master/Server/lib/node_modules/ws/lib/Receiver.js:532
            if (!Validation.isValidUTF8(messageBuffer)) {
                           ^

TypeError: Cannot read property 'isValidUTF8' of undefined
    at /Users/helloyunho/Downloads/KKuTu-master/Server/lib/node_modules/ws/lib/Receiver.js:532:28
    at Receiver.applyExtensions (/Users/helloyunho/Downloads/KKuTu-master/Server/lib/node_modules/ws/lib/Receiver.js:371:5)
    at /Users/helloyunho/Downloads/KKuTu-master/Server/lib/node_modules/ws/lib/Receiver.js:508:14
    at Receiver.flush (/Users/helloyunho/Downloads/KKuTu-master/Server/lib/node_modules/ws/lib/Receiver.js:347:3)
    at Receiver.finish (/Users/helloyunho/Downloads/KKuTu-master/Server/lib/node_modules/ws/lib/Receiver.js:541:12)
    at Receiver.expectHandler (/Users/helloyunho/Downloads/KKuTu-master/Server/lib/node_modules/ws/lib/Receiver.js:499:31)
    at Receiver.add (/Users/helloyunho/Downloads/KKuTu-master/Server/lib/node_modules/ws/lib/Receiver.js:103:24)
    at Socket.realHandler (/Users/helloyunho/Downloads/KKuTu-master/Server/lib/node_modules/ws/lib/WebSocket.js:825:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:189:7)
Worker 6071 died
```

이러면서 또 안되네요..

**Comment by yunho0508** [comment]
한동안 도전 안하다가 다른 부분에서 127.0.0.1로 번경해주니 됬습니다!!

답변해 주신 분들 모두 감사합니다!
