### ISSUE TITLE
ws 3.3.3 관련 Error: read ECONNRESET 오류

### ISSUE THREAD

**Issue by lshqqytiger** [JJoriping/KKuTu#540]
저희 서버는 유저가 접속하고 나갈 때 모두 IP를 로그합니다.

그래서 master.js 중 joinNewUser 함수, 캡챠 인증 부분, KKuTu.onClientClosed 이 세부분에서 $c.socket._socket.remoteAddress를 사용하고 있습니다.

그런데 이번에 ws를 3.3.3 버전으로 업데이트 해주고 이번 커밋 사항 또한 적용 해 주었는데 joinNewUser, 캡챠 인증은 정상입니다만 유저가 접속을 끊을 때, 즉 KKuTu.onClientClosed 부분에서만 오류가 납니다.

어떻게 해야할까요..
(참고로 master.js의 722번째 줄 내용은 var clientIp = $c.socket._socket.remoteAddress; 입니다.)

[2019-08-08 14:45:46] Error on #670ph--7sQDd61pnZKUYWeMf0keedEiV on ws: Error: read ECONNRESET
[2019-08-08 14:45:46] ERROR OCCURRED ON THE MASTER! :8080 [2019-8-8 14:45:46] ERROR: TypeError: Cannot read property 'remoteAddress' of null TypeError: Cannot read property 'remoteAddress' of null at Object.KKuTu.onClientClosed (C:\Users\user\Desktop\Private\KKuTu-master\Server\lib\Game\master.js:722:35) at WebSocket.&lt;anonymous> (C:\Users\user\Desktop\Private\KKuTu-master\Server\lib\Game\kkutu.js:283:11) at WebSocket.emit (events.js:187:15) at WebSocket.emitClose (C:\Users\user\Desktop\Private\KKuTu-master\Server\lib\node_modules\ws\lib\WebSocket.js:211:10) at _receiver.cleanup (C:\Users\user\Desktop\Private\KKuTu-master\Server\lib\node_modules\ws\lib\WebSocket.js:199:39) at Receiver.cleanup (C:\Users\user\Desktop\Private\KKuTu-master\Server\lib\node_modules\ws\lib\Receiver.js:520:15) at WebSocket.finalize (C:\Users\user\Desktop\Private\KKuTu-master\Server\lib\node_modules\ws\lib\WebSocket.js:199:20) at TLSSocket.emit (events.js:182:13) at emitErrorNT (internal/streams/destroy.js:82:8) at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)

**Comment by JJoriping** [comment]
안녕하세요. 해당 모듈 업데이트 후 `_socket` 속성이 숨겨진 것 같아 발생한 것으로 보여, 관련 소스 코드를 수정했습니다. 다시 확인해 보세요.

**Comment by lshqqytiger** [comment]
remoteAddress 오류는 해결되었고 IP도 정상적으로 로그되나, 유저가 접속을 끊을 때 IP가 로그됨과 동시에 다음과 같은 오류가 발생합니다.

[2019-08-08 15:25:41] Error on #tQcxi84L4nv47sR-3VJlKVE1pB4so0KP on ws: Error: read ECONNRESET

**Comment by JJoriping** [comment]
https://github.com/websockets/ws/issues/1256#issuecomment-364988689
확인 결과 해당 문제는 ws 모듈의 이슈로 올라와 있습니다. 클라이언트의 비정상 접속 종료로 인해 생기는 것으로 보이며, 위 링크에서 제시한 대로 해당 오류를 무시해도 되고, ws 모듈을 더 상위 버전으로 업데이트해 오류 자체가 보이지 않게 할 수도 있어 보입니다.

**Comment by JJoriping** [comment]
https://github.com/websockets/ws/issues/1256#issuecomment-364988689
확인 결과 해당 문제는 ws 모듈의 이슈로 올라와 있습니다. 클라이언트의 비정상 접속 종료로 인해 생기는 것으로 보이며, 위 링크에서 제시한 대로 해당 오류를 무시해도 되고, ws 모듈을 더 상위 버전으로 업데이트해 오류 자체가 보이지 않게 할 수도 있을 것 같습니다.

**Comment by lshqqytiger** [comment]
알겠습니다. 답변 감사합니다.
