### ISSUE TITLE
ssl 적용 오류

### ISSUE THREAD

**Issue by spnia** [JJoriping/KKuTu#549]
[2019-08-25 17:58:57] Master DB is ready. [2019-08-25 17:58:57] ERROR OCCURRED ON THE MASTER! :8140 [2019-8-25 5:58:57 PM] ERROR: Error: error:0909006C:PEM routines:get_name:no start line Error: error:0909006C:PEM routines:get_name:no start line at Object.createSecureContext (_tls_common.js:135:17) at Server (_tls_wrap.js:870:27) at new Server (https.js:62:14) at Object.createServer (https.js:85:10) at Object.MainDB.ready (C:\Users\Administrator\Desktop\trtwerfg\KKuTu-master\Server\lib\Game\master.js:279:25) at C:\Users\Administrator\Desktop\trtwerfg\KKuTu-master\Server\lib\Web\db.js:87:30 at BoundPool.&lt;anonymous> (C:\Users\Administrator\Desktop\trtwerfg\KKuTu-master\Server\lib\node_modules\pg-pool\index.js:137:9) at C:\Users\Administrator\Desktop\trtwerfg\KKuTu-master\Server\lib\node_modules\generic-pool\lib\generic-pool.js:347:9 at BoundPool.&lt;anonymous> (C:\Users\Administrator\Desktop\trtwerfg\KKuTu-master\Server\lib\node_modules\pg-pool\index.js:103:7) at Connection.&lt;anonymous> (C:\Users\Administrator\Desktop\trtwerfg\KKuTu-master\Server\lib\node_modules\pg\lib\client.js:166:7)
[2019-08-25 17:58:57] Master DB is ready. [2019-08-25 17:58:57] ERROR OCCURRED ON THE MASTER! :8100 [2019-8-25 5:58:57 PM] ERROR: Error: error:0909006C:PEM routines:get_name:no start line Error: error:0909006C:PEM routines:get_name:no start line at Object.createSecureContext (_tls_common.js:135:17) at Server (_tls_wrap.js:870:27) at new Server (https.js:62:14) at Object.createServer (https.js:85:10) at Object.MainDB.ready (C:\Users\Administrator\Desktop\trtwerfg\KKuTu-master\Server\lib\Game\master.js:279:25) at C:\Users\Administrator\Desktop\trtwerfg\KKuTu-master\Server\lib\Web\db.js:87:30 at BoundPool.&lt;anonymous> (C:\Users\Administrator\Desktop\trtwerfg\KKuTu-master\Server\lib\node_modules\pg-pool\index.js:137:9) at C:\Users\Administrator\Desktop\trtwerfg\KKuTu-master\Server\lib\node_modules\generic-pool\lib\generic-pool.js:347:9 at BoundPool.&lt;anonymous> (C:\Users\Administrator\Desktop\trtwerfg\KKuTu-master\Server\lib\node_modules\pg-pool\index.js:103:7) at Connection.&lt;anonymous> (C:\Users\Administrator\Desktop\trtwerfg\KKuTu-master\Server\lib\node_modules\pg\lib\client.js:166:7)
[2019-08-25 17:58:57] Master DB is ready. [2019-08-25 17:58:57] ERROR OCCURRED ON THE MASTER! :8120 [2019-8-25 5:58:57 PM] ERROR: Error: error:0909006C:PEM routines:get_name:no start line Error: error:0909006C:PEM routines:get_name:no start line at Object.createSecureContext (_tls_common.js:135:17) at Server (_tls_wrap.js:870:27) at new Server (https.js:62:14) at Object.createServer (https.js:85:10) at Object.MainDB.ready (C:\Users\Administrator\Desktop\trtwerfg\KKuTu-master\Server\lib\Game\master.js:279:25) at C:\Users\Administrator\Desktop\trtwerfg\KKuTu-master\Server\lib\Web\db.js:87:30 at BoundPool.&lt;anonymous> (C:\Users\Administrator\Desktop\trtwerfg\KKuTu-master\Server\lib\node_modules\pg-pool\index.js:137:9) at C:\Users\Administrator\Desktop\trtwerfg\KKuTu-master\Server\lib\node_modules\generic-pool\lib\generic-pool.js:347:9 at BoundPool.&lt;anonymous> (C:\Users\Administrator\Desktop\trtwerfg\KKuTu-master\Server\lib\node_modules\pg-pool\index.js:103:7) at Connection.&lt;anonymous> (C:\Users\Administrator\Desktop\trtwerfg\KKuTu-master\Server\lib\node_modules\pg\lib\client.js:166:7)
_tls_common.js:135 c.context.setCert(cert); ^ Error: error:0909006C:PEM routines:get_name:no start line at Object.createSecureContext (_tls_common.js:135:17) at Server (_tls_wrap.js:870:27) at new Server (https.js:62:14) at Object.createServer (https.js:85:10) at Object.&lt;anonymous> (C:\Users\Administrator\Desktop\trtwerfg\KKuTu-master\Server\lib\Game\slave.js:29:23) at Module._compile (internal/modules/cjs/loader.js:776:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10) at Module.load (internal/modules/cjs/loader.js:653:32) at tryModuleLoad (internal/modules/cjs/loader.js:593:12) at Function.Module._load (internal/modules/cjs/loader.js:585:3)
_tls_common.js:135 c.context.setCert(cert); ^ Error: error:0909006C:PEM routines:get_name:no start line at Object.createSecureContext (_tls_common.js:135:17) at Server (_tls_wrap.js:870:27) at new Server (https.js:62:14) at Object.createServer (https.js:85:10) at Object.&lt;anonymous> (C:\Users\Administrator\Desktop\trtwerfg\KKuTu-master\Server\lib\Game\slave.js:29:23) at Module._compile (internal/modules/cjs/loader.js:776:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10) at Module.load (internal/modules/cjs/loader.js:653:32) at tryModuleLoad (internal/modules/cjs/loader.js:593:12) at Function.Module._load (internal/modules/cjs/loader.js:585:3)
[2019-08-25 17:58:57] Worker @1 6468 died
_tls_common.js:135 c.context.setCert(cert); ^ Error: error:0909006C:PEM routines:get_name:no start line at Object.createSecureContext (_tls_common.js:135:17) at Server (_tls_wrap.js:870:27) at new Server (https.js:62:14) at Object.createServer (https.js:85:10) at Object.&lt;anonymous> (C:\Users\Administrator\Desktop\trtwerfg\KKuTu-master\Server\lib\Game\slave.js:29:23) at Module._compile (internal/modules/cjs/loader.js:776:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10) at Module.load (internal/modules/cjs/loader.js:653:32) at tryModuleLoad (internal/modules/cjs/loader.js:593:12) at Function.Module._load (internal/modules/cjs/loader.js:585:3)
[2019-08-25 17:58:57] Worker @1 6580 died
_tls_common.js:135 c.context.setCert(cert); ^ Error: error:0909006C:PEM routines:get_name:no start line at Object.createSecureContext (_tls_common.js:135:17) at Server (_tls_wrap.js:870:27) at new Server (https.js:62:14) at Object.createServer (https.js:85:10) at Object.&lt;anonymous> (C:\Users\Administrator\Desktop\trtwerfg\KKuTu-master\Server\lib\Game\slave.js:29:23) at Module._compile (internal/modules/cjs/loader.js:776:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10) at Module.load (internal/modules/cjs/loader.js:653:32) at tryModuleLoad (internal/modules/cjs/loader.js:593:12) at Function.Module._load (internal/modules/cjs/loader.js:585:3)
[2019-08-25 17:58:57] Game server #1 has an error: Error: connect ECONNREFUSED 127.0.0.2:8080 [2019-08-25 17:58:57] Game server #1 closed: 1006 [2019-08-25 17:58:57] Game server #1 has an error: Error: connect ECONNREFUSED 127.0.0.2:8100 [2019-08-25 17:58:57] Game server #1 closed: 1006 [2019-08-25 17:58:57] Game server #1 has an error: Error: connect ECONNREFUSED 127.0.0.2:8110 [2019-08-25 17:58:57] Game server #1 closed: 1006 [2019-08-25 17:58:57] Game server #1 has an error: Error: connect ECONNREFUSED 127.0.0.2:8140
_tls_common.js:135 c.context.setCert(cert); ^ Error: error:0909006C:PEM routines:get_name:no start line at Object.createSecureContext (_tls_common.js:135:17) at Server (_tls_wrap.js:870:27) at new Server (https.js:62:14) at Object.createServer (https.js:85:10) at Object.&lt;anonymous> (C:\Users\Administrator\Desktop\trtwerfg\KKuTu-master\Server\lib\Game\slave.js:29:23) at Module._compile (internal/modules/cjs/loader.js:776:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10) at Module.load (internal/modules/cjs/loader.js:653:32) at tryModuleLoad (internal/modules/cjs/loader.js:593:12) at Function.Module._load (internal/modules/cjs/loader.js:585:3)
[2019-08-25 17:58:57] Worker @1 1560 died
[2019-08-25 17:58:57] Game server #1 closed: 1006 [2019-08-25 17:58:57] Game server #1 has an error: Error: connect ECONNREFUSED 127.0.0.2:8120 [2019-08-25 17:58:57] Game server #1 closed: 1006 [2019-08-25 17:58:57] Game server #1 has an error: Error: connect ECONNREFUSED 127.0.0.2:8090 [2019-08-25 17:58:57] Game server #1 closed: 1006 [2019-08-25 17:58:57] Game server #1 has an error: Error: connect ECONNREFUSED 127.0.0.2:8130 [2019-08-25 17:58:57] Game server #1 closed: 1006 [2019-08-25 17:58:57] Error from Redis: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379 [2019-08-25 17:58:57] Run with no-redis mode.
[2019-08-25 17:58:57] Worker @1 6672 died
[2019-08-25 17:58:57] Worker @1 2040 died
_tls_common.js:135 c.context.setCert(cert); ^ Error: error:0909006C:PEM routines:get_name:no start line at Object.createSecureContext (_tls_common.js:135:17) at Server (_tls_wrap.js:870:27) at new Server (https.js:62:14) at Object.createServer (https.js:85:10) at Object.&lt;anonymous> (C:\Users\Administrator\Desktop\trtwerfg\KKuTu-master\Server\lib\Game\slave.js:29:23) at Module._compile (internal/modules/cjs/loader.js:776:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10) at Module.load (internal/modules/cjs/loader.js:653:32) at tryModuleLoad (internal/modules/cjs/loader.js:593:12) at Function.Module._load (internal/modules/cjs/loader.js:585:3)
[2019-08-25 17:58:57] Worker @1 7304 died

위와 같은 오류가 반복해서 발생합니다
이슈를 둘러보니 secure.js, slave.js도 수정해야 한다고 해서
secure.js에선 options.key, options.cert, options.ca 에 각각 인증서 경로를 넣어봤고
slave.js에선 const options = Secure();를 const options = secure();로 변경했습니다.
어디서 문제가 발생한건가요?

**Comment by spnia** [comment]
요약
_tls_common.js:135 c.context.setCert(cert); ^ Error: error:0909006C:PEM routines:get_name:no start line at Object.createSecureContext (_tls_common.js:135:17) at Server (_tls_wrap.js:870:27) at new Server (https.js:62:14) at Object.createServer (https.js:85:10) at Object.&lt;anonymous> (C:\Users\Administrator\Desktop\trtwerfg\KKuTu-master\Server\lib\Game\slave.js:29:23) at Module._compile (internal/modules/cjs/loader.js:776:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10) at Module.load (internal/modules/cjs/loader.js:653:32) at tryModuleLoad (internal/modules/cjs/loader.js:593:12) at Function.Module._load (internal/modules/cjs/loader.js:585:3)

**Comment by lshqqytiger** [comment]
cert가 잘못되었습니다.

**Comment by spnia** [comment]
어떤걸 넣어봐도 안됩니다

**Comment by spnia** [comment]
~-pem 파일을 넣었더니 해결되었습니다.
