### ISSUE TITLE
저좀 도와주세요

### ISSUE THREAD

**Issue by Muzihuzi** [JJoriping/KKuTu#560]
이 에러는 무엇인가요

[2019-09-21 19:13:20] &lt;&lt; KKuTu Web >>
[2019-09-21 19:13:20] &lt;&lt; KKuTu Server:8496 >>
[2019-09-21 19:13:20] OAuth Strategy naver is not loaded
[2019-09-21 19:13:20] OAuth2Strategy requires a clientID option
[2019-09-21 19:13:20] OAuth Strategy facebook is not loaded [2019-09-21 19:13:20] OAuth2Strategy requires a clientID option
[2019-09-21 19:13:20] OAuth Strategy google is not loaded [2019-09-21 19:13:20] OAuth2Strategy requires a clientID option
[2019-09-21 19:13:20] OAuth Strategy twitter is not loaded [2019-09-21 19:13:20] OAuthStrategy requires a consumerKey option
[2019-09-21 19:13:20] OAuth Strategy kakao is not loaded [2019-09-21 19:13:20] OAuth2Strategy requires a clientID option
[2019-09-21 19:13:20] OAuth Strategy discord is not loaded
[2019-09-21 19:13:20] Cannot find module 'passport-discord'
[2019-09-21 19:13:20] OAuth Strategy twitch is not loaded
[2019-09-21 19:13:20] Cannot find module 'passport-twitch'
[2019-09-21 19:13:20] OAuth Strategy github is not loaded [2019-09-21 19:13:20] Cannot find module 'passport-github'
[2019-09-21 19:13:20] OAuth Strategy line is not loaded [2019-09-21 19:13:20] Cannot find module 'passport-line'
[2019-09-21 19:13:20] OAuth Strategy instagram is not loaded [2019-09-21 19:13:20] Cannot find module 'passport-instagram'
[2019-09-21 19:13:20] OAuth Strategy spotify is not loaded [2019-09-21 19:13:20] Cannot find module 'passport-spotify'
[2019-09-21 19:13:21] Error from Redis: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379 [2019-09-21 19:13:21] Run with no-redis mode.
[2019-09-21 19:13:21] Master DB is ready.
[2019-09-21 19:13:21] Error from Redis: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379 [2019-09-21 19:13:21] Run with no-redis mode.
[2019-09-21 19:13:21] DB is ready.
[2019-09-21 19:13:21] Error from Redis: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
[2019-09-21 19:13:21] Run with no-redis mode.
[2019-09-21 19:13:21] New web server #1
[2019-09-21 19:13:21] Game server #1 connected
[2019-09-21 19:13:21] DB is ready.
events.js:174 throw er; // Unhandled 'error' event ^ Error
: bind EACCES null:80 at listenOnMasterHandle (net.js:1346:16) at rr (internal/cluster/child.js:126:12) at Worker.send (internal/cluster/child.js:93:7) at process.onInternalMessage (internal/cluster/utils.js:45:8) at process.emit (events.js:203:15) at emit (internal/child_process.js:832:12) at process._tickCallback (internal/proc
ess/next_tick.js:63:19) Emitted 'error' event at: at listenOnMasterHandle (net.js:1347:21) at rr (internal/cluster/child.js:126:12) [... lines matching original stack trace ...] at process._tickCallback (i
nternal/process/next_tick.js:63:19)
[2019-09-21 19:13:21] Exit web server #1
Worker 22804 died
W: CLOSED WITH CODE 0

**Comment by hatty163** [comment]
저 에러 코드 인터넷에 조금만 쳐보시면 나올텐데요..
포트 80이 다른 서비스 (IIS, Nginx, Apache, etc.) 등에 의해 사용 중입니다. 프로세스를 닫고 다시 시도하세요.

**Comment by Muzihuzi** [comment]
p{margin-top:0;margin-bottom:0}
    


    감사합니다
--------- 원본 메일 ---------

    
        보낸사람: 해티 <notifications@github.com>
        받는사람: JJoriping/KKuTu <KKuTu@noreply.github.com>
        
            참조: Muzihuzi <park20050620@daum.net>, Author <author@noreply.github.com>
        
        날짜: 19.09.21 21:30 GMT +0900
        제목: Re: [JJoriping/KKuTu] 저좀 도와주세요 (#560)
        
        
    
    
        저 에러 코드 인터넷에 조금만 쳐보시면 나올텐데요..

포트 80이 다른 서비스 (IIS, Nginx, Apache, etc.) 등에 의해 사용 중입니다. 프로세스를 닫고 다시 시도하세요.

**Comment by Muzihuzi** [comment]
> 저 에러 코드 인터넷에 조금만 쳐보시면 나올텐데요..
> 포트 80이 다른 서비스 (IIS, Nginx, Apache, etc.) 등에 의해 사용 중입니다. 프로세스를 닫고 다시 시도하세요.

포트 80번 사용자를 강제종료 할수 없는데. 파일을 수정해서 포트를 다른것으로 바꾸려 하는데 어느파인지 찾다가 포기했네요 좀 알려주실수 있나요?

**Comment by lshqqytiger** [comment]
제 경우에는 IIS가 80을 사용하고 있었습니다. IIS가 켜진 것은 아닌지 확인해보세요.
