### ISSUE TITLE
오류! 제발 도와주세요!

### ISSUE THREAD

**Issue by junykkutu** [JJoriping/KKuTu#573]
저는 kkutu.js 건들고 나서는 잘됬는데 갑자기 kkutu.js도 에러났네요...
그리고 l머시기.js 이건 건들기 조차도 하지 않았습니다....
이러면서 서버가 갑자기 안열리네요. 에러 내용 입니다
D:D\K:\KKuTu\KKKuTu\KKuTu-masuTu-matesterr\S\Sererver\lib\verGam\lib\Game\kkutu.jes:316\ @@ -1041,6 +105
D:\KKuTu\KKuTu-master\Server\lib\Game\kkutu.js:316 @@ -1041,6 +1050,9 @@ exports.Room = function(room, channel){ ^ SyntaxError: Invalid or unexpected token at Module._compile (internal/modules/cjs/loader.js:720:23) at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10) at Module.load (internal/modules/cjs/loader.js:643:32) at Function.Module._load (internal/modules/cjs/loader.js:556:12) at Module.require (internal/modules/cjs/loader.js:683:19) at require (internal/modules/cjs/helpers.js:16:16) at Object.&lt;anonymous> (D:\KKuTu\KKuTu-master\Server\lib\Game\master.js:25:13) D:\KKuTu\KKuTu-master\Server\lib\Game\kkutu.js:316 @@ -1041,6 +1050,9 @@ exports.Room = function(room, channel){ ^ SyntaxError: Invalid or unexpected token at Module._compile (int at Module._compile (internaelr/modules/cjsn/loaader.jls:776:30) /module at Objsect.Module._exte/nsions..js (cjs/loader.js:720:23) at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10) at Modulinternal/moe.load (intedules/cjs/loader.js:787rnal/modules/cjs/loader.js::10) at Module.load (internal/modules643:32) / at Funcction.Modulejs/l._load (internal/modules/cjs/loader.js:556:12) at Module.require (internal/moduoader.js:6
0,9 @@ exkkutu.js:316 @@ports.Room = function(roo m,-1041,6 channel){ ^ SyntaxError: Inv+al1050,9 @id@ oexports.Room = function(r rounom, channel)ex{ ^ SyntpeaxErrctor: edIn tvaoken at liModule.d _corom unexppile (intected token at Module._compile (internal/modules/cjs/loader.js:720:23) at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10) at Module.load (internal/modulesern/al/modules/cjs/loader.js:720:23) at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10) at Modulce.load (internal/moduljes/cjss/loader/loa.js:643:32d) ater.js Fu:643:32) nctio at Fn.Moduunction.Module._load (internal/modules/cjs/loader.js:556:1l2e.) _lo ad (internal/modu at Module.lerequire (ins/cjs/lternal/modules/cjs/oaloader.jder.js:556:12) at Module.requirs:683:19) ae (internal/t mreoqudules/ire (intecrnajs/loader.js:683:19)l/modules/cjs/he lp er s.js:a16:16t requir) e (inter at Objectnal/modules/cjs/hel.&lt;anonpyemours> s.(Djs::\KKu16:Tu\1KK6)uT u- ma ster\Server\lib\Gaatme O\mastebjer.cjs:25:1t.&lt;3anonymous> (D:\KKuTu\KKuTu-master\Server\lib\Game\master.js:25:13) at Module._compile (internal/modules/cjs/lo) ader.js:776:30) at Mod ule._com at Object.Module._extensions..js (internal/modules/cjs/loaderpi.le (internal/modules/cjs/loader.js:776:30) js:7 at Obj87:10) at Module.load (inecternal/modules/cjst./Module._loaderextensions..js (internal/modules/cjs/loader.js:787:10) at Module.load (internal/modules/cjs/loader.js:643:32) .js:643:32)
43les/cjs/load:er.js:683:19) at require (internal/modules/cjs/helpers.js:16:16) at Object.&lt;anonymous> 32) (D:\KKuTu\KKuTu-master\Server\lib\Game\master.js:25:13) at Module._compile (internal/modules/cjs/loader.js:776:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10) at Module.load (internal/modules/cjs/loader.js:643:32)
G: CLOSED WITH CODE 1
G: CLOSED WITH CODE 1
[2019-10-13 06:40:55] &lt;&lt; KKuTu Web >>
[2019-10-13 06:40:59] OAuth Strategy naver is not loaded [2019-10-13 06:40:59] OAuth2Strategy requires a clientID option
[2019-10-13 06:40:59] OAuth Strategy facebook is not loaded [2019-10-13 06:40:59] OAuth2Strategy requires a clientID option
[2019-10-13 06:40:59] OAuth Strategy google loaded successfully.
[2019-10-13 06:40:59] OAuth Strategy twitter is not loaded [2019-10-13 06:40:59] OAuthStrategy requires a consumerKey option
[2019-10-13 06:40:59] OAuth Strategy kakao loaded successfully.
[2019-10-13 06:40:59] OAuth Strategy discord is not loaded [2019-10-13 06:40:59] Cannot find module 'passport-discord' Require stack: - D:\KKuTu\KKuTu-master\Server\lib\Web\auth\auth_discord.js - D:\KKuTu\KKuTu-master\Server\lib\Web\routes\login.js - D:\KKuTu\KKuTu-master\Server\lib\Web\main.js - D:\KKuTu\KKuTu-master\Server\lib\Web\cluster.js
[2019-10-13 06:40:59] OAuth Strategy twitch is not loaded [2019-10-13 06:40:59] Cannot find module 'passport-twitch' Require stack: - D:\KKuTu\KKuTu-master\Server\lib\Web\auth\auth_twitch.js - D:\KKuTu\KKuTu-master\Server\lib\Web\routes\login.js - D:\KKuTu\KKuTu-master\Server\lib\Web\main.js - D:\KKuTu\KKuTu-master\Server\lib\Web\cluster.js
[2019-10-13 06:40:59] OAuth Strategy github is not loaded [2019-10-13 06:40:59] Cannot find module 'passport-github' Require stack: - D:\KKuTu\KKuTu-master\Server\lib\Web\auth\auth_github.js - D:\KKuTu\KKuTu-master\Server\lib\Web\routes\login.js - D:\KKuTu\KKuTu-master\Server\lib\Web\main.js - D:\KKuTu\KKuTu-master\Server\lib\Web\cluster.js
[2019-10-13 06:40:59] OAuth Strategy line is not loaded [2019-10-13 06:40:59] Cannot find module 'passport-line' Require stack: - D:\KKuTu\KKuTu-master\Server\lib\Web\auth\auth_line.js - D:\KKuTu\KKuTu-master\Server\lib\Web\routes\login.js - D:\KKuTu\KKuTu-master\Server\lib\Web\main.js - D:\KKuTu\KKuTu-master\Server\lib\Web\cluster.js
[2019-10-13 06:40:59] OAuth Strategy instagram is not loaded [2019-10-13 06:40:59] Cannot find module 'passport-instagram' Require stack: - D:\KKuTu\KKuTu-master\Server\lib\Web\auth\auth_instagram.js - D:\KKuTu\KKuTu-master\Server\lib\Web\routes\login.js - D:\KKuTu\KKuTu-master\Server\lib\Web\main.js - D:\KKuTu\KKuTu-master\Server\lib\Web\cluster.js
[2019-10-13 06:40:59] OAuth Strategy spotify is not loaded [2019-10-13 06:40:59] Cannot find module 'passport-spotify' Require stack: - D:\KKuTu\KKuTu-master\Server\lib\Web\auth\auth_spotify.js - D:\KKuTu\KKuTu-master\Server\lib\Web\routes\login.js - D:\KKuTu\KKuTu-master\Server\lib\Web\main.js - D:\KKuTu\KKuTu-master\Server\lib\Web\cluster.js
[2019-10-13 06:41:00] Game server #1 has an error: Error: connect ECONNREFUSED 127.0.0.2:8090 [2019-10-13 06:41:00] Game server #1 closed: 1006
[2019-10-13 06:41:00] Error from Redis: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379 [2019-10-13 06:41:00] Run with no-redis mode.
[2019-10-13 06:41:00] DB is ready.

**Comment by L4by** [comment]
끄투 서버를 무슨 마인크래프트 서버 쯤으로 생각하시는 것 같은데 Node.js에 대한 기본적인 지식조차 없으면 서버를 열래야 열 수가 없습니다. 뭘 건드리셨는지 정도는 알려주셔야 답변을 하던가 말던가 하지 이건 뭐..

**Comment by lshqqytiger** [comment]
정확히 **어떤 파일**을 **어떻게** 수정하신건지 알려주셔야 도움을 드릴 수 있습니다.

**Comment by andjsrk** [comment]
1  레디스를 설치해주세요.
2. 로그인 방식에 맞는 passport-(로그인 방식) 모듈을 설치해주세요
3. 그리고 제가 보기에만 맨 위엣줄 경로가 이상한가요
경로 문제일 수도 잇을 것 같네요
