### ISSUE TITLE
IJP_EXCEPT 관련 에러

### ISSUE THREAD

**Issue by trustypeople** [JJoriping/KKuTu#61]
TypeError: exports.IJP_EXCEPT.includes is not a function
    at /kkutu/kkutu-web/const.js:226:112
    at Array.filter (native)
    at Object.<anonymous> (/kkutu/kkutu-web/const.js:226:62)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/kkutu/kkutu-web/main.js:32:14)

에러가 발생합니다. 확인 부탁드립니다.

참고로 https://github.com/trustypeople/kkutu-web

와 같이 웹서버와 게임서버를 분리해놓은 상태입니다.

**Comment by trustypeople** [comment]
/kkutu/const.js:226
exports.KO_IJP = exports.KO_INJEONG.concat(exports.KO_THEME).filter(function(item){ return !exports.IJP_EXCEPT.includes(item); });
                                                                                                               ^

TypeError: exports.IJP_EXCEPT.includes is not a function
    at /kkutu/const.js:226:112
    at Array.filter (native)
    at Object.<anonymous> (/kkutu/const.js:226:62)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/kkutu/Web/main.js:32:14)

끄투의 /Server/lib/ 안의 내용물만 올려서 해도 같은 결과가 나옵니다. 확인 부탁드립니다.

**Comment by trustypeople** [comment]
원인 파악했습니다. Node.js 가 V4.? 로 설치되어 나타난 문제로, V6.10.0 으로 설치하여 해결하였습니다.
