### ISSUE TITLE
로그인 안하고 게임시작을 누를시 아무 반응이 없습니다.

### ISSUE THREAD

**Issue by hadocter** [JJoriping/KKuTu#627]
메인화면까지 띄우는건 성공했습니다..만 게임시작 버튼에 마우스를 가져다 대면 반응은 있지만 게임서버로의 이동이나 다른 반응은 오지 않습니다.
로그인의 문제인가 싶어 구글 oauth를 추가해 로그인버튼을 눌러 로그인을 하니 이런 에러가 뜹니다.
게스트로만이라도 되면 좋겠네요... 감사합니다.
혹시 제 질문이 규정에 어긋나면 삭제하겠습니다
환경은 ubuntu server 18.04.3에 intel core2 duo 입니다. 공유기 설정은 포트포워딩 말고 Twin IP(지정된 MAC의 pc가 공인 ip 를 사용하게 합니다) 로 사용하였습니다.
```
InternalOAuthError: failed to fetch user profile
    at /home/hacw/KKuTu/Server/lib/node_modules/passport-google-oauth2/lib/oauth2.js:92:28
    at passBackControl (/home/hacw/KKuTu/Server/lib/node_modules/oauth/lib/oauth2.js:132:9)
    at IncomingMessage.<anonymous> (/home/hacw/KKuTu/Server/lib/node_modules/oauth/lib/oauth2.js:157:7)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```
https://github.com/JJoriping/KKuTu/pull/598 이곳에 나와있는 해결방안은 다 시도 해 보았습니다.

**Comment by lshqqytiger** [comment]
`http://도메인/?server=0`으로는 접속이 되던가요? 된다면 #617 과 동일한 증상입니다.

**Comment by andjsrk** [comment]
메인화면은 일반적으로 https://github.com/JJoriping/KKuTu/issues/617 과 같은 증상입니다.
로그인쪽은 https://github.com/JJoriping/KKuTu/pull/598 쪽을 보고 해결해주세요.

**Comment by hadocter** [comment]
server을 실행 하였을떄 나오는 코드입니다.
```
root@hacw:/home/hacw/KKuTu/Server# node lib/Game/cluster.js 0 1
[2020-02-03 01:16:06] Master DB is ready.
[2020-02-03 01:16:06] << KKuTu Server:8496 >>
[2020-02-03 01:16:06] DB is ready.
[2020-02-03 01:16:24] New user #guest__1
[2020-02-03 01:16:28] Chan @0 Msg #guest__1: {"type":"seek"}
```
이후에는
`[2020-02-03 01:16:28] Chan @0 Msg #guest__1: {"type":"seek"}`
이 계속 뜹니다.

웹서버를 실행하면 이런식으로 뜹니다.
```
root@hacw:/home/hacw/KKuTu/Server# node lib/Web/cluster.js 1
[2020-02-03 01:16:24] << KKuTu Web >>
[2020-02-03 01:16:24] OAuth Strategy naver is not loaded
[2020-02-03 01:16:24] OAuth2Strategy requires a clientID option
[2020-02-03 01:16:24] OAuth Strategy facebook is not loaded
[2020-02-03 01:16:24] OAuth2Strategy requires a clientID option
[2020-02-03 01:16:24] OAuth Strategy google loaded successfully.
[2020-02-03 01:16:24] OAuth Strategy twitter is not loaded
[2020-02-03 01:16:24] OAuthStrategy requires a consumerKey option
[2020-02-03 01:16:24] OAuth Strategy kakao is not loaded
[2020-02-03 01:16:24] OAuth2Strategy requires a clientID option
[2020-02-03 01:16:24] OAuth Strategy discord is not loaded
[2020-02-03 01:16:24] OAuth2Strategy requires a clientID option
[2020-02-03 01:16:24] OAuth Strategy twitch is not loaded
[2020-02-03 01:16:24] OAuth2Strategy requires a clientID option
[2020-02-03 01:16:24] OAuth Strategy github is not loaded
[2020-02-03 01:16:24] OAuth2Strategy requires a clientID option
[2020-02-03 01:16:24] OAuth Strategy line is not loaded
[2020-02-03 01:16:24] OAuth2Strategy requires a clientID option
[2020-02-03 01:16:24] OAuth Strategy instagram is not loaded
[2020-02-03 01:16:24] OAuth2Strategy requires a clientID option
[2020-02-03 01:16:24] OAuth Strategy spotify is not loaded
[2020-02-03 01:16:24] OAuth2Strategy requires a clientID option
[2020-02-03 01:16:24] Game server #1 connected
[2020-02-03 01:16:24] DB is ready.
[2020-02-03 01:21:51] 117.110.115.38@_D9-zRpl6b kkutu, {}
```

http://ggutu.kro.kr/?server=0 으로 접속은 되지만 로딩이 되다가 '불러오는중... 앞으로 1'에서 멈춥니다.

혹시나싶어 우분투 측의 방화벽은 끈 상태로 Advanced Port Scanner 을 이용해 외부 측에서 포트스캔을 돌려보니 실행되있는 서비스는 이러했습니다.
HTTP : [undefined] 글자로 놀자! 끄투 온라인 (Node.js Express middleware)
port 22(TCP):OpenSSH 7.6p1 Ubuntu 4ubuntu0.3 Ubuntu Linux; protocol 2.0
port 80(TCP):Node.js Express middleware
port 8496(TCP):Ogar agar.io server

혹시나 싶어 ggutu.kro.kr:8496으로 접속해보니 upgrade required 라고만 뜹니다.
갑사합니다.

**Comment by lshqqytiger** [comment]
`[2020-02-03 01:16:24] OAuth Strategy naver is not loaded
[2020-02-03 01:16:24] OAuth2Strategy requires a clientID option
[2020-02-03 01:16:24] OAuth Strategy facebook is not loaded
[2020-02-03 01:16:24] OAuth2Strategy requires a clientID option
[2020-02-03 01:16:24] OAuth Strategy google loaded successfully.
[2020-02-03 01:16:24] OAuth Strategy twitter is not loaded
[2020-02-03 01:16:24] OAuthStrategy requires a consumerKey option
[2020-02-03 01:16:24] OAuth Strategy kakao is not loaded
[2020-02-03 01:16:24] OAuth2Strategy requires a clientID option
[2020-02-03 01:16:24] OAuth Strategy discord is not loaded
[2020-02-03 01:16:24] OAuth2Strategy requires a clientID option
[2020-02-03 01:16:24] OAuth Strategy twitch is not loaded
[2020-02-03 01:16:24] OAuth2Strategy requires a clientID option
[2020-02-03 01:16:24] OAuth Strategy github is not loaded
[2020-02-03 01:16:24] OAuth2Strategy requires a clientID option
[2020-02-03 01:16:24] OAuth Strategy line is not loaded
[2020-02-03 01:16:24] OAuth2Strategy requires a clientID option
[2020-02-03 01:16:24] OAuth Strategy instagram is not loaded
[2020-02-03 01:16:24] OAuth2Strategy requires a clientID option
[2020-02-03 01:16:24] OAuth Strategy spotify is not loaded
[2020-02-03 01:16:24] OAuth2Strategy requires a clientID option`

이 로그들은 `auth.json`에 clientID와 clientSecret을 입력하지 않아서 발생하는 로그이고, `auth.json`에 clientID와 clientSecret을 입력해주시거나 `auth_[strategy type].js` 파일을 삭제하시거나 확장자를 바꾸어 인식할 수 없도록 해주시기 바랍니다.

**Comment by andjsrk** [comment]
https://github.com/JJoriping/KKuTu/wiki/%ED%81%B4%EB%9F%AC%EC%8A%A4%ED%84%B0%EB%A7%81#%ED%8F%AC%ED%8A%B8-%EB%B2%88%ED%98%B8
여기를 참고해주세요.

**Comment by hadocter** [comment]
감사합니다 클러스터링에서 redis 항목 주석을 푸니 되는것 같네요
아직 메인에서 접속은 안되지만 /?server=0을 붙일경우 접속이 가능하기에 일단 그렇게 쓰기로 했습니다!! 학교에선 끄투가 막혀서 급하거든요 ㅋㅋ
