### ISSUE TITLE
우분투 환경 80포트 에러

### ISSUE THREAD

**Issue by tjtdkr** [JJoriping/KKuTu#630]
node lib/Web/cluster.js 1
[2020-02-05 14:17:57] << KKuTu Web >>
[2020-02-05 14:17:58] OAuth Strategy naver is not loaded
[2020-02-05 14:17:58] OAuth2Strategy requires a clientID option
[2020-02-05 14:17:58] OAuth Strategy facebook is not loaded
[2020-02-05 14:17:58] OAuth2Strategy requires a clientID option
[2020-02-05 14:17:58] OAuth Strategy google is not loaded
[2020-02-05 14:17:58] OAuth2Strategy requires a clientID option
[2020-02-05 14:17:58] OAuth Strategy twitter is not loaded
[2020-02-05 14:17:58] OAuthStrategy requires a consumerKey option
[2020-02-05 14:17:58] OAuth Strategy kakao is not loaded
[2020-02-05 14:17:58] OAuth2Strategy requires a clientID option
[2020-02-05 14:17:58] OAuth Strategy discord is not loaded
[2020-02-05 14:17:58] OAuth2Strategy requires a clientID option
[2020-02-05 14:17:58] OAuth Strategy twitch is not loaded
[2020-02-05 14:17:58] OAuth2Strategy requires a clientID option
[2020-02-05 14:17:58] OAuth Strategy github is not loaded
[2020-02-05 14:17:58] OAuth2Strategy requires a clientID option
[2020-02-05 14:17:58] OAuth Strategy line is not loaded
[2020-02-05 14:17:58] OAuth2Strategy requires a clientID option
[2020-02-05 14:17:58] OAuth Strategy instagram is not loaded
[2020-02-05 14:17:58] OAuth2Strategy requires a clientID option
[2020-02-05 14:17:58] OAuth Strategy spotify is not loaded
[2020-02-05 14:17:58] OAuth2Strategy requires a clientID option
[2020-02-05 14:17:58] Error from Redis: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
[2020-02-05 14:17:58] Run with no-redis mode.
[2020-02-05 14:17:58] Game server #1 connected
[2020-02-05 14:17:58] DB is ready.
events.js:200
      throw er; // Unhandled 'error' event
      ^

Error: bind EACCES null:80
    at listenOnMasterHandle (net.js:1373:18)
    at rr (internal/cluster/child.js:129:12)
    at Worker.<anonymous> (internal/cluster/child.js:96:7)
    at process.onInternalMessage (internal/cluster/utils.js:43:8)
    at process.emit (events.js:228:7)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
Emitted 'error' event on Server instance at:
    at listenOnMasterHandle (net.js:1374:21)
    at rr (internal/cluster/child.js:129:12)
    [... lines matching original stack trace ...]
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: 'EACCES',
  code: 'EACCES',
  syscall: 'bind',
  address: null,
  port: 80
}
Worker 1909 died

라는 로그와 함께 실행이 되지 않는데 재부팅 직후 서버를 구동하여 포트를 잡아먹을게 없는 상황에서도 이런 에러가 출력됩니다. 혹시 포트를 변경할 수 있을까요?

**Comment by andjsrk** [comment]
[이 부분](https://github.com/JJoriping/KKuTu/blob/master/Server/lib/Web/main.js#L148)을 수정하시면 될 듯합니다.

**Comment by tjtdkr** [comment]
> 포트를 변경하시려면 [이 부분](https://github.com/JJoriping/KKuTu/blob/master/Server/lib/Web/main.js#L148)을 수정하시면 될 듯합니다.
------------------------------------------------------

포트를 변경해서 될 줄 알았는데 이번엔 
  errno: 'EADDRINUSE',
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 8080
이런 에러가 뜹니다.. 어떻게 해야 할까요?

**Comment by lshqqytiger** [comment]
8080 포트가 이미 사용중이라는 것입니다.
Node.js 서버가 정상적으로 종료되지 않았거나, 다른 프로그램에서 사용하는 것입니다.
