### ISSUE TITLE
서버 접속이 안됨

### ISSUE THREAD

**Issue by sjkim04** [JJoriping/KKuTu#642]
서버 열고 127.0.0.1 들어가면 연결 거부 페이지가 떠요....

[2020-02-18 20:32:01] &lt;&lt; KKuTu Web >>
[2020-02-18 20:32:01] &lt;&lt; KKuTu Server:8496 >>
[2020-02-18 20:32:01] Error from Redis: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
[2020-02-18 20:32:01] Run with no-redis mode.
internal/modules/cjs/loader.js:638 throw err; ^
Error: Cannot find module '../../sub/auth.json' at Function.Module._resolveFilename (internal/modules/cjs/loader.
js:6
36:15) at Function.Module._load (internal/modules/cjs/loader.js:562:25) at Module.require (internal/modules/cjs/loader.js:692:17) at require (internal/modules/cjs/helpers.js:25:18) at
Obj
e
ct.&lt;anonymous> (C:\Users\sung
n_00
0\Downloads\KKuTu-master\Serve
r\li
b\Web\routes\logi
n.js:25:16) at Module._compile (internal/modules/cjs/l
oader.js:778:30) at Ob
ject.Module._extensions..js (inte
rnal/modules/cjs/loader.js:789:10) at Module.load (internal/mod
ules/cjs/loader.js:653:
32) at tryModuleLoad (internal/modules/cjs/loader.js:593:12) at Function.Modul
e._load (internal/modules/cjs/loader.js:585:3)
Worker 10604 died
W: CLOSED WITH CODE 0
[2020-02-18 20:32:02] Master DB is ready.
[2020-02-18 20:32:02] Error from Redis: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
[2020-02-18 20:32:02] Run with no-redis mode.
[2020-02-18 20:32:02] DB is ready.
끄투 매니저 콘솔에선 이렇게 떠요...
어떻게 하면 될까요?

**Comment by lshqqytiger** [comment]
README 좀 읽어주세요
`폴더 ./Server/lib/sub에 oAuth 설정 파일(auth.json)과 전역 설정 파일(global.json)을 반드시 만들어 주세요. 본 레포지토리에는 각 파일의 양식이 들어가 있습니다.`

`랭킹 및 세션 기능 일부는 Redis 서버가 실행되어야만 작동합니다. 일단 이를 설치하지 않아도 서버가 작동할 수 있도록 조치했습니다.`

**Comment by sjkim04** [comment]
죄송합니다.... 해결됬어여
