### ISSUE TITLE
카카오 로그인이 안 됩니다ㅠ

### ISSUE THREAD

**Issue by Maple-kkutu** [JJoriping/KKuTu#645]
InternalOAuthError: failed to fetch user profile
    at C:\Users\user\Desktop\KKuTu\Server\lib\node_modules\passport-kakao\lib\strategy.js:58:28
    at passBackControl (C:\Users\user\Desktop\KKuTu\Server\lib\node_modules\oauth\lib\oauth2.js:132:9)
    at IncomingMessage.<anonymous> (C:\Users\user\Desktop\KKuTu\Server\lib\node_modules\oauth\lib\oauth2.js:157:7)
    at IncomingMessage.emit (events.js:228:7)
    at endReadableNT (_stream_readable.js:1185:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21) 이런게 뜹니다ㅠㅠ

**Comment by Jimmy607-2020** [comment]
이거 어떡하죠ㅠㅠ?

**Comment by Jimmy607-2020** [comment]
TokenError: authorization code not found for code=WrlmMuGXzGDDNVe4z3ogLhG1BKws-uEFv6a6pssicsFlQUjDVM_3oMITSzIiSX31NO2tOAo9c-sAAAFwdWtCuQ
    at Strategy.OAuth2Strategy.parseErrorResponse (C:\Users\user\Desktop\KKuTu\Server\lib\node_modules\passport-kakao\node_modules\passport-oauth2\lib\strategy.js:298:12)
    at Strategy.OAuth2Strategy._createOAuthError (C:\Users\user\Desktop\KKuTu\Server\lib\node_modules\passport-kakao\node_modules\passport-oauth2\lib\strategy.js:345:16)
    at C:\Users\user\Desktop\KKuTu\Server\lib\node_modules\passport-kakao\node_modules\passport-oauth2\lib\strategy.js:171:43
    at C:\Users\user\Desktop\KKuTu\Server\lib\node_modules\oauth\lib\oauth2.js:191:18
    at passBackControl (C:\Users\user\Desktop\KKuTu\Server\lib\node_modules\oauth\lib\oauth2.js:132:9)
    at IncomingMessage.<anonymous> (C:\Users\user\Desktop\KKuTu\Server\lib\node_modules\oauth\lib\oauth2.js:157:7)
    at IncomingMessage.emit (events.js:228:7)
    at endReadableNT (_stream_readable.js:1185:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21) 이런 것도 뜨네요ㅠㅠ

**Comment by lshqqytiger** [comment]
저도 원인 파악 중에 있습니다.
현재로서는 임시로 카카오 로그인을 비활성화 하는 것 외엔 방법이 없네요.

**Comment by Jimmy607-2020** [comment]
아...빨리 해결했으면 좋겠네요

**Comment by Jimmy607-2020** [comment]
흠...아직도 안되나요?

**Comment by pink-flower** [comment]
#675 를 참고해보세요.

**Comment by Jimmy607-2020** [comment]
#675 해봐도 소용 없어요...

**Comment by Maple-kkutu** [comment]
그리고 명령 프롬프트에 npm i passport-kakao를 쳤는데 C:\Users\user>npm i passport-kakao
npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\user\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\user\package.json'
npm WARN user No description
npm WARN user No repository field.
npm WARN user No README data
npm WARN user No license field.

+ passport-kakao@1.0.0
updated 1 package and audited 10 packages in 1.547s
found 0 vulnerabilities가 있어서 해봐도 안되더라고요?

**Comment by lshqqytiger** [comment]
```C:\Users\user```에서 실행하시면 안되고 끄투 폴더 내부에서 설치하셔야 합니다. (```KKuTu-master\Server\lib\```

**Comment by Maple-kkutu** [comment]
KKuTu-master\Server\lib에서 설치 해봤는데 뭔지 모르겠어요...

**Comment by lshqqytiger** [comment]
```
updated 1 package and audited 10 packages in 1.547s -> 패키지 하나를 설치하였고 1.547초 소요
found 0 vulnerabilities -> 아무 문제 없이 설치됨
```
이거 말하시는 건가요?

**Comment by Maple-kkutu** [comment]
아니요 뭔 말인지 모르겠는게 아니고 여기서 카카오 로그인을 ### KKuTu-master\Server\lib에서 하는 이유인지 알려주세요(?)

**Comment by lshqqytiger** [comment]
무슨 질문인지 잘 모르겠습니다.
passport-kakao 모듈을 끄투 폴더 내에 설치해야 auth_kakao.js가 제대로 작동하죠.
다른데 설치하면 auth_kakao.js에서 모듈이 설치된 걸로 인식을 안하죠.
(`KKuTu-master\Server\lib\node_modules`)
https://github.com/JJoriping/KKuTu/blob/8454e7b85f2389815642645ae4b2e72deec4f94e/Server/lib/Web/auth/auth_kakao.js#L4

**Comment by Maple-kkutu** [comment]
아하...
그런 말이였군요? 네 알겠습니다

**Comment by Random-Studio** [comment]
그 이후로 새로 서버를 만든 다음 디스코드 로그인으로 변경되었습니다.
