### ISSUE TITLE
구글 로그인 오류

### ISSUE THREAD

**Issue by KellogDES** [JJoriping/KKuTu#646]
다른 문제들은 구글링을 하거나 닫힌 이슈들 찾아가 보면서 해결했는데 이 로그인 오류는 해결하지 못하겠더라구요.. 저랑 오류로그가 비슷하신 분들이 해결하신 방법 google+ api 온 오프 확인도 해보고 리디렉션 url http://제도메인.kro.kr/login/google/callback 설정도 하고 다했는데도 이런 오류가 뜨네요 아무나 저 좀 도와주세요 ㅠㅠ 구글 계정으로 로그인 하면 뜨는 오류로그는 아래와 같습니다

InternalOAuthError: failed to fetch user profile
    at C:\Users\개인정보\Desktop\KKuTu-master (1)\KKuTu-master\Server\lib\node_modules\passport-google-oauth2\lib\oauth2.js:92:28
    at passBackControl (C:\Users\개인정보\Desktop\KKuTu-master (1)\KKuTu-master\Server\lib\node_modules\oauth\lib\oauth2.js:132:9)
    at IncomingMessage.<anonymous> (C:\Users\개인정보\Desktop\KKuTu-master (1)\KKuTu-master\Server\lib\node_modules\oauth\lib\oauth2.js:157:7)
    at IncomingMessage.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Comment by wjdgustn** [comment]
passport-google-oauth2의 버전을 0.2.0으로 바꿔보세요.

**Comment by lshqqytiger** [comment]
#598 참고해보세요

**Comment by KellogDES** [comment]
0.2.0으로 버전을 바꾸니깐 400 Error:invalid_request 가 뜨네요

**Comment by lshqqytiger** [comment]
#598 의 모든 변경 사항들을 적용하셨나요

**Comment by KellogDES** [comment]
> #598 의 모든 변경 사항들을 적용하셨나요

저 글을 글 쓰기 전에 봤어서 package.json 하고 package-lock.json 및 스코프 제거는 다 해놨습니다

**Comment by andjsrk** [comment]
모듈들을 업데이트해보세요.
