### ISSUE TITLE
SSL 오류

### ISSUE THREAD

**Issue by jm073011** [JJoriping/KKuTu#691]
SSL 추가 후 에러가 뜹니다.
다음은 제가 고친 파일들입니다,
global.json
**{
	"ADMIN": [ "135511848" ],
	"MAIN_PORTS": [ 8080 ],
	"KKUTUHOT_PATH": "/kkutu/data/kkutuhot.json",
	"PASS":"11",
	"PG_USER": "postgres",
	"PG_PASSWORD": "11",
	"PG_PORT": 5432,
	"PG_DATABASE": "main",
	"GOOGLE_RECAPTCHA_TO_GUEST": false,
	"GOOGLE_RECAPTCHA_TO_USER": false,
	"GOOGLE_RECAPTCHA_SITE_KEY": "Your Google Recaptcha site key Here",
	"GOOGLE_RECAPTCHA_SECRET_KEY": "Your Google Recaptcha secret key Here",
	"IS_SECURED": true,
	"SSL_OPTIONS": {
		"PRIVKEY": "C:\\Users\\admin\\Desktop\\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\\ssl\\private.key",
		"CERT": "C:\\Users\\admin\\Desktop\\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\\ssl\\certificate.crt",
		"CA": "C:\\Users\\admin\\Desktop\\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\\ssl\\ca_bundle.crt",
		"PFX": "jmjmjm0730",
		"isPFX": false,
		"isCA": false
	}
}**

main.js 중
	Server.listen(443);
	if(Const.IS_SECURED) {
		const options = Secure();
		https.createServer(options, Server).listen(443);

이건 에러내용입니다.
events.js:287 throw er; // Unhandled 'error' event ^ Error: bind EADDRINUSE null:443 at listenOnMasterHandle (net.js:1380:18) at shared (internal/cluster/child.js:126:3) at Worker.&lt;anonymous> (internal/cluster/child.js:97:7) at process.onInternalMessage (internal/cluster/utils.js:47:8) at process.emit (events.js:322:22) at emit (internal/child_process.js:876:12) at processTicksAndRejections (internal/process/task_queues.js:85:21) Emitted 'error' event on Server instance at: at listenOnMasterHandle (net.js:1381:21) at shared (internal/cluster/child.js:126:3) [... lines matching original stack trace ...] at processTicksAndRejections (internal/process/task_queues.js:85:21) { errno: 'EADDRINUSE', code: 'EADDRINUSE', syscall: 'bind', address: null, port: 443 }

전체
KKuTu Server Manager v2.5.1 - 끄투온라인
환영합니다.
C:\Users\admin\Desktop\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\Server\lib\sub\secure.js:17 }``` ^^ SyntaxError: Unexpected template string at wrapSafe (internal/modules/cjs/loader.js:1070:16) at Module._compile (internal/modules/cjs/loader.js:1120:27) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10) at Module.load (internal/modules/cjs/loader.js:1000:32) at Function.Module._load (internal/modules/cjs/loader.js:899:14) at Module.require (internal/modules/cjs/loader.js:1042:19) at require (internal/modules/cjs/helpers.js:77:18) at Object.&lt;anonymous> (C:\Users\admin\Desktop\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\Server\lib\Game\master.js:29:14) at Module._compile (internal/modules/cjs/loader.js:1156:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
G: CLOSED WITH CODE 1
C:\Users\admin\Desktop\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\Server\lib\sub\secure.js:17 }``` ^^ SyntaxError: Unexpected template string at wrapSafe (internal/modules/cjs/loader.js:1070:16) at Module._compile (internal/modules/cjs/loader.js:1120:27) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10) at Module.load (internal/modules/cjs/loader.js:1000:32) at Function.Module._load (internal/modules/cjs/loader.js:899:14) at Module.require (internal/modules/cjs/loader.js:1042:19) at require (internal/modules/cjs/helpers.js:77:18) at Object.&lt;anonymous> (C:\Users\admin\Desktop\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\Server\lib\Web\main.js:37:14) at Module._compile (internal/modules/cjs/loader.js:1156:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
Worker 6692 died
W: CLOSED WITH CODE 0
C:\Users\admin\Desktop\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\Server\lib\sub\secure.js:17 }``` ^^ SyntaxError: Unexpected template string at wrapSafe (internal/modules/cjs/loader.js:1070:16) at Module._compile (internal/modules/cjs/loader.js:1120:27) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10) at Module.load (internal/modules/cjs/loader.js:1000:32) at Function.Module._load (internal/modules/cjs/loader.js:899:14) at Module.require (internal/modules/cjs/loader.js:1042:19) at require (internal/modules/cjs/helpers.js:77:18) at Object.&lt;anonymous> (C:\Users\admin\Desktop\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\Server\lib\Game\master.js:29:14) at Module._compile (internal/modules/cjs/loader.js:1156:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
G: CLOSED WITH CODE 1
C:\Users\admin\Desktop\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\Server\lib\sub\secure.js:17 }``` ^^ SyntaxError: Unexpected template string at wrapSafe (internal/modules/cjs/loader.js:1070:16) at Module._compile (internal/modules/cjs/loader.js:1120:27) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10) at Module.load (internal/modules/cjs/loader.js:1000:32) at Function.Module._load (internal/modules/cjs/loader.js:899:14) at Module.require (internal/modules/cjs/loader.js:1042:19) at require (internal/modules/cjs/helpers.js:77:18) at Object.&lt;anonymous> (C:\Users\admin\Desktop\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\Server\lib\Web\main.js:37:14) at Module._compile (internal/modules/cjs/loader.js:1156:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
Worker 5540 died
W: CLOSED WITH CODE 0
[2020-04-23 20:57:19] &lt;&lt; KKuTu Web >>
[2020-04-23 20:57:19] Master DB is ready.
[2020-04-23 20:57:19] &lt;&lt; KKuTu Server:8496 >>
[2020-04-23 20:57:20] DB is ready.
[2020-04-23 20:57:20] OAuth Strategy naver loaded successfully.
[2020-04-23 20:57:20] OAuth Strategy facebook is not loaded
[2020-04-23 20:57:20] OAuth2Strategy requires a clientID option
[2020-04-23 20:57:20] OAuth Strategy google is not loaded [2020-04-23 20:57:20] OAuth2Strategy requires a clientID option
[2020-04-23 20:57:20] OAuth Strategy twitter is not loaded [2020-04-23 20:57:20] OAuthStrategy requires a consumerKey option
[2020-04-23 20:57:20] OAuth Strategy kakao is not loaded [2020-04-23 20:57:20] OAuth2Strategy requires a clientID option
[2020-04-23 20:57:20] OAuth Strategy discord is not loaded
[2020-04-23 20:57:20] OAuth2Strategy requires a clientID option
[2020-04-23 20:57:20] OAuth Strategy twitch is not loaded [2020-04-23 20:57:20] OAuth2Strategy requires a clientID option
[2020-04-23 20:57:20] OAuth Strategy github is not loaded [2020-04-23 20:57:20] OAuth2Strategy requires a clientID option
[2020-04-23 20:57:20] OAuth Strategy line is not loaded [2020-04-23 20:57:20] OAuth2Strategy requires a clientID option
[2020-04-23 20:57:20] OAuth Strategy instagram is not loaded [2020-04-23 20:57:20] OAuth2Strategy requires a clientID option
[2020-04-23 20:57:20] OAuth Strategy spotify is not loaded [2020-04-23 20:57:20] OAuth2Strategy requires a clientID option
[2020-04-23 20:57:20] New web server #1
[2020-04-23 20:57:20] Game server #1 connected
[2020-04-23 20:57:20] DB is ready.
[2020-04-23 20:57:40] 180.254.159.41@pie6ANTGG9 portal, {}
[2020-04-23 20:57:43] 192.168.0.1@A8k20hR8Hw portal, {}
G: CLOSED WITH CODE null
W: CLOSED WITH CODE null
[2020-04-23 21:03:45] &lt;&lt; KKuTu Web >>
[2020-04-23 21:03:45] Master DB is ready.
[2020-04-23 21:03:45] &lt;&lt; KKuTu Server:null >>
[2020-04-23 21:03:46] DB is ready.
[2020-04-23 21:03:46] OAuth Strategy naver loaded successfully.
[2020-04-23 21:03:46] OAuth Strategy facebook is not loaded [2020-04-23 21:03:46] OAuth2Strategy requires a clientID option
[2020-04-23 21:03:46] OAuth Strategy google is not loaded [2020-04-23 21:03:46] OAuth2Strategy requires a clientID option
[2020-04-23 21:03:46] OAuth Strategy twitter is not loaded [2020-04-23 21:03:46] OAuthStrategy requires a consumerKey option
[2020-04-23 21:03:46] OAuth Strategy kakao is not loaded [2020-04-23 21:03:46] OAuth2Strategy requires a clientID option
[2020-04-23 21:03:46] OAuth Strategy discord is not loaded [2020-04-23 21:03:46] OAuth2Strategy requires a clientID option
[2020-04-23 21:03:46] OAuth Strategy twitch is not loaded [2020-04-23 21:03:46] OAuth2Strategy requires a clientID option
[2020-04-23 21:03:46] OAuth Strategy github is not loaded [2020-04-23 21:03:46] OAuth2Strategy requires a clientID option
[2020-04-23 21:03:46] OAuth Strategy line is not loaded [2020-04-23 21:03:46] OAuth2Strategy requires a clientID option
[2020-04-23 21:03:46] OAuth Strategy instagram is not loaded [2020-04-23 21:03:46] OAuth2Strategy requires a clientID option
[2020-04-23 21:03:46] OAuth Strategy spotify is not loaded [2020-04-23 21:03:46] OAuth2Strategy requires a clientID option
[2020-04-23 21:03:46] New web server #1
[2020-04-23 21:03:46] Game server #1 connected
[2020-04-23 21:03:46] DB is ready.
C:\Users\admin\Desktop\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\Server\lib\Web\main.js:150 const options = secure(); ^ ReferenceError: secure is not defined at Object.DB.ready (C:\Users\admin\Desktop\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\Server\lib\Web\main.js:150:19) at C:\Users\admin\Desktop\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\Server\lib\Web\db.js:87:30 at BoundPool.&lt;anonymous> (C:\Users\admin\Desktop\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\Server\lib\node_modules\pg-pool\index.js:137:9) at C:\Users\admin\Desktop\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\Server\lib\node_modules\generic-pool\lib\generic-pool.js:347:9 at BoundPool.&lt;anonymous> (C:\Users\admin\Desktop\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\Server\lib\node_modules\pg-pool\index.js:103:7) at Connection.&lt;anonymous> (C:\Users\admin\Desktop\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\Server\lib\node_modules\pg\lib\client.js:166:7) at Object.onceWrapper (events.js:417:26) at Connection.emit (events.js:322:22) at Socket.&lt;anonymous> (C:\Users\admin\Desktop\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\Server\lib\node_modules\pg\lib\connection.js:133:12) at Socket.emit (events.js:310:20)
[2020-04-23 21:03:46] Exit web server #1
Worker 19184 died
W: CLOSED WITH CODE 0
G: CLOSED WITH CODE null
[2020-04-23 21:05:36] &lt;&lt; KKuTu Web >>
[2020-04-23 21:05:36] &lt;&lt; KKuTu Server:null >>
[2020-04-23 21:05:36] Master DB is ready.
[2020-04-23 21:05:36] DB is ready.
[2020-04-23 21:05:36] OAuth Strategy naver loaded successfully.
[2020-04-23 21:05:36] OAuth Strategy facebook is not loaded
[2020-04-23 21:05:36] OAuth2Strategy requires a clientID option
[2020-04-23 21:05:36] OAuth Strategy google is not loaded [2020-04-23 21:05:36] OAuth2Strategy requires a clientID option
[2020-04-23 21:05:36] OAuth Strategy twitter is not loaded [2020-04-23 21:05:36] OAuthStrategy requires a consumerKey option
[2020-04-23 21:05:36] OAuth Strategy kakao is not loaded [2020-04-23 21:05:36] OAuth2Strategy requires a clientID option
[2020-04-23 21:05:36] OAuth Strategy discord is not loaded [2020-04-23 21:05:36] OAuth2Strategy requires a clientID option
[2020-04-23 21:05:36] OAuth Strategy twitch is not loaded [2020-04-23 21:05:36] OAuth2Strategy requires a clientID option
[2020-04-23 21:05:36] OAuth Strategy github is not loaded [2020-04-23 21:05:36] OAuth2Strategy requires a clientID option
[2020-04-23 21:05:36] OAuth Strategy line is not loaded
[2020-04-23 21:05:36] OAuth2Strategy requires a clientID option
[2020-04-23 21:05:36] OAuth Strategy instagram is not loaded [2020-04-23 21:05:36] OAuth2Strategy requires a clientID option
[2020-04-23 21:05:36] OAuth Strategy spotify is not loaded
[2020-04-23 21:05:36] OAuth2Strategy requires a clientID option
[2020-04-23 21:05:36] New web server #1
[2020-04-23 21:05:36] Game server #1 connected
[2020-04-23 21:05:36] DB is ready.
events.js:287 throw er; // Unhandled 'error' event ^ Error: bind EADDRINUSE null:443 at listenOnMasterHandle (net.js:1380:18) at shared (internal/cluster/child.js:126:3) at Worker.&lt;anonymous> (internal/cluster/child.js:97:7) at process.onInternalMessage (internal/cluster/utils.js:47:8) at process.emit (events.js:322:22) at emit (internal/child_process.js:876:12) at processTicksAndRejections (internal/process/task_queues.js:85:21) Emitted 'error' event on Server instance at: at listenOnMasterHandle (net.js:1381:21) at shared (internal/cluster/child.js:126:3) [... lines matching original stack trace ...] at processTicksAndRejections (internal/process/task_queues.js:85:21) { errno: 'EADDRINUSE', code: 'EADDRINUSE', syscall: 'bind', address: null, port: 443 }
[2020-04-23 21:05:36] Exit web server #1
Worker 17160 died
W: CLOSED WITH CODE 0

제 정보력이 안좋은지는 몰라도 이슈를 뒤져봐도 나오지 않습니다
도와주세요~~!

**Comment by lshqqytiger** [comment]
```
Server.listen(80);
	if(Const.IS_SECURED) {
		const options = Secure();
		https.createServer(options, Server).listen(443);
	}
```
`main.js`는 이게 원래 정상이구요.
`isCA` 값을 true로 바꿔주세요.

**Comment by jm073011** [comment]
해결했습니다!
정말 감사합니다!
