### ISSUE TITLE
서버에서 행동이 안되는 버그

### ISSUE THREAD

**Issue by papakia1234** [JJoriping/KKuTu#721]
로그:
`환영합니다!.
[2020-07-04 13:59:12] &lt;&lt; KKuTu Web >>
[2020-07-04 13:59:12] &lt;&lt; KKuTu Server:8496 >>
[2020-07-04 13:59:12] Master DB is ready.
[2020-07-04 13:59:12] DB is ready.
[2020-07-04 13:59:12] OAuth Strategy naver loaded successfully.
[2020-07-04 13:59:12] OAuth Strategy facebook is not loaded
[2020-07-04 13:59:12] OAuth2Strategy requires a clientID option
[2020-07-04 13:59:12] OAuth Strategy google is not loaded [2020-07-04 13:59:12] OAuth2Strategy requires a clientID option
[2020-07-04 13:59:12] OAuth Strategy twitter is not loaded [2020-07-04 13:59:12] OAuthStrategy requires a consumerKey option
[2020-07-04 13:59:13] OAuth Strategy kakao is not loaded [2020-07-04 13:59:13] OAuth2Strategy requires a clientID option
[2020-07-04 13:59:13] OAuth Strategy discord loaded successfully.
[2020-07-04 13:59:13] OAuth Strategy twitch is not loaded [2020-07-04 13:59:13] OAuth2Strategy requires a clientID option
[2020-07-04 13:59:13] OAuth Strategy github is not loaded [2020-07-04 13:59:13] OAuth2Strategy requires a clientID option
[2020-07-04 13:59:13] OAuth Strategy line is not loaded [2020-07-04 13:59:13] OAuth2Strategy requires a clientID option
[2020-07-04 13:59:13] OAuth Strategy instagram is not loaded [2020-07-04 13:59:13] OAuth2Strategy requires a clientID option
[2020-07-04 13:59:13] OAuth Strategy spotify is not loaded [2020-07-04 13:59:13] OAuth2Strategy requires a clientID option
[2020-07-04 13:59:13] New web server #1
[2020-07-04 13:59:13] Game server #1 connected
[2020-07-04 13:59:13] DB is ready.
[2020-07-04 13:59:20] 192.168.56.1@dvLuAUZjLY portal, {}
[2020-07-04 13:59:25] 192.168.56.1@dvLuAUZjLY login, {}
[2020-07-04 13:59:31] 192.168.56.1@dvLuAUZjLY portal, {}
[2020-07-04 13:59:36] 192.168.56.1@dvLuAUZjLY kkutu, {}
[2020-07-04 13:59:40] New user #discord-724500350731550741
[2020-07-04 13:59:40] Error when querying: UPDATE users SET "lastaccess"=202064 WHERE "_id"='discord-724500350731550741' [2020-07-04 13:59:40] Context: error: column "lastaccess" of relation "users" does not exist
[2020-07-04 13:59:43] Chan @0 Msg #discord-724500350731550741: {"type":"talk","value":"ㅇ"}
[2020-07-04 13:59:43] ERROR OCCURRED ON THE MASTER! :8080 [2020-7-4 13:59:43] ERROR: TypeError: Cannot read property 'indexOf' of undefined TypeError: Cannot read property 'indexOf' of undefined at exports.Client.my.chat (C:\Users\김태원\Desktop\KKuTu\Server\lib\Game\kkutu.js:396:35) at processClientRequest (C:\Users\김태원\Desktop\KKuTu\Server\lib\Game\master.js:461:8) at Object.KKuTu.onClientMessage (C:\Users\김태원\Desktop\KKuTu\Server\lib\Game\master.js:400:3) at WebSocket.&lt;anonymous> (C:\Users\김태원\Desktop\KKuTu\Server\lib\Game\kkutu.js:305:11) at WebSocket.emit (events.js:311:20) at Receiver._receiver.onmessage (C:\Users\김태원\Desktop\KKuTu\Server\lib\node_modules\ws\lib\WebSocket.js:143:47) at Receiver.dataMessage (C:\Users\김태원\Desktop\KKuTu\Server\lib\node_modules\ws\lib\Receiver.js:389:14) at Receiver.getData (C:\Users\김태원\Desktop\KKuTu\Server\lib\node_modules\ws\lib\Receiver.js:330:12) at Receiver.startLoop (C:\Users\김태원\Desktop\KKuTu\Server\lib\node_modules\ws\lib\Receiver.js:165:16) at Receiver.add (C:\Users\김태원\Desktop\KKuTu\Server\lib\node_modules\ws\lib\Receiver.js:139:10)
[2020-07-04 13:59:43] ERROR OCCURRED ON THE MASTER! :8080 [2020-7-4 13:59:43] ERROR: SyntaxError: Unexpected token  in JSON at position 0 SyntaxError: Unexpected token  in JSON at position 0 at JSON.parse (&lt;anonymous>) at WebSocket.&lt;anonymous> (C:\Users\김태원\Desktop\KKuTu\Server\lib\Game\kkutu.js:301:53) at WebSocket.emit (events.js:311:20) at Receiver._receiver.onmessage (C:\Users\김태원\Desktop\KKuTu\Server\lib\node_modules\ws\lib\WebSocket.js:143:47) at Receiver.dataMessage (C:\Users\김태원\Desktop\KKuTu\Server\lib\node_modules\ws\lib\Receiver.js:389:14) at Receiver.getData (C:\Users\김태원\Desktop\KKuTu\Server\lib\node_modules\ws\lib\Receiver.js:330:12) at Receiver.startLoop (C:\Users\김태원\Desktop\KKuTu\Server\lib\node_modules\ws\lib\Receiver.js:165:16) at Receiver.add (C:\Users\김태원\Desktop\KKuTu\Server\lib\node_modules\ws\lib\Receiver.js:139:10) at Socket.&lt;anonymous> (C:\Users\김태원\Desktop\KKuTu\Server\lib\node_modules\ws\lib\WebSocket.js:139:22) at Socket.emit (events.js:311:20)
[2020-07-04 13:59:43] ERROR OCCURRED ON THE MASTER! :8080 [2020-7-4 13:59:43] ERROR: SyntaxError: Unexpected token � in JSON at position 0 SyntaxError: Unexpected token � in JSON at position 0 at JSON.parse (&lt;anonymous>) at WebSocket.&lt;anonymous> (C:\Users\김태원\Desktop\KKuTu\Server\lib\Game\kkutu.js:301:53) at WebSocket.emit (events.js:311:20) at Receiver._receiver.onmessage (C:\Users\김태원\Desktop\KKuTu\Server\lib\node_modules\ws\lib\WebSocket.js:143:47) at Receiver.dataMessage (C:\Users\김태원\Desktop\KKuTu\Server\lib\node_modules\ws\lib\Receiver.js:389:14) at Receiver.getData (C:\Users\김태원\Desktop\KKuTu\Server\lib\node_modules\ws\lib\Receiver.js:330:12) at Receiver.startLoop (C:\Users\김태원\Desktop\KKuTu\Server\lib\node_modules\ws\lib\Receiver.js:165:16) at Receiver.add (C:\Users\김태원\Desktop\KKuTu\Server\lib\node_modules\ws\lib\Receiver.js:139:10) at Socket.&lt;anonymous> (C:\Users\김태원\Desktop\KKuTu\Server\lib\node_modules\ws\lib\WebSocket.js:139:22) at Socket.emit (events.js:311:20)
[2020-07-04 13:59:43] ERROR OCCURRED ON THE MASTER! :8080 [2020-7-4 13:59:43] ERROR: SyntaxError: Unexpected token � in JSON at position 0 SyntaxError: Unexpected token � in JSON at position 0 at JSON.parse (&lt;anonymous>) at WebSocket.&lt;anonymous> (C:\Users\김태원\Desktop\KKuTu\Server\lib\Game\kkutu.js:301:53) at WebSocket.emit (events.js:311:20) at Receiver._receiver.onmessage (C:\Users\김태원\Desktop\KKuTu\Server\lib\node_modules\ws\lib\WebSocket.js:143:47) at Receiver.dataMessage (C:\Users\김태원\Desktop\KKuTu\Server\lib\node_modules\ws\lib\Receiver.js:389:14) at Receiver.getData (C:\Users\김태원\Desktop\KKuTu\Server\lib\node_modules\ws\lib\Receiver.js:330:12) at Receiver.startLoop (C:\Users\김태원\Desktop\KKuTu\Server\lib\node_modules\ws\lib\Receiver.js:165:16) at Receiver.add (C:\Users\김태원\Desktop\KKuTu\Server\lib\node_modules\ws\lib\Receiver.js:139:10) at Socket.&lt;anonymous> (C:\Users\김태원\Desktop\KKuTu\Server\lib\node_modules\ws\lib\WebSocket.js:139:22) at Socket.emit (events.js:311:20)
[2020-07-04 13:59:44] ERROR OCCURRED ON THE MASTER! :8080 [2020-7-4 13:59:44] ERROR: SyntaxError: Unexpected token T in JSON at position 0 SyntaxError: Unexpected token T in JSON at position 0 at JSON.parse (&lt;anonymous>) at WebSocket.&lt;anonymous> (C:\Users\김태원\Desktop\KKuTu\Server\lib\Game\kkutu.js:301:53) at WebSocket.emit (events.js:311:20) at Receiver._receiver.onmessage (C:\Users\김태원\Desktop\KKuTu\Server\lib\node_modules\ws\lib\WebSocket.js:143:47) at Receiver.dataMessage (C:\Users\김태원\Desktop\KKuTu\Server\lib\node_modules\ws\lib\Receiver.js:389:14) at Receiver.getData (C:\Users\김태원\Desktop\KKuTu\Server\lib\node_modules\ws\lib\Receiver.js:330:12) at Receiver.startLoop (C:\Users\김태원\Desktop\KKuTu\Server\lib\node_modules\ws\lib\Receiver.js:165:16) at Receiver.add (C:\Users\김태원\Desktop\KKuTu\Server\lib\node_modules\ws\lib\Receiver.js:139:10) at Socket.&lt;anonymous> (C:\Users\김태원\Desktop\KKuTu\Server\lib\node_modules\ws\lib\WebSocket.js:139:22) at Socket.emit (events.js:311:20)
[2020-07-04 13:59:44] ERROR OCCURRED ON THE MASTER! :8080 [2020-7-4 13:59:44] ERROR: SyntaxError: Unexpected token փ in JSON at position 0 SyntaxError: Unexpected token փ in JSON at position 0 at JSON.parse (&lt;anonymous>) at WebSocket.&lt;anonymous> (C:\Users\김태원\Desktop\KKuTu\Server\lib\Game\kkutu.js:301:53) at WebSocket.emit (events.js:311:20) at Receiver._receiver.onmessage (C:\Users\김태원\Desktop\KKuTu\Server\lib\node_modules\ws\lib\WebSocket.js:143:47) at Receiver.dataMessage (C:\Users\김태원\Desktop\KKuTu\Server\lib\node_modules\ws\lib\Receiver.js:389:14) at Receiver.getData (C:\Users\김태원\Desktop\KKuTu\Server\lib\node_modules\ws\lib\Receiver.js:330:12) at Receiver.startLoop (C:\Users\김태원\Desktop\KKuTu\Server\lib\node_modules\ws\lib\Receiver.js:165:16) at Receiver.add (C:\Users\김태원\Desktop\KKuTu\Server\lib\node_modules\ws\lib\Receiver.js:139:10) at Socket.&lt;anonymous> (C:\Users\김태원\Desktop\KKuTu\Server\lib\node_modules\ws\lib\WebSocket.js:139:22) at Socket.emit (events.js:311:20)
[2020-07-04 13:59:48] ERROR OCCURRED ON THE MASTER! :8080 [2020-7-4 13:59:48] ERROR: SyntaxError: Unexpected token � in JSON at position 0 SyntaxError: Unexpected token � in JSON at position 0 at JSON.parse (&lt;anonymous>) at WebSocket.&lt;anonymous> (C:\Users\김태원\Desktop\KKuTu\Server\lib\Game\kkutu.js:301:53) at WebSocket.emit (events.js:311:20) at Receiver._receiver.onmessage (C:\Users\김태원\Desktop\KKuTu\Server\lib\node_modules\ws\lib\WebSocket.js:143:47) at Receiver.dataMessage (C:\Users\김태원\Desktop\KKuTu\Server\lib\node_modules\ws\lib\Receiver.js:389:14) at Receiver.getData (C:\Users\김태원\Desktop\KKuTu\Server\lib\node_modules\ws\lib\Receiver.js:330:12) at Receiver.startLoop (C:\Users\김태원\Desktop\KKuTu\Server\lib\node_modules\ws\lib\Receiver.js:165:16) at Receiver.add (C:\Users\김태원\Desktop\KKuTu\Server\lib\node_modules\ws\lib\Receiver.js:139:10) at Socket.&lt;anonymous> (C:\Users\김태원\Desktop\KKuTu\Server\lib\node_modules\ws\lib\WebSocket.js:139:22) at Socket.emit (events.js:311:20)
[2020-07-04 13:59:54] 192.168.56.1@dvLuAUZjLY portal, {}
[2020-07-04 13:59:54] ERROR OCCURRED ON THE MASTER! :8080 [2020-7-4 13:59:54] ERROR: SyntaxError: Unexpected token � in JSON at position 1 SyntaxError: Unexpected token � in JSON at position 1 at JSON.parse (&lt;anonymous>) at WebSocket.&lt;anonymous> (C:\Users\김태원\Desktop\KKuTu\Server\lib\Game\kkutu.js:301:53) at WebSocket.emit (events.js:311:20) at Receiver._receiver.onmessage (C:\Users\김태원\Desktop\KKuTu\Server\lib\node_modules\ws\lib\WebSocket.js:143:47) at Receiver.dataMessage (C:\Users\김태원\Desktop\KKuTu\Server\lib\node_modules\ws\lib\Receiver.js:389:14) at Receiver.getData (C:\Users\김태원\Desktop\KKuTu\Server\lib\node_modules\ws\lib\Receiver.js:330:12) at Receiver.startLoop (C:\Users\김태원\Desktop\KKuTu\Server\lib\node_modules\ws\lib\Receiver.js:165:16) at Receiver.add (C:\Users\김태원\Desktop\KKuTu\Server\lib\node_modules\ws\lib\Receiver.js:139:10) at Socket.&lt;anonymous> (C:\Users\김태원\Desktop\KKuTu\Server\lib\node_modules\ws\lib\WebSocket.js:139:22) at Socket.emit (events.js:311:20)`

**Comment by lshqqytiger** [comment]
채팅 데이터를 제대로 파싱하지 못하는 것 같습니다.

**Comment by hatty163** [comment]
현재 그림퀴즈 관련 PR 적용 시, 누군가 웹소켓으로 빈 요청을 보낼 경우 오류가 발생하고 있습니다.
[이곳](https://github.com/JJoriping/KKuTu/pull/326/files/096640351e2219ecc9d523532dfd20107cf7b66e#diff-ed61428d3d3778064094e7ef9250e05e)을 참고해주세요.

**Comment by papakia1234** [comment]
무슨 오류를 수정해야 하지요?

**Comment by lshqqytiger** [comment]
```if(!my) return;
if(!msg) return;
if(!my.id) return;```
이걸 추가해보세요.

**Comment by papakia1234** [comment]
어디에 추가 하나요?

**Comment by hatty163** [comment]
@lshqqytiger 그렇게 하면 일부 요청이 정상적으로 작동하지 않을 뿐더러, 근본적인 해결책이 아닙니다.

위에 링크해둔 diff를 참조해주세요.

**Comment by lshqqytiger** [comment]
저는 DDoS 공격 당할 때 로그가 도배되는 게 싫어서 그냥 둘 다 처리해뒀습니다.
딱히 별다른 문제는 없네요.

**Comment by papakia1234** [comment]
그냥 초기화 할게요
