### ISSUE TITLE
네이버 로그인 후 오류

### ISSUE THREAD

**Issue by qkrdbqls3398** [JJoriping/KKuTu#723]
[2020-07-05 14:19:53] ERROR OCCURRED ON THE MASTER! :8080 [2020-7-5 2:19:53 ├F10: PM┤] ERROR: TypeError: Cannot read property 'replace' of undefined TypeError: Cannot read property 'replace' of undefined at C:\Users\user\KKuTu-master\Server\lib\Game\master.js:345:51 at exports.Tail.go (C:\Users\user\KKuTu-master\Server\lib\sub\lizard.js:43:16) at C:\Users\user\KKuTu-master\Server\lib\Game\kkutu.js:455:11 at callback (C:\Users\user\KKuTu-master\Server\lib\sub\collection.js:316:13) at Result.preCB (C:\Users\user\KKuTu-master\Server\lib\sub\collection.js:298:6) at Result.Query.handleReadyForQuery (C:\Users\user\KKuTu-master\Server\lib\node_modules\pg\lib\query.js:144:10) at Connection.&lt;anonymous> (C:\Users\user\KKuTu-master\Server\lib\node_modules\pg\lib\client.js:180:19) at Connection.emit (events.js:315:20) at Socket.&lt;anonymous> (C:\Users\user\KKuTu-master\Server\lib\node_modules\pg\lib\connection.js:133:12) at Socket.emit (events.js:315:20)

어디부분이 잘못된건가요?

**Comment by lshqqytiger** [comment]
```DNAME[($c.profile.title || $c.profile.name).replace(/\s/g, "")] = $c.id;```
$c.profile.title 또는 $c.profile.name이 정해지지 않았습니다.

**Comment by qkrdbqls3398** [comment]
$p.name = profile.displayName;
$p.title = profile.displayName;

이 두 부분만 설정하면 되는거죠?
