### ISSUE TITLE
오류 문제 고치는법 알려주세요

### ISSUE THREAD

**Issue by kimdoyun0217** [JJoriping/KKuTu#752]
[2020-08-29 17:57:37] &lt;&lt; KKuTu Server:8496 >>
[2020-08-29 17:57:37] &lt;&lt; KKuTu Web >>
[2020-08-29 17:57:38] ERROR OCCURRED ON THE MASTER!
:8080 [2020-8-29 5:57:38 ├F10: PM┤] ERROR: Error: Unknown authenticationOk message typeMessage { name: 'authenticationOk', length: 23 } Error: Unknown authenticationOk message typeMessage { name: 'authenticationOk', length: 23 } at Connection.parseR (C:\Users\PC\Desktop\kkutu\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\Server\lib\node_modules\pg\lib\connection.js:454:9) at Connection.parseMessage (C:\Users\PC\Desktop\kkutu\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\Server\lib\node_modules\pg\lib\connection.js:370:17) at Socket.&lt;anonymous> (C:\Users\PC\Desktop\kkutu\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\Server\lib\node_modules\pg\lib\connection.js:129:22) at Socket.emit (events.js:315:20) at addChunk (_stream_readable.js:295:12) at readableAddChunk (_stream_readable.js:271:9) at Socket.Readable.push (_stream_readable.js:212:10) at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
[2020-08-29 17:57:38] ERROR OCCURRED ON THE MASTER! :8496 [2020-8-29 5:57:38 ├F10: PM┤] ERROR: Error: Unknown authenticationOk message typeMessage { name: 'authenticationOk', length: 23 } Error: Unknown authenticationOk message typeMessage { name: 'authenticationOk', length: 23 } at Connection.parseR (C:\Users\PC\Desktop\kkutu\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\Server\lib\node_modules\pg\lib\connection.js:454:9) at Connection.parseMessage (C:\Users\PC\Desktop\kkutu\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\Server\lib\node_modules\pg\lib\connection.js:370:17) at Socket.&lt;anonymous> (C:\Users\PC\Desktop\kkutu\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\Server\lib\node_modules\pg\lib\connection.js:129:22) at Socket.emit (events.js:315:20) at addChunk (_stream_readable.js:295:12) at readableAddChunk (_stream_readable.js:271:9) at Socket.Readable.push (_stream_readable.js:212:10) at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
[2020-08-29 17:57:38] ERROR OCCURRED! This worker will die in 10 seconds. :8496 [2020-8-29 5:57:38 ├F10: PM┤] ERROR: Error: Unknown authenticationOk message typeMessage { name: 'authenticationOk', length: 23 } Error: Unknown authenticationOk message typeMessage { name: 'authenticationOk', length: 23 } at Connection.parseR (C:\Users\PC\Desktop\kkutu\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\Server\lib\node_modules\pg\lib\connection.js:454:9) at Connection.parseMessage (C:\Users\PC\Desktop\kkutu\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\Server\lib\node_modules\pg\lib\connection.js:370:17) at Socket.&lt;anonymous> (C:\Users\PC\Desktop\kkutu\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\Server\lib\node_modules\pg\lib\connection.js:129:22) at Socket.emit (events.js:315:20) at addChunk (_stream_readable.js:295:12) at readableAddChunk (_stream_readable.js:271:9) at Socket.Readable.push (_stream_readable.js:212:10) at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
[2020-08-29 17:57:38] OAuth Strategy naver is not loaded [2020-08-29 17:57:38] OAuth2Strategy requires a clientID option
[2020-08-29 17:57:38] OAuth Strategy facebook is not loaded [2020-08-29 17:57:38] OAuth2Strategy requires a clientID option
[2020-08-29 17:57:38] OAuth Strategy google is not loaded [2020-08-29 17:57:38] OAuth2Strategy requires a clientID option
[2020-08-29 17:57:38] OAuth Strategy twitter is not loaded
[2020-08-29 17:57:38] OAuthStrategy requires a consumerKey option
[2020-08-29 17:57:39] OAuth Strategy kakao is not loaded [2020-08-29 17:57:39] OAuth2Strategy requires a clientID option
[2020-08-29 17:57:39] OAuth Strategy discord is not loaded [2020-08-29 17:57:39] OAuth2Strategy requires a clientID option
[2020-08-29 17:57:39] OAuth Strategy twitch is not loaded [2020-08-29 17:57:39] OAuth2Strategy requires a clientID option
[2020-08-29 17:57:39] OAuth Strategy github is not loaded [2020-08-29 17:57:39] OAuth2Strategy requires a clientID option
[2020-08-29 17:57:39] OAuth Strategy line is not loaded [2020-08-29 17:57:39] OAuth2Strategy requires a clientID option
[2020-08-29 17:57:39] OAuth Strategy instagram is not loaded [2020-08-29 17:57:39] OAuth2Strategy requires a clientID option
[2020-08-29 17:57:39] OAuth Strategy spotify is not loaded [2020-08-29 17:57:39] OAuth2Strategy requires a clientID option
C:\Users\PC\Desktop\kkutu\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\Server\lib\node_modules\pg\lib\connection.js:454 throw new Error("Unknown authenticationOk message type" + util.inspect(msg)); ^ Error: Unknown authenticationOk message typeMessage { name: 'authenticationOk', length: 23 } at Connection.parseR (C:\Users\PC\Desktop\kkutu\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\Server\lib\node_modules\pg\lib\connection.js:454:9) at Connection.parseMessage (C:\Users\PC\Desktop\kkutu\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\Server\lib\node_modules\pg\lib\connection.js:370:17) at Socket.&lt;anonymous> (C:\Users\PC\Desktop\kkutu\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\Server\lib\node_modules\pg\lib\connection.js:129:22) at Socket.emit (events.js:315:20) at addChunk (_stream_readable.js:295:12) at readableAddChunk (_stream_readable.js:271:9) at Socket.Readable.push (_stream_readable.js:212:10) at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
Worker 23260 died
W: CLOSED WITH CODE 0

**Comment by kdhkr** [comment]
#689
3. 이슈 작성에 앞서 `README.md` 파일과 [위키](https://github.com/JJoriping/KKuTu/wiki) 및 **이미 존재하는 이슈**를 참고하시기 바랍니다.
현재 작성이 이루어지는 이슈 중 상당수는 이미 답변된 문제점이거나 README.md 또는 위키에 자세히 서술되어 있는 경우가 많습니다. 이러한 것들을 읽지 않고서 발생하는 문제에 관해서는 도와드리기 어렵습니다.
