### ISSUE TITLE
오류 고치는 법 좀 알려주세요

### ISSUE THREAD

**Issue by odd02311** [JJoriping/KKuTu#754]
W: internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module '../../sub/auth.json'
Require stack:
- D:\open source devleopment\KKuTu-master\Server\lib\Web\routes\login.js
- D:\open source devleopment\KKuTu-master\Server\lib\Web\main.js
- D:\open source devleopment\KKuTu-master\Server\lib\Web\cluster.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (D:\open source devleopment\KKuTu-master\Server\lib\Web\routes\login.js:25:16)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\open source devleopment\\KKuTu-master\\Server\\lib\\Web\\routes\\login.js',
    'D:\\open source devleopment\\KKuTu-master\\Server\\lib\\Web\\main.js',
    'D:\\open source devleopment\\KKuTu-master\\Server\\lib\\Web\\cluster.js'
  ]
}

[2020-09-01 20:50:23] W: CLOSED WITH CODE 0

서버 실행하면 이렇게 뜨는데 어케해야되나요?

끄투 서버 매니저에서는 
internal/modules/cjs/loader.js:968 throw err; ^ Error: Cannot find module '../../sub/auth.json' Require stack: - D:\open source devleopment\KKuTu-master\Server\lib\Web\routes\login.js - D:\open source devleopment\KKuTu-master\Server\lib\Web\main.js - D:\open source devleopment\KKuTu-master\Server\lib\Web\cluster.js at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15) at Function.Module._load (internal/modules/cjs/loader.js:841:27) at Module.require (internal/modules/cjs/loader.js:1025:19) at require (internal/modules/cjs/helpers.js:72:18) at Object.&lt;anonymous> (D:\open source devleopment\KKuTu-master\Server\lib\Web\routes\login.js:25:16) at Module._compile (internal/modules/cjs/loader.js:1137:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10) at Module.load (internal/modules/cjs/loader.js:985:32) at Function.Module._load (internal/modules/cjs/loader.js:878:14) at Module.require (internal/modules/cjs/loader.js:1025:19) { code: 'MODULE_NOT_FOUND', requireStack: [ 'D:\\open source devleopment\\KKuTu-master\\Server\\lib\\Web\\routes\\login.js', 'D:\\open source devleopment\\KKuTu-master\\Server\\lib\\Web\\main.js', 'D:\\open source devleopment\\KKuTu-master\\Server\\lib\\Web\\cluster.js' ] }
Worker 16720 died
이렇게 뜹니다

**Comment by odd02311** [comment]
끄투 server\lib\sub 안에 auto.json이 있는데도 오류가 뜹니다
