### ISSUE TITLE
소셜 로그인 오류

### ISSUE THREAD

**Issue by qkrehddls** [JJoriping/KKuTu#763]
안녕하세요 Discord 소셜 로그인을 설정하려고 하는데 로그인을 시도하려고 하니 Cannot GET /api/oauth2/authorize 라고 오류가 발생해서 npm i passport-discord도 시도해보았는데 그래도 오류가 발생합니다 해결 방법을 아시는 분이 있으신가요 ㅠ
서버 주소는 https://kkutu.us 이고 IIS에서 127.0.0.1:20443포트로 리버스 프록시 사용중입니다 그리고 리다이렉트 URI이 127.0.0.1:20443으로 설정되있는거 같던데 나중에 이 문제를 해결했을때 또 다른 문제가 생길거 같네요 이것도 해결 방법을 아시는분 답변 부탁드립니다 ㅠㅠ

**Comment by lshqqytiger** [comment]
끄투에서는 /api/oauth2/authorize 대신 /login/discord/callback을 사용합니다.
서버 설정과 디스코드 API 콜백 URL 설정을 바꿔주세요.

**Comment by qkrehddls** [comment]
https://kkutu.us/login/discord/callback 로 접근시에  https://kkutu.us/api/oauth2/authorize 로 리다이렉트 됩니다

**Comment by qkrehddls** [comment]
음 일딴 어찌어찌 수정을 했는데
TokenError: Invalid "redirect_uri" in request.
    at Strategy.OAuth2Strategy.parseErrorResponse (C:\KKuTu-master\Server\lib\node_modules\passport-discord\node_modules\passport-oauth2\lib\strategy.js:358:12)
    at Strategy.OAuth2Strategy._createOAuthError (C:\KKuTu-master\Server\lib\node_modules\passport-discord\node_modules\passport-oauth2\lib\strategy.js:405:16)
    at C:\KKuTu-master\Server\lib\node_modules\passport-discord\node_modules\passport-oauth2\lib\strategy.js:175:45
    at C:\KKuTu-master\Server\lib\node_modules\oauth\lib\oauth2.js:191:18
    at passBackControl (C:\KKuTu-master\Server\lib\node_modules\oauth\lib\oauth2.js:132:9)
    at IncomingMessage.<anonymous> (C:\KKuTu-master\Server\lib\node_modules\oauth\lib\oauth2.js:157:7)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
이런 오류가 나네요ㅠ

**Comment by lshqqytiger** [comment]
디스코드 API 설정이나 npm 모듈 쪽이 잘못 된거 같기도 한데 이런 경우는 처음 보네요.

**Comment by qkrehddls** [comment]
흠 passport 버전을 내려볼까요 ㅠ

**Comment by qkrehddls** [comment]
네이버 로그인에서도 같은 문제가 발생하네요
[https://imgur.com/a/dM2mKdB](url)
위 사진과 같이 설정은 정상적으로 되있는데 
네이버에서는 Cannot GET /oauth2.0/authorize 오류가 발생하네요

**Comment by qkrehddls** [comment]
구글 로그인도 같은 문제가 발생하네요
Cannot GET /login/google/callback&scope=profile&client_id=(가림)-(가림).apps.googleusercontent.com

**Comment by qkrehddls** [comment]
리버스 프록시를 거치지 않고 로그인하니 되네요 해결되었으니 닫습니다
