### ISSUE TITLE
게임 서버가 열리지 않습니다

### ISSUE THREAD

**Issue by fevertimes1009** [JJoriping/KKuTu#776]
[2020-11-27 09:55:43] &lt;&lt; KKuTu Server:8496 >>
[2020-11-27 09:55:44] &lt;&lt; KKuTu Web >>
[2020-11-27 09:55:47] OAuth Strategy naver is not loaded [2020-11-27 09:55:47] OAuth2Strategy requires a clientID option
[2020-11-27 09:55:47] OAuth Strategy facebook is not loaded
[2020-11-27 09:55:47] OAuth2Strategy requires a clientID option
[2020-11-27 09:55:47] OAuth Strategy google is not loaded [2020-11-27 09:55:47] OAuth2Strategy requires a clientID option
[2020-11-27 09:55:48] OAuth Strategy twitter is not loaded [2020-11-27 09:55:48] OAuthStrategy requires a consumerKey option
[2020-11-27 09:55:48] OAuth Strategy kakao is not loaded [2020-11-27 09:55:48] OAuth2Strategy requires a clientID option
[2020-11-27 09:55:48] OAuth Strategy discord is not loaded [2020-11-27 09:55:48] OAuth2Strategy requires a clientID option
[2020-11-27 09:55:48] OAuth Strategy twitch is not loaded [2020-11-27 09:55:48] OAuth2Strategy requires a clientID option
[2020-11-27 09:55:48] OAuth Strategy github is not loaded [2020-11-27 09:55:48] OAuth2Strategy requires a clientID option
[2020-11-27 09:55:48] OAuth Strategy line is not loaded [2020-11-27 09:55:48] OAuth2Strategy requires a clientID option
[2020-11-27 09:55:48] OAuth Strategy instagram is not loaded [2020-11-27 09:55:48] OAuth2Strategy requires a clientID option
[2020-11-27 09:55:48] OAuth Strategy spotify is not loaded [2020-11-27 09:55:48] OAuth2Strategy requires a clientID option
[2020-11-27 09:55:48] Game server #1 has an error: Error: connect ECONNREFUSED 127.0.0.2:8080
[2020-11-27 09:55:48] Game server #1 closed: 1006

포트 8090으로도 바꿔보고 8080, 8496, 80 포트 사용하는 프로세스 모두 종료해봤는데 해결되지 않습니다

**Comment by kdhkr** [comment]
먼저 끄투 게임 서버부터 가동하시고 그 다음에 웹 서버를 가동하셔야 합니다.

**Comment by pink-flower** [comment]
pg 모듈을 v8.0.3 이상으로 업데이트 해 보세요.

**Comment by fevertimes1009** [comment]
CMD를 사용해서 서버를 가동하지 않고 github에 있는 레포지터리랑 postgresql, redis, node.js를 다운받아서 직접 수동하고 연결해서 레포지터리에 있는 run.bat 파일을 이용하여 서버를 열었습니다. 이 방법에서는 게임 서버를 어떻게 구동하나요?

**Comment by kdhkr** [comment]
ECONNREFUSED는 연결이 거부되었을 경우 발생하는 오류입니다. 대부분의 경우, 게임 서버가 정상적으로 구동되지 않아 발생하는 오류입니다. 웹 서버가 게임 서버보다 먼저 열릴 경우, 웹 서버가 열린 시점에 게임 서버로 요청을 보낼 수 없어 게임 서버가 열리지 않은 것처럼 표시됩니다.

이에 따라, 레프지토리에 포함된 구동기(`./Server/run.bat`)를 사용하시는 것보다 아래와 같이 명령어를 입력하여 차례차례 구동하는 것을 권장합니다.

(Windows 기준, `./Server` 디렉토리에서 실행해주세요.)
(게임 서버) `node lib\Game\cluster.js 0 1`
(웹 서버) `node lib\Web\cluster.js 1`

아울러, 이미 존재하는 이슈들을 참고해주시면 더욱 빠르게 답변을 받을 수 있습니다.

**Comment by fevertimes1009** [comment]
전에 구동기를 사용하지 않고 직접 node lib\Game\cluster.js 0 1 를 이용해서 게임 서버를 구동하려고 했습니다. 계속 오류가 떴는데 이번에도 같은 오류가 뜨네요 
[2020-11-27 10:36:04] << KKuTu Server:8496 >>
[2020-11-27 10:36:05] Error on ws: Error: bind EADDRINUSE null:8496

뭔지 모르겠어서 웹서핑도 해봤으나 이런 종류의 오류는 찾을 수 없었습니다. 어떤 오류인가요 ㅠㅠ

**Comment by kdhkr** [comment]
8496 포트가 사용 중입니다. 다른 프로세스를 종료하고 다시 시도해주세요.

**Comment by fevertimes1009** [comment]
C:\Users\김**>taskkill /f /pid 8496
오류: 프로세스 "8496"을(를) 찾을 수 없습니다.

**Comment by kdhkr** [comment]
실행하신 명령어는 8496 포트를 사용하고 있는 프로세스를 끝내는 것이 아닌, PID "8496"을 가진 프로세스를 끝내는 명령어입니다.
명령어를 다시 확인해보시기 바랍니다.

**Comment by fevertimes1009** [comment]
제가 실수했네요 방금 두 가지 방법을 시도해보았습니다
제가 사용했던 run 배치파일을 직접 구동하기 전에 cmd에서 node lib/Game/cluster.js 0 1을 입력했을 때 다음 명령을 입력하지 못하도록 나왔습니다 다음 node lib/Web/cluster.js 1을 어떻게 명령 내릴지 모르겠습니다

다음 방법으로는 아예 처음부터 cmd를 사용하여 다시 해봤습니다
ubuntu@ip-172-31-14-0:~/KKuTu/Server$ node lib/Game/cluster.js 0 1
module.js:674
    throw err;
    ^

SyntaxError: /home/ubuntu/KKuTu/Server/lib/sub/global.json: Unexpected token i in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (module.js:671:27)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/ubuntu/KKuTu/Server/lib/const.js:19:14)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
이런 오류코드가 뜹니다.

**Comment by kdhkr** [comment]
죄송하지만, 더 이상의 답변은 어려울 것 같습니다. 이미 똑같은 이슈가 수도 없이 많으며, global.json 구문 오류는 끄투 자체의 문제점이 아닙니다. #689 참고해주세요.

**Comment by fevertimes1009** [comment]
일단 가장 큰 문제인 8496 포트 문제는 해결했으니 이슈 닫겠습니다
도와주셔서 감사합니다 새로 생긴 문제는 다른 이슈로 올리겠습니다.

**Comment by lshqqytiger** [comment]
cmd를 두개를 켜셔야 합니다.
node lib/Game/cluster.js 0 1 한번
node lib/Web/cluster.js 1 한번

**Comment by fevertimes1009** [comment]
cmd 두 개 켜서 해봤는데 안 됐습니다 컴퓨터가 후져서 그런 것 같아요 성능 좋은 컴퓨터로 하니까 잘만 되더라구요 도움 주셔서 감사합니다:)
