### ISSUE TITLE
게임 시작 버튼

### ISSUE THREAD

**Issue by fevertimes1009** [JJoriping/KKuTu#778]
게임시작 버튼이 눌리지 않아요. 게임 서버가 구동중이지 않을 때라고 들었습니다 .
ubuntu@ip-172-31-1-98:~/KKuTu/Server$ node lib/Game/cluster.js 0 1
[2020-11-27 08:12:33] Error from Redis: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
[2020-11-27 08:12:33] Run with no-redis mode.
[2020-11-27 08:12:33] Master DB is ready.
_**[2020-11-27 08:12:33] Error on ws: Error: listen EADDRINUSE :::8080**_
[2020-11-27 08:12:34] << KKuTu Server:8496 >>
[2020-11-27 08:12:34] Error from Redis: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
[2020-11-27 08:12:34] Run with no-redis mode.
[2020-11-27 08:12:34] DB is ready.
볼드글씨에 오류있는 것 같습니다.

(+ Error on ws: Error: bind EADDRINUSE null:8496
이 오류도 같이 뜹니다. 8080, 8496포트 사용중인 프로세스도 없습니다
이 오류코드가 같은 포트 사용하는 프로세스가 존재한다는 뜻 아니었나요?
http://3.35.238.119/
주소입니다

**Comment by fevertimes1009** [comment]
+ Error on ws: Error: bind EADDRINUSE null:8496
이 오류도 같이 뜹니다. 8080, 8496포트 사용중인 프로세스도 없습니다
http://3.35.238.119/
주소입니다.

**Comment by qkrehddls** [comment]
Redis 설치 하셨나요?

**Comment by fevertimes1009** [comment]
redis 설치를 cmd 통해서 어떻게 해야하는지 모르겠습니다

**Comment by qkrehddls** [comment]
1: sudo apt update
2: sudo apt upgrade
3: sudo apt install redis-server

**Comment by fevertimes1009** [comment]
ubuntu@ip-172-31-1-98:~/KKuTu/Server$ node lib/Game/cluster.js 0 1
[2020-11-27 09:11:19] Master DB is ready.
[2020-11-27 09:11:19] Error on ws: Error: listen EADDRINUSE :::8080
[2020-11-27 09:11:19] << KKuTu Server:8496 >>
[2020-11-27 09:11:19] Error on ws: Error: bind EADDRINUSE null:8496
[2020-11-27 09:11:19] DB is ready.

레디스 설치했습니다. 감사합니다
근데 아직도 시작버튼은 안 눌립니다 ㅠㅠ

**Comment by qkrehddls** [comment]
sudo lsof -i :8080

**Comment by qkrehddls** [comment]
sudo lsof -i :8496

**Comment by fevertimes1009** [comment]
ubuntu@ip-172-31-1-98:~/KKuTu/Server$ sudo lsof -i :8080
COMMAND   PID   USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
node    11636 ubuntu   14u  IPv6  39893      0t0  TCP *:http-alt (LISTEN)
node    11636 ubuntu   15u  IPv6  40702      0t0  TCP ip-172-31-1-98:http-alt->localhost:55846 (ESTABLISHED)
node    11747   root   14u  IPv4  40701      0t0  TCP localhost:55846->ip-172-31-1-98:http-alt (ESTABLISHED)
ubuntu@ip-172-31-1-98:~/KKuTu/Server$ taskkill /f /pid 11747
taskkill: command not found
ubuntu@ip-172-31-1-98:~/KKuTu/Server$ sudo lsof -i :8496
COMMAND   PID   USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
node    12775 ubuntu   16u  IPv6  47451      0t0  TCP *:8496 (LISTEN)

**Comment by qkrehddls** [comment]
reboot 해서 재부팅 하시고 다시 끄투 서버를 켜보세요

**Comment by fevertimes1009** [comment]
shutdown -r 맞나요?

**Comment by qkrehddls** [comment]
그냥 reboot 하셔도 됩니다

**Comment by fevertimes1009** [comment]
재부팅했는데도 
ubuntu@ip-172-31-1-98:~/KKuTu/Server$ node lib/Game/cluster.js 0 1
[2020-11-27 09:48:03] Master DB is ready.
[2020-11-27 09:48:03] Error on ws: Error: listen EADDRINUSE :::8080
[2020-11-27 09:48:04] << KKuTu Server:8496 >>
[2020-11-27 09:48:04] Error on ws: Error: bind EADDRINUSE null:8496
[2020-11-27 09:48:04] DB is ready.
이 오류코드 계속 나옵니다.

**Comment by qkrehddls** [comment]
sudo lsof -i :8080

**Comment by fevertimes1009** [comment]
ubuntu@ip-172-31-1-98:~/KKuTu/Server$ sudo lsof -i :8080
COMMAND   PID   USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
node    11636 ubuntu   14u  IPv6  39893      0t0  TCP *:http-alt (LISTEN)
node    11636 ubuntu   15u  IPv6  40702      0t0  TCP ip-172-31-1-98:http-alt->localhost:55846 (ESTABLISHED)
node    11747   root   14u  IPv4  40701      0t0  TCP localhost:55846->ip-172-31-1-98:http-alt (ESTABLISHED)
ubuntu@ip-172-31-1-98:~/KKuTu/Server$ node lib/Game/cluster.js 0 1

**Comment by qkrehddls** [comment]
kill -9 11636
kill -9 11747

**Comment by fevertimes1009** [comment]
Game 서버는 잘 구동됩니다
Web 서버가 문제가 생겼습니다.

Error: bind EADDRINUSE null:80
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at listenOnMasterHandle (net.js:1427:16)
    at rr (internal/cluster/child.js:121:12)
    at Worker.send (internal/cluster/child.js:88:7)
    at process.onInternalMessage (internal/cluster/utils.js:42:8)
    at emitTwo (events.js:131:20)
    at process.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)

80 포트를 사용하고 있다고 해서 
ubuntu@ip-172-31-1-98:~/KKuTu/Server$ sudo lsof -i :80
COMMAND   PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
node    11741 root   13u  IPv6  40710      0t0  TCP *:http (LISTEN)
11741을 kill -9 를 사용해서 죽이려고 했는데
-bash: kill: (11741) - Operation not permitted
이 오류가 뜹니다.

**Comment by lshqqytiger** [comment]
sudo kill -9 11741로 해보세요.

**Comment by fevertimes1009** [comment]
포트 문제는 해결됐습니다 도와주신 두 분께 정말 감사드립니다.
