### ISSUE TITLE
웹 서버 오픈 에러

### ISSUE THREAD

**Issue by fevertimes1009** [JJoriping/KKuTu#779]
ubuntu@ip-172-31-1-98:~/KKuTu/Server$ sudo node lib/Web/cluster.js 1
[2020-11-27 11:18:59] << KKuTu Web >>
[2020-11-27 11:18:59] OAuth Strategy naver is not loaded
[2020-11-27 11:18:59] OAuth2Strategy requires a clientID option
[2020-11-27 11:18:59] OAuth Strategy facebook is not loaded
[2020-11-27 11:18:59] OAuth2Strategy requires a clientID option
[2020-11-27 11:18:59] OAuth Strategy google is not loaded
[2020-11-27 11:18:59] OAuth2Strategy requires a clientID option
[2020-11-27 11:18:59] OAuth Strategy twitter is not loaded
[2020-11-27 11:18:59] OAuthStrategy requires a consumerKey option
[2020-11-27 11:18:59] OAuth Strategy kakao is not loaded
[2020-11-27 11:18:59] OAuth2Strategy requires a clientID option
[2020-11-27 11:18:59] OAuth Strategy discord is not loaded
[2020-11-27 11:18:59] OAuth2Strategy requires a clientID option
[2020-11-27 11:18:59] OAuth Strategy twitch is not loaded
[2020-11-27 11:18:59] OAuth2Strategy requires a clientID option
[2020-11-27 11:18:59] OAuth Strategy github is not loaded
[2020-11-27 11:18:59] OAuth2Strategy requires a clientID option
[2020-11-27 11:18:59] OAuth Strategy line is not loaded
[2020-11-27 11:18:59] OAuth2Strategy requires a clientID option
[2020-11-27 11:18:59] OAuth Strategy instagram is not loaded
[2020-11-27 11:18:59] OAuth2Strategy requires a clientID option
[2020-11-27 11:18:59] OAuth Strategy spotify is not loaded
[2020-11-27 11:18:59] OAuth2Strategy requires a clientID option
[2020-11-27 11:18:59] DB is ready.
/home/ubuntu/KKuTu/Server/lib/node_modules/ws/lib/WebSocket.js:360
      else throw new Error('not opened');
           ^

Error: not opened
    at WebSocket.send (/home/ubuntu/KKuTu/Server/lib/node_modules/ws/lib/WebSocket.js:360:18)
    at /home/ubuntu/KKuTu/Server/lib/Web/main.js:129:26
    at Array.forEach (<anonymous>)
    at Timeout._onTimeout (/home/ubuntu/KKuTu/Server/lib/Web/main.js:128:15)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
Worker 14071 died
ubuntu@ip-172-31-1-98:~/KKuTu/Server$

**Comment by qkrehddls** [comment]
Node.js 버전이 몇인가요?

**Comment by fevertimes1009** [comment]
버전 어떻게 확인하나요?

**Comment by qkrehddls** [comment]
node -v

**Comment by fevertimes1009** [comment]
v8.10.0 입니다

**Comment by lshqqytiger** [comment]
게임 서버가 응답하지 않는 것 같습니다.
문제가 발생한 [main.js의 해당 부분](https://github.com/JJoriping/KKuTu/blob/8454e7b85f2389815642645ae4b2e72deec4f94e/Server/lib/Web/main.js#L127)은 게임 서버로 ```{"type":"seek"}```를 전송하는 내용입니다.

**Comment by fevertimes1009** [comment]
main.js 파일을 찾아서 수정하면 되나요?

**Comment by qkrehddls** [comment]
Node.js를 업데이트 해보세요
sudo npm cache clean -f 
sudo npm install -g n 
sudo n stable

**Comment by fevertimes1009** [comment]
ubuntu@ip-172-31-1-98:~/KKuTu/Server$ sudo npm cache clean -f
npm WARN using --force I sure hope you know what you are doing.
ubuntu@ip-172-31-1-98:~/KKuTu/Server$ sudo npm install -g n
▄ ╢░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟

sudo npm cache clean -f 이후 sudo npm install -g n입력시
저 상태에서 멈춥니다. ▄이 기호가 계속 뱅글뱅글 돌아가기만 해요

**Comment by lshqqytiger** [comment]
아뇨 수정해서 될 문제는 아닌거 같습니다.

**Comment by fevertimes1009** [comment]
ubuntu@ip-172-31-1-98:~/KKuTu/Server$ sudo npm install -g n
▄ ╢░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
npm ERR! Linux 5.4.0-1029-aws
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "n"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! syscall connect

npm ERR! network connect ETIMEDOUT 104.16.18.35:443
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/KKuTu/Server/npm-debug.log



ubuntu@ip-172-31-1-98:~/KKuTu$ sudo npm install -g n
npm ERR! Linux 5.4.0-1029-aws
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "n"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! syscall connect

npm ERR! network connect ETIMEDOUT 104.16.21.35:443
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/KKuTu/npm-debug.log




ubuntu@ip-172-31-1-98:/$ sudo npm install -g n
npm ERR! Linux 5.4.0-1029-aws
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "n"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! syscall connect

npm ERR! network connect ETIMEDOUT 104.16.17.35:443
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     /npm-debug.log

**Comment by qkrehddls** [comment]
인스턴스를 삭제하고 다시 생성해서 다시 세팅해보세요

**Comment by qkrehddls** [comment]
그리고 Node.js는 아래 커맨드로 설치해보세요

curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
sudo apt-get install -y nodejs

**Comment by fevertimes1009** [comment]
방금 인스턴스 삭제하고 키페어도 삭제해서 완전 처음부터 다시 해봤는데 오류코드는 조금 달라졌지만 그래도 안 되는 건 마찬가지입니다 ㅠㅠ
ubuntu@ip-172-31-38-130:~/KKuTu/Server$ sudo node lib/Web/cluster.js 1
[2020-11-29 10:08:44] << KKuTu Web >>
[2020-11-29 10:08:44] OAuth Strategy naver is not loaded
[2020-11-29 10:08:44] OAuth2Strategy requires a clientID option
[2020-11-29 10:08:44] OAuth Strategy facebook is not loaded
[2020-11-29 10:08:44] OAuth2Strategy requires a clientID option
[2020-11-29 10:08:44] OAuth Strategy google is not loaded
[2020-11-29 10:08:44] OAuth2Strategy requires a clientID option
[2020-11-29 10:08:44] OAuth Strategy twitter is not loaded
[2020-11-29 10:08:44] OAuthStrategy requires a consumerKey option
[2020-11-29 10:08:44] OAuth Strategy kakao is not loaded
[2020-11-29 10:08:44] OAuth2Strategy requires a clientID option
[2020-11-29 10:08:44] OAuth Strategy discord is not loaded
[2020-11-29 10:08:44] OAuth2Strategy requires a clientID option
[2020-11-29 10:08:44] OAuth Strategy twitch is not loaded
[2020-11-29 10:08:44] OAuth2Strategy requires a clientID option
[2020-11-29 10:08:44] OAuth Strategy github is not loaded
[2020-11-29 10:08:44] OAuth2Strategy requires a clientID option
[2020-11-29 10:08:44] OAuth Strategy line is not loaded
[2020-11-29 10:08:44] OAuth2Strategy requires a clientID option
[2020-11-29 10:08:44] OAuth Strategy instagram is not loaded
[2020-11-29 10:08:44] OAuth2Strategy requires a clientID option
[2020-11-29 10:08:44] OAuth Strategy spotify is not loaded
[2020-11-29 10:08:44] OAuth2Strategy requires a clientID option
[2020-11-29 10:08:44] DB is ready.
/home/ubuntu/KKuTu/Server/lib/node_modules/ws/lib/WebSocket.js:344
      else throw new Error('not opened');
           ^

Error: not opened
    at WebSocket.send (/home/ubuntu/KKuTu/Server/lib/node_modules/ws/lib/WebSocket.js:344:18)
    at /home/ubuntu/KKuTu/Server/lib/Web/main.js:129:26
    at Array.forEach (<anonymous>)
    at Timeout._onTimeout (/home/ubuntu/KKuTu/Server/lib/Web/main.js:128:15)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
Worker 26319 died

**Comment by qkrehddls** [comment]
node -v

**Comment by fevertimes1009** [comment]
v12.20.0

**Comment by fevertimes1009** [comment]
node lib/Web/cluster.js 1 로 사용하면 Error: bind EACCES null:80 에러가 떠서 
sudo node lib/Web/cluster.js 1을 사용했는데 이게 문제가 되는 건 아니겠죠?

**Comment by qkrehddls** [comment]
네

**Comment by qkrehddls** [comment]
Ubuntu 버전이 몇인가요?

**Comment by fevertimes1009** [comment]
Ubuntu 18.04.5 LTS \n \l

**Comment by qkrehddls** [comment]
Amazon Linux 2로 다시 인스턴스 재 생성 해보시고 Node.js는 아래와 같이 설치해보세요

yum update -y
reboot
curl -sL https://rpm.nodesource.com/setup_12.x | sudo bash -
sudo yum install nodejs -y

**Comment by fevertimes1009** [comment]
ubuntu@ip-172-31-38-130:~/KKuTu$ yum update -y
You need to be root to perform this command.
ubuntu@ip-172-31-38-130:~/KKuTu$ sudo passwd root
Enter new UNIX password:
Retype new UNIX password:
passwd: password updated successfully
ubuntu@ip-172-31-38-130:~/KKuTu$ su -
Password:
root@ip-172-31-38-130:~# yum update -y
There are no enabled repos.
 Run "yum repolist all" to see the repos you have.
 You can enable repos with yum-config-manager --enable <repo>

**Comment by qkrehddls** [comment]
Ubuntu로 재생성 하신거 같은데요?

**Comment by fevertimes1009** [comment]
root 로 가야한대서 root 비번 설정하고 root로 이동해서 yum update -y치니 저 에러가 떠요

**Comment by qkrehddls** [comment]
그게 아니고 Ubuntu로 인스턴스를 재생성 하신거같은데요?

**Comment by fevertimes1009** [comment]
아 지금 linux 2로 생성하고 다운 했습니다

**Comment by kdhkr** [comment]
@qkrehddls 도대체 Amazon Linux를 강요하시는 이유를 모르겠습니다. Amazon Linux만 지원하는 것도 아니고요.

**Comment by qkrehddls** [comment]
AWS에 제일 잘 맞는 OS라고 저는 생각을 해서 추천 드렸습니다 :)
