### ISSUE TITLE
제가 해보다가 진짜 뭘 고쳐야하는 오류인지 모르겠어서요

### ISSUE THREAD

**Issue by ghost** [JJoriping/KKuTu#784]
Game server #1 has an error: Error: connect ECONNREFUSED 127.0.0.2:8080
 Game server #1 closed: 1006

**Comment by qkrehddls** [comment]
전체 로그를 보여주실수 있나요?

**Comment by world011** [comment]
환영합니다.
[2020-12-19 19:26:26] &lt;&lt; KKuTu Web >>
[2020-12-19 19:26:26] &lt;&lt; KKuTu Server:8496 >>
[2020-12-19 19:26:27] OAuth Strategy naver is not loaded
[2020-12-19 19:26:27] OAuth2Strategy requires a clientID option
[2020-12-19 19:26:27] OAuth Strategy facebook is not loaded [2020-12-19 19:26:27] OAuth2Strategy requires a clientID option
[2020-12-19 19:26:27] OAuth Strategy google is not loaded [2020-12-19 19:26:27] OAuth2Strategy requires a clientID option
[2020-12-19 19:26:28] OAuth Strategy twitter is not loaded [2020-12-19 19:26:28] OAuthStrategy requires a consumerKey option
[2020-12-19 19:26:28] OAuth Strategy kakao is not loaded [2020-12-19 19:26:28] OAuth2Strategy requires a clientID option
[2020-12-19 19:26:28] OAuth Strategy discord is not loaded [2020-12-19 19:26:28] OAuth2Strategy requires a clientID option
[2020-12-19 19:26:28] OAuth Strategy twitch is not loaded [2020-12-19 19:26:28] OAuth2Strategy requires a clientID option
[2020-12-19 19:26:28] OAuth Strategy github is not loaded [2020-12-19 19:26:28] OAuth2Strategy requires a clientID option
[2020-12-19 19:26:28] OAuth Strategy line is not loaded [2020-12-19 19:26:28] OAuth2Strategy requires a clientID option
[2020-12-19 19:26:28] OAuth Strategy instagram is not loaded [2020-12-19 19:26:28] OAuth2Strategy requires a clientID option
[2020-12-19 19:26:28] OAuth Strategy spotify is not loaded [2020-12-19 19:26:28] OAuth2Strategy requires a clientID option
[2020-12-19 19:26:30] Game server #1 has an error: Error: connect ECONNREFUSED 127.0.0.2:8080
[2020-12-19 19:26:30] Game server #1 closed: 1006

**Comment by qkrehddls** [comment]
cmd 창을 2개 띄우시고 첫번째로 node lib/Game/cluster.js 0 1 를 실행해보시고 그 다음에 node lib/Web/cluster.js 1 를 실행해보세요

**Comment by world011** [comment]
1번째는:C:\Users\USER>node lib/Game/cluster.js 0 1
internal/modules/cjs/loader.js:1017
  throw err;
  ^

Error: Cannot find module 'C:\Users\USER\lib\Game\cluster.js'
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1014:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:884:27)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)[39m
[90m    at internal/main/run_main_module.js:17:47[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: []
} 이렇게 나오고
두번째는:C:\Users\USER>node lib/Web/cluster.js 1
internal/modules/cjs/loader.js:1017
  throw err;
  ^

Error: Cannot find module 'C:\Users\USER\lib\Web\cluster.js'
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1014:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:884:27)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)[39m
[90m    at internal/main/run_main_module.js:17:47[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: []
} 이렇게 뜹니다

**Comment by qkrehddls** [comment]
끄투 파일이 있는 디렉터리에서 실행하셔야 됩니다

**Comment by kdhkr** [comment]
@world011 서버 디렉토리 내에서 해당 명령어를 실행하셔야 합니다.

**Comment by kdhkr** [comment]
+ 해당 문제는 최신 버전의 Docker 지원 패치로 인하여 발생하는 문제입니다.
계속해서 문제가 발생한다면 #697을 참고하여 패치를 진행해주시기 바랍니다.

**Comment by world011** [comment]
원래 구버전의 레포로 했고,그 방법을 써봤지만 똑같은 오류가 뜹니다.

**Comment by msrykkutuzard** [comment]
혹시나 그런 오류가 생긴다면 저한테 DM 주시기 바랍니다. 저는 저 오류를 고칠줄 압니다.

**Comment by msrykkutuzard** [comment]
수박애플#4628로 DM 주시기 바랍니다.
