### ISSUE TITLE
끄투 온라인 오류 해결 법좀 알려주세용..

### ISSUE THREAD

**Issue by rroma995** [JJoriping/KKuTu#789]
unrecognized win32 error code: 123psql: 오류: {C:/Users/ansh6/Desktop/KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2}/db
.sql: Invalid argument 라고 CMD 에 뜹니다.

**Comment by Carlo-Woo** [comment]
invalid argument 오류는 보통 파일을 저장할 때의 경로 혹은 파일 명에 들어가면 안되는 문자가 들어간 경우 생기는 에러를 뜻하는데... ```
{C:/Users/ansh6/Desktop/KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2}/db
.sql: Invalid argument
``` 의 중괄호는 뭐죠?

**Comment by Carlo-Woo** [comment]
invalid argument 오류는 보통 파일을 저장할 때의 경로 혹은 파일 명에 들어가면 안되는 문자가 들어간 경우 생기는 에러를 뜻하는데... ```
{C:/Users/ansh6/Desktop/KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2}/db
.sql: Invalid argument``` 의 중괄호는 뭐죠?

**Comment by lshqqytiger** [comment]
쪼리핑님 블로그의 
```
psql -U "postgres" -d "main" -f "(SQL 파일 경로)"
```
이 부분을 그대로 적다가 문제가 생긴 것으로 보입니다.
중괄호는 블로그의 기울어진 글씨 때문에 괄호를 중괄호로 착각하신 것으로 보이구요.
```
psql -U "postgres" -d "main" -f "C:/Users/ansh6/Desktop/KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2/db.sql"
```
이렇게 다시 시도해보시기 바랍니다.

**Comment by rroma995** [comment]
환영합니다.
[2020-12-30 14:50:08] &lt;&lt; KKuTu Web >>
[2020-12-30 14:50:08] &lt;&lt; KKuTu Server:8496 >>
[2020-12-30 14:50:08] OAuth Strategy naver is not loaded [2020-12-30 14:50:08] OAuth2Strategy requires a clientID option
[2020-12-30 14:50:08] OAuth Strategy facebook is not loaded [2020-12-30 14:50:08] OAuth2Strategy requires a clientID option
[2020-12-30 14:50:08] OAuth Strategy google is not loaded [2020-12-30 14:50:08] OAuth2Strategy requires a clientID option
[2020-12-30 14:50:08] OAuth Strategy twitter is not loaded [2020-12-30 14:50:08] OAuthStrategy requires a consumerKey option
[2020-12-30 14:50:08] OAuth Strategy kakao is not loaded [2020-12-30 14:50:08] OAuth2Strategy requires a clientID option
[2020-12-30 14:50:08] OAuth Strategy discord is not loaded [2020-12-30 14:50:08] OAuth2Strategy requires a clientID option
[2020-12-30 14:50:08] OAuth Strategy twitch is not loaded [2020-12-30 14:50:08] OAuth2Strategy requires a clientID option
[2020-12-30 14:50:08] OAuth Strategy github is not loaded [2020-12-30 14:50:08] OAuth2Strategy requires a clientID option
[2020-12-30 14:50:08] OAuth Strategy line is not loaded [2020-12-30 14:50:08] OAuth2Strategy requires a clientID option
[2020-12-30 14:50:08] OAuth Strategy instagram is not loaded [2020-12-30 14:50:08] OAuth2Strategy requires a clientID option
[2020-12-30 14:50:08] OAuth Strategy spotify is not loaded [2020-12-30 14:50:08] OAuth2Strategy requires a clientID option
[2020-12-30 14:50:08] Game server #1 has an error: Error: connect ECONNREFUSED 127.0.0.2:8080
[2020-12-30 14:50:08] Game server #1 closed: 1006 라고 뜨면서 안됀다는데 어떻게 해야돼는건가요?

**Comment by lshqqytiger** [comment]
이미 내용이 완전히 일치하는 이슈가 있습니다.
#776

**Comment by rroma995** [comment]
저걸 봐도 이해가 안갑니다.

**Comment by qkrehddls** [comment]
윈도우 환경이시라면 서버 디렉토리 안에서 CMD창을 2개 띄우시고 첫번째로 node lib/Game/cluster.js 0 1 를 입력하시고 두번째로 node lib/Web/cluster.js 1를 입력해서 실행해보세요

**Comment by rroma995** [comment]
cmd 에 하면 internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'C:\Windows\system32\lib\Game\cluster.js'
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:725:27)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)[39m
[90m    at internal/main/run_main_module.js:17:47[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: []
} 이오류가 뜹니다.

**Comment by qkrehddls** [comment]
서버 디레터리 안에서 실행하셔야합니다

**Comment by lshqqytiger** [comment]
그 오류와 똑같은 내용이 이슈 또한 존재합니다.
#784

**Comment by rroma995** [comment]
도저희 시도를 해봐도 안돼네요.. 어떻게 도와주실수는 없슬까요?

**Comment by qkrehddls** [comment]
cmd상에서 경로를 이동하시는 방법을 구글에 검색해보세요

**Comment by rroma995** [comment]
![2311232](https://user-images.githubusercontent.com/65393767/103334755-f67f3580-4ab5-11eb-8fbd-11d84c376a00.PNG)
이렇게 뜹니다

**Comment by lshqqytiger** [comment]
```
cd Server
```

**Comment by rroma995** [comment]
![15112111](https://user-images.githubusercontent.com/65393767/103335214-b5882080-4ab7-11eb-8be8-d93eaad6ee5b.PNG)
이건 어떤 오류인가요?

**Comment by qkrehddls** [comment]
Redis를 설치하셔야합니다

**Comment by rroma995** [comment]
redis 는 어디서 설치하나여?

**Comment by lshqqytiger** [comment]
기존 이슈를 찾아본 후 질문 바랍니다.
#661

**Comment by rroma995** [comment]
다 했는데도 안됍니다...

**Comment by qkrehddls** [comment]
어떻게 오류가 발생하는지 로그를 알려주실수 있나요?

**Comment by rroma995** [comment]
위에 형상이 게속 뜨고 [2020-12-30 14:50:08] << KKuTu Web >>
[2020-12-30 14:50:08] << KKuTu Server:8496 >>
[2020-12-30 14:50:08] OAuth Strategy naver is not loaded [2020-12-30 14:50:08] OAuth2Strategy requires a clientID option
[2020-12-30 14:50:08] OAuth Strategy facebook is not loaded [2020-12-30 14:50:08] OAuth2Strategy requires a clientID option
[2020-12-30 14:50:08] OAuth Strategy google is not loaded [2020-12-30 14:50:08] OAuth2Strategy requires a clientID option
[2020-12-30 14:50:08] OAuth Strategy twitter is not loaded [2020-12-30 14:50:08] OAuthStrategy requires a consumerKey option
[2020-12-30 14:50:08] OAuth Strategy kakao is not loaded [2020-12-30 14:50:08] OAuth2Strategy requires a clientID option
[2020-12-30 14:50:08] OAuth Strategy discord is not loaded [2020-12-30 14:50:08] OAuth2Strategy requires a clientID option
[2020-12-30 14:50:08] OAuth Strategy twitch is not loaded [2020-12-30 14:50:08] OAuth2Strategy requires a clientID option
[2020-12-30 14:50:08] OAuth Strategy github is not loaded [2020-12-30 14:50:08] OAuth2Strategy requires a clientID option
[2020-12-30 14:50:08] OAuth Strategy line is not loaded [2020-12-30 14:50:08] OAuth2Strategy requires a clientID option
[2020-12-30 14:50:08] OAuth Strategy instagram is not loaded [2020-12-30 14:50:08] OAuth2Strategy requires a clientID option
[2020-12-30 14:50:08] OAuth Strategy spotify is not loaded [2020-12-30 14:50:08] OAuth2Strategy requires a clientID option
[2020-12-30 14:50:08] Game server #1 has an error: Error: connect ECONNREFUSED 127.0.0.2:8080
[2020-12-30 14:50:08] Game server #1 closed: 1006  가 계속 뜹니다.

**Comment by qkrehddls** [comment]
게임 서버를 먼저 키신게 맞나요?

**Comment by rroma995** [comment]
네네

**Comment by qkrehddls** [comment]
Server 폴더 안에 있는 run.bat로 실행하신건가요 아니면 CMD창 두개를 띄워서 실행하신건가요?

**Comment by rroma995** [comment]
Server 폴더 안에 있는 run.bat로 실행했습니다

**Comment by qkrehddls** [comment]
> 
> 
> 윈도우 환경이시라면 서버 디렉토리 안에서 CMD창을 2개 띄우시고 첫번째로 node lib/Game/cluster.js 0 1 를 입력하시고 두번째로 node lib/Web/cluster.js 1를 입력해서 실행해보세요

이거대로 해보세요

**Comment by rroma995** [comment]
그걸 하면 이게 개속 뜹니다.
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'C:\Users\ansh6\lib\Game\cluster.js'
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:725:27)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)[39m
[90m    at internal/main/run_main_module.js:17:47[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: []
}

**Comment by lshqqytiger** [comment]
```
C:\Users\ansh6\Desktop\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\Server
```
이 디렉토리에서 실행한 것이 맞나요?

**Comment by rroma995** [comment]
![awdawdawd](https://user-images.githubusercontent.com/65393767/103347919-c0ed4300-4adb-11eb-97e4-9037eae3237d.PNG)
라고뜨는데..

**Comment by lshqqytiger** [comment]
이건 그냥 8080 포트가 사용중인 것 같기도 한데 8080 포트를 사용하는 다른 프로세스는 없나요

**Comment by rroma995** [comment]
8080 를 사용하는 프로세스는 없습니다.

**Comment by Carlo-Woo** [comment]
없는데도 저 에러가 나타날 리가 없는데요?

**Comment by kdhkr** [comment]
> 
> 
> ![awdawdawd](https://user-images.githubusercontent.com/65393767/103347919-c0ed4300-4adb-11eb-97e4-9037eae3237d.PNG)
> 라고뜨는데..

게임 서버가 완전히 열리지 않았습니다.
게임 서버가 정상적으로 가동되면 콘솔에 `DB is ready.`이라는 문구가 출력됩니다.

**Comment by Carlo-Woo** [comment]
해결되셨으면 이슈 닫아주시기 바랍니다.
