### ISSUE TITLE
이슈 다 뒤져봤는데 해결법이 안 나와서요...

### ISSUE THREAD

**Issue by Carlo-Woo** [JJoriping/KKuTu#803]
서버를 열었더니만
`C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Game\master.js:581 } SyntaxError: Unexpected end of input at wrapSafe (node:internal/modules/cjs/loader:1024:16) at Module._compile (node:internal/modules/cjs/loader:1072:27) at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10) at Module.load (node:internal/modules/cjs/loader:973:32) at Function.Module._load (node:internal/modules/cjs/loader:813:14) at Module.require (node:internal/modules/cjs/loader:997:19) at require (node:internal/modules/cjs/helpers:92:18) at Object.&lt;anonymous> (C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Game\cluster.js:58:2) at Module._compile (node:internal/modules/cjs/loader:1108:14) at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)`
라며 오류가 뜹니다.
Unexpected end of input 오류는 괄호를 제대로 닫지 않아서 생기는 오류라는데
정작 master.js를 보니
(아래 코드는 master.js 572번째 줄부터 581번째 줄까지에요)
```
KKuTu.onClientClosed = function($c, code) {
	delete DIC[$c.id];
	if($c._error != 409) MainDB.users.update([ '_id', $c.id ]).set([ 'server', "" ]).on();
	if($c.profile) delete DNAME[$c.profile.title || $c.profile.name];
	if($c.socket) $c.socket.removeAllListeners();
	if($c.friends) narrateFriends($c.id, $c.friends, "off");
	KKuTu.publish('disconn', { id: $c.id });
	
	JLog.alert("Exit #" + $c.id);
}
```
라고 적혀있었습니다.
무슨 문제인 걸까요?

**Comment by qkrehddls** [comment]
Node.js 버전을 12같은 구버전으로 내려보세요

**Comment by Carlo-Woo** [comment]
다운로드하려고 찾아봤는데 자꾸 html 파일만 뜨는것같네요.. nodejs.org에서 받는 건 맞는거같은데 어디서 받는건가요?

**Comment by qkrehddls** [comment]
https://nodejs.org/dist/latest-v12.x/node-v12.20.2-x64.msi

**Comment by Carlo-Woo** [comment]
12버전을 설치해도
```
환영합니다.
C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Game\master.js:581 } SyntaxError: Unexpected end of input at wrapSafe (internal/modules/cjs/loader.js:915:16) at Module._compile (internal/modules/cjs/loader.js:963:27) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10) at Module.load (internal/modules/cjs/loader.js:863:32) at Function.Module._load (internal/modules/cjs/loader.js:708:14) at Module.require (internal/modules/cjs/loader.js:887:19) at require (internal/modules/cjs/helpers.js:74:18) at Object.&lt;anonymous> (C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Game\cluster.js:58:2) at Module._compile (internal/modules/cjs/loader.js:999:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
G: CLOSED WITH CODE 1
C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Game\master.js:581 } SyntaxError: Unexpected end of input at wrapSafe (internal/modules/cjs/loader.js:915:16) at Module._compile (internal/modules/cjs/loader.js:963:27) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10) at Module.load (internal/modules/cjs/loader.js:863:32) at Function.Module._load (internal/modules/cjs/loader.js:708:14) at Module.require (internal/modules/cjs/loader.js:887:19) at require (internal/modules/cjs/helpers.js:74:18) at Object.&lt;anonymous> (C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Game\cluster.js:58:2) at Module._compile (internal/modules/cjs/loader.js:999:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
G: CLOSED WITH CODE 1
[2021-02-15 13:04:34] &lt;&lt; KKuTu Web >>
[2021-02-15 13:04:35] OAuth Strategy naver loaded successfully.
[2021-02-15 13:04:35] OAuth Strategy facebook is not loaded [2021-02-15 13:04:35] Cannot find module 'C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\auth\auth_facebook.js' Require stack: - C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\routes\login.js - C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\main.js - C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\cluster.js
[2021-02-15 13:04:35] OAuth Strategy google is not loaded [2021-02-15 13:04:35] Cannot find module 'C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\auth\auth_google.js' Require stack: - C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\routes\login.js - C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\main.js - C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\cluster.js
[2021-02-15 13:04:35] OAuth Strategy twitter is not loaded [2021-02-15 13:04:35] Cannot find module 'C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\auth\auth_twitter.js' Require stack: - C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\routes\login.js - C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\main.js - C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\cluster.js
[2021-02-15 13:04:35] OAuth Strategy kakao is not loaded [2021-02-15 13:04:35] Cannot find module 'C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\auth\auth_kakao.js' Require stack: - C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\routes\login.js - C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\main.js - C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\cluster.js
[2021-02-15 13:04:35] OAuth Strategy discord loaded successfully.
[2021-02-15 13:04:35] OAuth Strategy twitch is not loaded [2021-02-15 13:04:35] Cannot find module 'C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\auth\auth_twitch.js' Require stack: - C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\routes\login.js - C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\main.js - C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\cluster.js
[2021-02-15 13:04:35] OAuth Strategy github is not loaded [2021-02-15 13:04:35] Cannot find module 'C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\auth\auth_github.js' Require stack: - C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\routes\login.js - C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\main.js - C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\cluster.js
[2021-02-15 13:04:35] OAuth Strategy line is not loaded [2021-02-15 13:04:35] Cannot find module 'C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\auth\auth_line.js' Require stack: - C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\routes\login.js - C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\main.js - C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\cluster.js
[2021-02-15 13:04:35] OAuth Strategy instagram is not loaded [2021-02-15 13:04:35] Cannot find module 'C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\auth\auth_instagram.js' Require stack: - C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\routes\login.js - C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\main.js - C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\cluster.js
[2021-02-15 13:04:35] OAuth Strategy spotify is not loaded [2021-02-15 13:04:35] Cannot find module 'C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\auth\auth_spotify.js' Require stack: - C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\routes\login.js - C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\main.js - C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\cluster.js
[2021-02-15 13:04:35] Game server #1 has an error: Error: connect ECONNREFUSED 127.0.0.2:8080
[2021-02-15 13:04:35] Game server #1 closed: 1006
[2021-02-15 13:04:35] Game server #1 has an error: Error: connect ECONNREFUSED 127.0.0.2:8090 [2021-02-15 13:04:35] Game server #1 closed: 1006
[2021-02-15 13:04:35] DB is ready.
[2021-02-15 13:04:35] Error when querying: SELECT * FROM kkutu_shop_desc WHERE TRUE [2021-02-15 13:04:35] Context: error: "kkutu_shop_desc" 이름의 릴레이션(relation)이 없습니다
```
라는 오류를 뿜으며 서버가 꺼집니다.. 어떻게 해야 하는 건가요?

**Comment by norhu1130** [comment]
원본 끄투 파일을 다운받아서 해보세요

**Comment by houlday755** [comment]
> 12버전을 설치해도
> 
> ```
> 환영합니다.
> C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Game\master.js:581 } SyntaxError: Unexpected end of input at wrapSafe (internal/modules/cjs/loader.js:915:16) at Module._compile (internal/modules/cjs/loader.js:963:27) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10) at Module.load (internal/modules/cjs/loader.js:863:32) at Function.Module._load (internal/modules/cjs/loader.js:708:14) at Module.require (internal/modules/cjs/loader.js:887:19) at require (internal/modules/cjs/helpers.js:74:18) at Object.&lt;anonymous> (C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Game\cluster.js:58:2) at Module._compile (internal/modules/cjs/loader.js:999:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
> G: CLOSED WITH CODE 1
> C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Game\master.js:581 } SyntaxError: Unexpected end of input at wrapSafe (internal/modules/cjs/loader.js:915:16) at Module._compile (internal/modules/cjs/loader.js:963:27) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10) at Module.load (internal/modules/cjs/loader.js:863:32) at Function.Module._load (internal/modules/cjs/loader.js:708:14) at Module.require (internal/modules/cjs/loader.js:887:19) at require (internal/modules/cjs/helpers.js:74:18) at Object.&lt;anonymous> (C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Game\cluster.js:58:2) at Module._compile (internal/modules/cjs/loader.js:999:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
> G: CLOSED WITH CODE 1
> [2021-02-15 13:04:34] &lt;&lt; KKuTu Web >>
> [2021-02-15 13:04:35] OAuth Strategy naver loaded successfully.
> [2021-02-15 13:04:35] OAuth Strategy facebook is not loaded [2021-02-15 13:04:35] Cannot find module 'C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\auth\auth_facebook.js' Require stack: - C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\routes\login.js - C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\main.js - C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\cluster.js
> [2021-02-15 13:04:35] OAuth Strategy google is not loaded [2021-02-15 13:04:35] Cannot find module 'C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\auth\auth_google.js' Require stack: - C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\routes\login.js - C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\main.js - C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\cluster.js
> [2021-02-15 13:04:35] OAuth Strategy twitter is not loaded [2021-02-15 13:04:35] Cannot find module 'C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\auth\auth_twitter.js' Require stack: - C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\routes\login.js - C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\main.js - C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\cluster.js
> [2021-02-15 13:04:35] OAuth Strategy kakao is not loaded [2021-02-15 13:04:35] Cannot find module 'C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\auth\auth_kakao.js' Require stack: - C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\routes\login.js - C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\main.js - C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\cluster.js
> [2021-02-15 13:04:35] OAuth Strategy discord loaded successfully.
> [2021-02-15 13:04:35] OAuth Strategy twitch is not loaded [2021-02-15 13:04:35] Cannot find module 'C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\auth\auth_twitch.js' Require stack: - C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\routes\login.js - C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\main.js - C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\cluster.js
> [2021-02-15 13:04:35] OAuth Strategy github is not loaded [2021-02-15 13:04:35] Cannot find module 'C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\auth\auth_github.js' Require stack: - C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\routes\login.js - C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\main.js - C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\cluster.js
> [2021-02-15 13:04:35] OAuth Strategy line is not loaded [2021-02-15 13:04:35] Cannot find module 'C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\auth\auth_line.js' Require stack: - C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\routes\login.js - C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\main.js - C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\cluster.js
> [2021-02-15 13:04:35] OAuth Strategy instagram is not loaded [2021-02-15 13:04:35] Cannot find module 'C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\auth\auth_instagram.js' Require stack: - C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\routes\login.js - C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\main.js - C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\cluster.js
> [2021-02-15 13:04:35] OAuth Strategy spotify is not loaded [2021-02-15 13:04:35] Cannot find module 'C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\auth\auth_spotify.js' Require stack: - C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\routes\login.js - C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\main.js - C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\cluster.js
> [2021-02-15 13:04:35] Game server #1 has an error: Error: connect ECONNREFUSED 127.0.0.2:8080
> [2021-02-15 13:04:35] Game server #1 closed: 1006
> [2021-02-15 13:04:35] Game server #1 has an error: Error: connect ECONNREFUSED 127.0.0.2:8090 [2021-02-15 13:04:35] Game server #1 closed: 1006
> [2021-02-15 13:04:35] DB is ready.
> [2021-02-15 13:04:35] Error when querying: SELECT * FROM kkutu_shop_desc WHERE TRUE [2021-02-15 13:04:35] Context: error: "kkutu_shop_desc" 이름의 릴레이션(relation)이 없습니다
> ```
> 
> 라는 오류를 뿜으며 서버가 꺼집니다.. 어떻게 해야 하는 건가요?

이번엔 서버 설정을 안한듯 합니다. postgresql 설정을 하고 켜보세요

**Comment by lshqqytiger** [comment]
DB 구축이 일단 제대로 안 된 것 같고 기존 SyntaxError도 계속 발생하네요.
원본 master.js 파일로 교체해보시고 DB 구축도 다시 해주세요.

**Comment by Carlo-Woo** [comment]
DB 다시 구축하고 master.js 교체한 뒤 로그입니다..
```
환영합니다.
[2021-02-16 11:07:50] &lt;&lt; KKuTu Web >>
[2021-02-16 11:07:50] &lt;&lt; KKuTu Server:8506 >>
[2021-02-16 11:07:50] &lt;&lt; KKuTu Server:8506 >>
[2021-02-16 11:07:50] &lt;&lt; KKuTu Server:8496 >>
[2021-02-16 11:07:50] &lt;&lt; KKuTu Server:8496 >>
[2021-02-16 11:07:50] Master DB is ready.
[2021-02-16 11:07:50] Master DB is ready.
[2021-02-16 11:07:50] DB is ready.
[2021-02-16 11:07:50] DB is ready.
[2021-02-16 11:07:50] DB is ready.
[2021-02-16 11:07:50] DB is ready.
[2021-02-16 11:07:50] Error when querying: SELECT * FROM kkutu_shop WHERE TRUE
[2021-02-16 11:07:50] Error when querying: SELECT * FROM kkutu_shop WHERE TRUE [2021-02-16 11:07:50] Error when querying: SELECT * FROM kkutu_shop WHERE TRUE [2021-02-16 11:07:50] Context: error: "kkutu_shop" 이름의 릴레이션(relation)이 없습니다 [2021-02-16 11:07:50] Context: error: "kkutu_shop" 이름의 릴레이션(relation)이 없습니다
[2021-02-16 11:07:50] Context: error: "kkutu_shop" 이름의 릴레이션(relation)이 없습니다
[2021-02-16 11:07:50] Error when querying: SELECT * FROM kkutu_shop WHERE TRUE
[2021-02-16 11:07:50] Context: error: "kkutu_shop" 이름의 릴레이션(relation)이 없습니다
[2021-02-16 11:07:50] Error when querying: UPDATE users SET "server"='' WHERE "server"='0'
[2021-02-16 11:07:50] Error when querying: UPDATE users SET "server"='' WHERE "server"='1' [2021-02-16 11:07:50] Context: error: "users" 이름의 릴레이션(relation)이 없습니다
[2021-02-16 11:07:50] Context: error: "users" 이름의 릴레이션(relation)이 없습니다
[2021-02-16 11:07:50] Error when querying: SELECT * FROM kkutu_shop WHERE TRUE [2021-02-16 11:07:50] Context: error: "kkutu_shop" 이름의 릴레이션(relation)이 없습니다
[2021-02-16 11:07:50] Error when querying: SELECT * FROM kkutu_shop WHERE TRUE [2021-02-16 11:07:50] Context: error: "kkutu_shop" 이름의 릴레이션(relation)이 없습니다
[2021-02-16 11:07:51] OAuth Strategy naver loaded successfully.
[2021-02-16 11:07:51] OAuth Strategy facebook is not loaded [2021-02-16 11:07:51] Cannot find module 'C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\auth\auth_facebook.js' Require stack: - C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\routes\login.js - C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\main.js - C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\cluster.js
[2021-02-16 11:07:51] OAuth Strategy google is not loaded [2021-02-16 11:07:51] Cannot find module 'C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\auth\auth_google.js' Require stack: - C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\routes\login.js - C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\main.js - C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\cluster.js
[2021-02-16 11:07:51] OAuth Strategy twitter is not loaded [2021-02-16 11:07:51] Cannot find module 'C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\auth\auth_twitter.js' Require stack: - C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\routes\login.js - C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\main.js - C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\cluster.js
[2021-02-16 11:07:51] OAuth Strategy kakao is not loaded [2021-02-16 11:07:51] Cannot find module 'C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\auth\auth_kakao.js' Require stack: - C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\routes\login.js - C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\main.js - C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\cluster.js
[2021-02-16 11:07:51] OAuth Strategy discord loaded successfully.
[2021-02-16 11:07:51] OAuth Strategy twitch is not loaded [2021-02-16 11:07:51] Cannot find module 'C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\auth\auth_twitch.js' Require stack: - C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\routes\login.js - C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\main.js - C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\cluster.js
[2021-02-16 11:07:51] OAuth Strategy github is not loaded [2021-02-16 11:07:51] Cannot find module 'C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\auth\auth_github.js' Require stack: - C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\routes\login.js - C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\main.js - C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\cluster.js
[2021-02-16 11:07:51] OAuth Strategy line is not loaded [2021-02-16 11:07:51] Cannot find module 'C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\auth\auth_line.js' Require stack: - C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\routes\login.js - C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\main.js - C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\cluster.js
[2021-02-16 11:07:51] OAuth Strategy instagram is not loaded [2021-02-16 11:07:51] Cannot find module 'C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\auth\auth_instagram.js' Require stack: - C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\routes\login.js - C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\main.js - C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\cluster.js
[2021-02-16 11:07:51] OAuth Strategy spotify is not loaded [2021-02-16 11:07:51] Cannot find module 'C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\auth\auth_spotify.js' Require stack: - C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\routes\login.js - C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\main.js - C:\Users\Administrator\Desktop\KKuTu-master\Server\lib\Web\cluster.js
[2021-02-16 11:07:51] New web server #1
[2021-02-16 11:07:51] Game server #1 connected
[2021-02-16 11:07:51] Game server #1 connected
[2021-02-16 11:07:51] New web server #1
[2021-02-16 11:07:51] DB is ready.
[2021-02-16 11:07:51] Error when querying: SELECT * FROM kkutu_shop_desc WHERE TRUE [2021-02-16 11:07:51] Context: error: "kkutu_shop_desc" 이름의 릴레이션(relation)이 없습니다
```
이제는 서버는 켜져있는데
기존 오류가 계속 발생합니다...

**Comment by norhu1130** [comment]
완전히 기존코드로 해보세요

**Comment by qkrehddls** [comment]
https://github.com/JJoriping/KKuTu/archive/master.zip

**Comment by lshqqytiger** [comment]
아무리봐도 DB가 정상적으로 구축된 것이 아닙니다. 다시 구축해주세요.

**Comment by Lotinex** [comment]
DB 구축 과정에서 빼먹은 과정이 있거나 제대로 완료하지 못한 과정이 있는지 확인해보세요.

**Comment by Carlo-Woo** [comment]
해결됐으므로 이슈 닫습니다.
