### ISSUE TITLE
끄투 웹서버 실행시 오류

### ISSUE THREAD

**Issue by AA1004** [JJoriping/KKuTu#822]
ubuntu@ip-172-31-34-238:~/KKuTu/Server$ sudo node lib/Web/cluster.js 1

[2021-03-07 05:30:34] << KKuTu Web >>

[2021-03-07 05:30:34] OAuth Strategy kakao loaded successfully.

[2021-03-07 05:30:34] OAuth Strategy discord loaded successfully.

[2021-03-07 05:30:34] New web server #1

[2021-03-07 05:30:34] Game server #1 closed: 1000

[2021-03-07 05:30:34] Exit web server #1

[2021-03-07 05:30:34] Game server #1 connected

[2021-03-07 05:30:34] Error from Redis: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379

[2021-03-07 05:30:34] Run with no-redis mode.

[2021-03-07 05:30:34] DB is ready.

events.js:174

      throw er; // Unhandled 'error' event

      ^

 

Error: bind EADDRINUSE null:80

    at listenOnMasterHandle (net.js:1347:16)

    at rr (internal/cluster/child.js:126:12)

    at Worker.send (internal/cluster/child.js:93:7)

    at process.onInternalMessage (internal/cluster/utils.js:45:8)

    at process.emit (events.js:203:15)

    at emit (internal/child_process.js:832:12)

    at process._tickCallback (internal/process/next_tick.js:63:19)

Emitted 'error' event at:

    at listenOnMasterHandle (net.js:1348:21)

    at rr (internal/cluster/child.js:126:12)

    [... lines matching original stack trace ...]

    at process._tickCallback (internal/process/next_tick.js:63:19)

Worker 15312 died

이렇게 프리서버가 죽어버립니다 어떻게 해야하나요?

**Comment by qkrehddls** [comment]
80포트를 다른 프로세스가 점유하고 있은거 같은데요?

**Comment by qkrehddls** [comment]
그리고 Redis 설치하셔야 합니다

**Comment by AA1004** [comment]
해볼게요

**Comment by lshqqytiger** [comment]
`EADDRINUSE`만 검색해도 15개의 이슈가 나옵니다..
#107 과 비슷한 문제입니다.

**Comment by AA1004** [comment]
이렇게 하든 어떻게 하든 안 고쳐지네요 포트를 빼먹어서 포트 추가해도 안돼요 그리고 Redis는 물어본거 아니고요. 80포트 점유하고있는거 없다는데요... 어떡하죠

**Comment by lshqqytiger** [comment]
```
netstat -ano | findstr 80
```
해도 아무것도 안뜬다는 건가요

**Comment by AA1004** [comment]
그냥 예전 서버 복구했습니다
