### ISSUE TITLE
오류

### ISSUE THREAD

**Issue by wd5dw** [JJoriping/KKuTu#823]
환영합니다.
[2021-03-10 17:21:22] ERROR OCCURRED ON THE MASTER! :8496 [2021-3-10 5:21:22 ├F10: PM┤] ERROR: Error: Unknown authenticationOk message typeMessage { name: 'authenticationOk', length: 23 } Error: Unknown authenticationOk message typeMessage { name: 'authenticationOk', length: 23 } at Connection.parseR (C:\Users\USER\Desktop\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\Server\lib\node_modules\pg\lib\connection.js:454:9) at Connection.parseMessage (C:\Users\USER\Desktop\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\Server\lib\node_modules\pg\lib\connection.js:370:17) at Socket.&lt;anonymous> (C:\Users\USER\Desktop\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\Server\lib\node_modules\pg\lib\connection.js:129:22) at Socket.emit (events.js:315:20) at addChunk (_stream_readable.js:295:12) at readableAddChunk (_stream_readable.js:271:9) at Socket.Readable.push (_stream_readable.js:212:10) at TCP.onStreamRead (internal/stream_base_commons.js:186:23)

이건 어떻게 해야 하나요?

**Comment by wd5dw** [comment]
그럼 어떻게 해결할 수 있나요?

**Comment by wd5dw** [comment]
> 비슷한 이슈가 몇 있었는데 확실한 해결책을 찾지 못했던 것으로 기억합니다.
> 아마 모듈 버전이나 PostgreSQL 또는 Node.js의 버전이 서로 맞지 않기 때문에 발생하는게 아닐까 생각합니다.

어떻게 해결 할 수 있나요?

**Comment by lshqqytiger** [comment]
node_modules 폴더와 package.json, package-lock.json 파일을 지우시고 원본 package.json과 package-lock.json 파일을 다운로드해서 넣은 다음 server-setup.bat을 다시 돌려보세요.

**Comment by wd5dw** [comment]
> node_modules 폴더와 package.json, package-lock.json 파일을 지우시고 원본 package.json과 package-lock.json 파일을 다운로드해서 넣은 다음 server-setup


> node_modules 폴더와 package.json, package-lock.json 파일을 지우시고 원본 package.json과 package-lock.json 파일을 다운로드해서 넣은 다음 server-setup.bat을 다시 돌려보세요.

node_modules 폴더와 package.json, package-lock.json 파일이 여러개 있는데 어느 폴더에 있는 것입니까?

**Comment by wd5dw** [comment]
> node_modules 폴더와 package.json, package-lock.json 파일을 지우시고 원본 package.json과 package-lock.json 파일을 다운로드해서 넣은 다음 server-setup.bat을 다시 돌려보세요.

어느 폴더 안에 있는 node_modules 폴더와 package.json, package-lock.json 파일 말씀이십니까?

**Comment by lshqqytiger** [comment]
Server 폴더와 lib 폴더요

**Comment by IAMIHAH** [comment]
`Server\lib` 폴더에서 cmd 창을 키신 후, `npm install pg` 를 입력하시고 서버를 다시 키시면 해결되는 문제입니다.

**Comment by IAMIHAH** [comment]
단, 버전에 맞게 설치하셔야 합니다.
#804 의 테스트 환경에 맞게 해주시면 될 것 같습니다.
또는, DB버전을 9.5버전으로 낮추시면 된다는 다른 이슈가 존재합니다.
