### ISSUE TITLE
이거 안나와서 질문합니다..

### ISSUE THREAD

**Issue by Seburancev** [JJoriping/KKuTu#825]
SyntaxError: Unexpected token ')'
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\spang\Desktop\KKuTu-master\Server\lib\Game\cluster.js:56:2)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)

server 디렉토리에서 했고, node lib/Game/cluster.js 0 1 철자도 안틀렸는데 왜이러는지 모르겠네요..
제가 8080 무슨 버그때문에 cmd로 했는데 이번엔 이러네요..

**Comment by lshqqytiger** [comment]
문법 오류입니다..cluster.js 56번째 줄을 잘못 수정하신 것 같습니다.

**Comment by Seburancev** [comment]
앗...그렇군요.. 감사합니다! 이슈 닫습니다 해결됬네용
