### ISSUE TITLE
게임서버가 안켜지는 오류

### ISSUE THREAD

**Issue by Aurorarain** [JJoriping/KKuTu#827]
C:\Users\user\Desktop\KKuTu\Server\lib\Game\kkutu.js:1453 function filterRobot(item){ ^^^^^^^^ SyntaxError: Unexpected token function at new Script (vm.js:74:7) at createScript (vm.js:246:10) at Object.runInThisContext (vm.js:298:10) at Module._compile (internal/modules/cjs/loader.js:646:28) at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10) at Module.load (internal/modules/cjs/loader.js:589:32) at tryModuleLoad (internal/modules/cjs/loader.js:528:12) at Function.Module._load (internal/modules/cjs/loader.js:520:3) at Module.require (internal/modules/cjs/loader.js:626:17) at require (internal/modules/cjs/helpers.js:20:18)
G: CLOSED WITH CODE 1
C:\Users\user\Desktop\KKuTu\Server\lib\Game\kkutu.js:1453 function filterRobot(item){ ^^^^^^^^ SyntaxError: Unexpected token function at new Script (vm.js:74:7) at createScript (vm.js:246:10) at Object.runInThisContext (vm.js:298:10) at Module._compile (internal/modules/cjs/loader.js:646:28) at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10) at Module.load (internal/modules/cjs/loader.js:589:32) at tryModuleLoad (internal/modules/cjs/loader.js:528:12) at Function.Module._load (internal/modules/cjs/loader.js:520:3) at Module.require (internal/modules/cjs/loader.js:626:17) at require (internal/modules/cjs/helpers.js:20:18)
G: CLOSED WITH CODE 1
C:\Users\user\Desktop\KKuTu\Server\lib\Game\kkutu.js:1453 function filterRobot(item){ ^^^^^^^^ SyntaxError: Unexpected token function at new Script (vm.js:74:7) at createScript (vm.js:246:10) at Object.runInThisContext (vm.js:298:10) at Module._compile (internal/modules/cjs/loader.js:646:28) at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10) at Module.load (internal/modules/cjs/loader.js:589:32) at tryModuleLoad (internal/modules/cjs/loader.js:528:12) at Function.Module._load (internal/modules/cjs/loader.js:520:3) at Module.require (internal/modules/cjs/loader.js:626:17) at require (internal/modules/cjs/helpers.js:20:18)
G: CLOSED WITH CODE 1
[2021-03-12 14:33:38] &lt;&lt; KKuTu Web >>
[2021-03-12 14:33:38] OAuth Strategy naver is not loaded [2021-03-12 14:33:38] OAuth2Strategy requires a clientID option
[2021-03-12 14:33:38] OAuth Strategy facebook is not loaded [2021-03-12 14:33:38] OAuth2Strategy requires a clientID option
[2021-03-12 14:33:38] OAuth Strategy google loaded successfully.
[2021-03-12 14:33:38] OAuth Strategy twitter is not loaded [2021-03-12 14:33:38] OAuthStrategy requires a consumerKey option
[2021-03-12 14:33:38] OAuth Strategy kakao is not loaded [2021-03-12 14:33:38] OAuth2Strategy requires a clientID option
[2021-03-12 14:33:38] OAuth Strategy discord loaded successfully.
[2021-03-12 14:33:38] OAuth Strategy twitch is not loaded [2021-03-12 14:33:38] OAuth2Strategy requires a clientID option
[2021-03-12 14:33:38] OAuth Strategy github is not loaded [2021-03-12 14:33:38] OAuth2Strategy requires a clientID option
[2021-03-12 14:33:38] OAuth Strategy line is not loaded [2021-03-12 14:33:38] OAuth2Strategy requires a clientID option
[2021-03-12 14:33:38] OAuth Strategy instagram is not loaded [2021-03-12 14:33:38] OAuth2Strategy requires a clientID option
[2021-03-12 14:33:38] OAuth Strategy spotify is not loaded [2021-03-12 14:33:38] OAuth2Strategy requires a clientID option
[2021-03-12 14:33:38] DB is ready.
[2021-03-12 14:33:40] Game server #1 has an error: Error: connect ECONNREFUSED 127.0.0.2:8080 [2021-03-12 14:33:40] Game server #1 closed: 1006
[2021-03-12 14:33:47] 121.151.110.149@tyENQmARhk portal, {}

**Comment by lshqqytiger** [comment]
kkutu.js를 원본으로 교체해보세요.
