### ISSUE TITLE
안녕하세요 오류가발생하여 질문드립니다.

### ISSUE THREAD

**Issue by ehowlqk** [JJoriping/KKuTu#837]
Error: Unknown authenticationOk message typeMessage { name: 'authenticationOk', length: 23 }
    at Connection.parseR (F:\KKuTu-master\Server\lib\node_modules\pg\lib\connection.js:454:9)
    at Connection.parseMessage (F:\KKuTu-master\Server\lib\node_modules\pg\lib\connection.js:370:17)
    at Socket.<anonymous> (F:\KKuTu-master\Server\lib\node_modules\pg\lib\connection.js:129:22)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23):8506 [2021-4-1 12:44:31 ├F10: PM┤] ERROR: Error: Unknown authenticationOk message typeMessage { name: 'authenticationOk', length: 23 }
    라고오류가표시되어 더이상 진행할수없습니다.
[KKUTU_ERROR.log](https://github.com/JJoriping/KKuTu/files/6241100/KKUTU_ERROR.log)

**Comment by lshqqytiger** [comment]
#864

**Comment by CHEEY-BORIN** [comment]
아직도 버그가 진행되고 있나요? 버그가 고쳐졌다면 이슈 닫아주세요.
