### ISSUE TITLE
오류

### ISSUE THREAD

**Issue by dev-vibel** [JJoriping/KKuTu#854]
개발 환경: Windows_Server-2012-R2_RTM-English-64Bit-Base-2021.04.14
노드 버전: 12.22.1 x64
DB버전(postgrSQL): postgresql-13.2-2-windows-x64

수정하지 않은 기본 소스코드에서 구동 환경만 구축후 작동을 시키니

KKuTu Server Manager v2.5.1 - My KKuTu Server
환영합니다.
[2021-04-25 08:44:08] &lt;&lt; KKuTu Server:8496 >>
[2021-04-25 08:44:10] Error from Redis: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
[2021-04-25 08:44:10] Run with no-redis mode.
[2021-04-25 08:44:10] Error from Redis: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379 [2021-04-25 08:44:10] Run with no-redis mode.
[2021-04-25 08:44:10] &lt;&lt; KKuTu Web >>
[2021-04-25 08:44:10] OAuth Strategy daldalso is not loaded
[2021-04-25 08:44:10] OAuth2Strategy requires a clientID option
[2021-04-25 08:44:10] OAuth Strategy naver is not loaded
[2021-04-25 08:44:10] OAuth2Strategy requires a clientID option
[2021-04-25 08:44:10] OAuth Strategy facebook is not loaded
[2021-04-25 08:44:10] OAuth2Strategy requires a clientID option
[2021-04-25 08:44:10] ERROR OCCURRED ON THE MASTER! :8080 [4/25/2021, 8:44:10 AM] ERROR: Error: Unknown authenticationOk message typeMessage { name: 'authenticationOk', length: 23 } Error: Unknown authenticationOk message typeMessage { name: 'authenticationOk', length: 23 } at Connection.parseR (C:\Users\Administrator\Desktop\KKuTu-master\KKuTu-master\Server\lib\node_modules\pg\lib\connection.js:454:9) at Connection.parseMessage (C:\Users\Administrator\Desktop\KKuTu-master\KKuTu-master\Server\lib\node_modules\pg\lib\connection.js:370:17) at Socket.&lt;anonymous> (C:\Users\Administrator\Desktop\KKuTu-master\KKuTu-master\Server\lib\node_modules\pg\lib\connection.js:129:22) at Socket.emit (events.js:314:20) at addChunk (_stream_readable.js:297:12) at readableAddChunk (_stream_readable.js:272:9) at Socket.Readable.push (_stream_readable.js:213:10) at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
[2021-04-25 08:44:10] ERROR OCCURRED ON THE MASTER!
:8496 [4/25/2021, 8:44:10 AM] ERROR: Error: Unknown authenticationOk message typeMessage { name: 'authenticationOk', length: 23 } Error: Unknown authenticationOk message typeMessage { name: 'authenticationOk', length: 23 } at Connection.parseR (C:\Users\Administrator\Desktop\KKuTu-master\KKuTu-master\Server\lib\node_modules\pg\lib\connection.js:454:9) at Connection.parseMessage (C:\Users\Administrator\Desktop\KKuTu-master\KKuTu-master\Server\lib\node_modules\pg\lib\connection.js:370:17) at Socket.&lt;anonymous> (C:\Users\Administrator\Desktop\KKuTu-master\KKuTu-master\Server\lib\node_modules\pg\lib\connection.js:129:22) at Socket.emit (events.js:314:20) at addChunk (_stream_readable.js:297:12) at readableAddChunk (_stream_readable.js:272:9) at Socket.Readable.push (_stream_readable.js:213:10) at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
[2021-04-25 08:44:10] ERROR OCCURRED! This worker will die in 10 seconds.
:8496 [4/25/2021, 8:44:10 AM] ERROR: Error: Unknown authenticationOk message typeMessage { name: 'authenticationOk', length: 23 } Error: Unknown authenticationOk message typeMessage { name: 'authenticationOk', length: 23 } at Connection.parseR (C:\Users\Administrator\Desktop\KKuTu-master\KKuTu-master\Server\lib\node_modules\pg\lib\connection.js:454:9) at Connection.parseMessage (C:\Users\Administrator\Desktop\KKuTu-master\KKuTu-master\Server\lib\node_modules\pg\lib\connection.js:370:17) at Socket.&lt;anonymous> (C:\Users\Administrator\Desktop\KKuTu-master\KKuTu-master\Server\lib\node_modules\pg\lib\connection.js:129:22) at Socket.emit (events.js:314:20) at addChunk (_stream_readable.js:297:12) at readableAddChunk (_stream_readable.js:272:9) at Socket.Readable.push (_stream_readable.js:213:10) at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
[2021-04-25 08:44:10] OAuth Strategy google is not loaded
[2021-04-25 08:44:10] OAuth2Strategy requires a clientID option
[2021-04-25 08:44:10] OAuth Strategy twitter is not loaded
[2021-04-25 08:44:10] OAuthStrategy requires a consumerKey option
[2021-04-25 08:44:10] OAuth Strategy kakao is not loaded
[2021-04-25 08:44:10] OAuth2Strategy requires a clientID option
[2021-04-25 08:44:10] OAuth Strategy discord is not loaded
[2021-04-25 08:44:10] OAuth2Strategy requires a clientID option
[2021-04-25 08:44:10] OAuth Strategy twitch is not loaded
[2021-04-25 08:44:10] OAuth2Strategy requires a clientID option
[2021-04-25 08:44:10] OAuth Strategy github is not loaded
[2021-04-25 08:44:10] OAuth2Strategy requires a clientID option
[2021-04-25 08:44:10] OAuth Strategy line is not loaded
[2021-04-25 08:44:10] OAuth2Strategy requires a clientID option
[2021-04-25 08:44:10] OAuth Strategy instagram is not loaded
[2021-04-25 08:44:10] OAuth2Strategy requires a clientID option
[2021-04-25 08:44:10] OAuth Strategy spotify is not loaded
[2021-04-25 08:44:10] OAuth2Strategy requires a clientID option
[2021-04-25 08:44:11] Game server #1 has an error: Error: connect ECONNREFUSED 127.0.0.2:8080
[2021-04-25 08:44:11] Game server #1 closed: 1006
[2021-04-25 08:44:12] Error from Redis: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
[2021-04-25 08:44:12] Run with no-redis mode.
C:\Users\Administrator\Desktop\KKuTu-master\KKuTu-master\Server\lib\node_modules\pg\lib\connection.js:454 throw new Error("Unknown authenticationOk message type" + util.inspect(msg)); ^ Error: Unknown authenticationOk message typeMessage { name: 'authenticationOk', length: 23 } at Connection.parseR (C:\Users\Administrator\Desktop\KKuTu-master\KKuTu-master\Server\lib\node_modules\pg\lib\connection.js:454:9) at Connection.parseMessage (C:\Users\Administrator\Desktop\KKuTu-master\KKuTu-master\Server\lib\node_modules\pg\lib\connection.js:370:17) at Socket.&lt;anonymous> (C:\Users\Administrator\Desktop\KKuTu-master\KKuTu-master\Server\lib\node_modules\pg\lib\connection.js:129:22) at Socket.emit (events.js:314:20) at addChunk (_stream_readable.js:297:12) at readableAddChunk (_stream_readable.js:272:9) at Socket.Readable.push (_stream_readable.js:213:10) at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
Worker 3684 died
W: CLOSED WITH CODE 0
G: CLOSED WITH CODE null

이런 버그를 출력후 워커가 죽습니다 이오류에 대해서 도움을 주실분이 계시나요? 본인 컴퓨터에선 아무런 문제없이 잘 구동이 되었으나 AWS호스팅 컴퓨터에선 이런 오류가 발생합니다.

**Comment by qkrehddls** [comment]
Postgresql의 비밀번호 암호화가 MD5가 아닌 SCRAM-SHA-256 인거 같은데요 설정에서  password_encryption = md5 로 변경하시고 md5 비밀번호를 사용하는 유저를 신규 생성하면 될거같습니다

**Comment by lshqqytiger** [comment]
https://github.com/brianc/node-postgres/issues/1508
이미 pg 모듈 레포지토리에 관련 이슈가 있으니 참고하시면 될것같네요

**Comment by dev-vibel** [comment]
해결했습니다!
postgresql의 버젼을 낮추기 해결되었습니다.도움을 주신 두분 정말 감사합니다.
