### ISSUE TITLE
무슨 오류죠

### ISSUE THREAD

**Issue by MegaKkutu** [JJoriping/KKuTu#885]
``App threw an error during load
SyntaxError: C:\Users\asdf\Desktop\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\settings.json: Unexpected token      in JSON at position 22
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (module.js:588:27)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\asdf\Desktop\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\Server\main.js:20:18)
    at Object.<anonymous> (C:\Users\asdf\Desktop\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\Server\main.js:61:3)
    at Module._compile (module.js:569:30)``
    제가 settings.json에 있는 내용을
    ``	"web-num-cpu": 2,
	"game-num-cpu": 2,
	"game-num-inst": 2``
	으로 바꾼뒤에
	global.json에 있는 port를 8080, 8090로 바꿔서 하였더니 이런 오류가 뜹니다.
	그래서 원래대로 1,1,1 8080만 했는데에도 이런 오류가 뜹니다.
	제가 global.json에 있는 PASS를 넣지 않았습니다.
	그런데 끄투 서버는 잘 실행 되었습니다.
	그리고, 오늘 이렇게 바꿔서 하니까 갑자기 run.bat를 실행하였는데 이런 오류가 떴습니다

**Comment by kmsimproject** [comment]
#689

**Comment by MegaKkutu** [comment]
.....

**Comment by kmsimproject** [comment]
@MegaKkutu 여기는 구현 관련해서 묻는곳이 아닙니다.

**Comment by kmsimproject** [comment]
> .....

비슷한 내용의 이슈를 읽어보고 질문하시기 바랍니다.

**Comment by kmsimproject** [comment]
확인하셨다면 해당 이슈를 닫아주시기 바랍니다.

**Comment by MegaKkutu** [comment]
비슷한 내용의 이슈가 어떤것이 있나요

**Comment by kmsimproject** [comment]
> 비슷한 내용의 이슈가 어떤것이 있나요

그건 직접 본인이 찾아보셔야 할듯 한데요.

**Comment by kdwkr** [comment]
json 문법이 맞지 않아 생기는 오류로 보입니다~
단순한 문법 이슈이므로 해당 레포지토리와는 관련이 없어보입니다

**Comment by MegaKkutu** [comment]
네 해결됬습니다
