### ISSUE TITLE
달달소 로그인을 구현했더니만 이런 오류가 뜨네요

### ISSUE THREAD

**Issue by graykkutu** [JJoriping/KKuTu#926]
TypeError: Cannot read property 'image' of undefined
    at Strategy._verify (C:\Users\ㅁㄴㅇㄹ\Desktop\KKuTu-master\Server\lib\Web\auth\auth_daldalso.js:25:24)
    at C:\Users\ㅁㄴㅇㄹ\Desktop\KKuTu-master\Server\lib\node_modules\passport-oauth2\lib\strategy.js:186:24
    at C:\Users\ㅁㄴㅇㄹ\Desktop\KKuTu-master\Server\lib\node_modules\passport-daldalso\lib\strategy.js:54:3
    at passBackControl (C:\Users\ㅁㄴㅇㄹ\Desktop\KKuTu-master\Server\lib\node_modules\oauth\lib\oauth2.js:134:9)
    at IncomingMessage.<anonymous> (C:\Users\ㅁㄴㅇㄹ\Desktop\KKuTu-master\Server\lib\node_modules\oauth\lib\oauth2.js:157:7)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Comment by graykkutu** [comment]
서버에 이미지를 넣어도 그런데

**Comment by lshqqytiger** [comment]
최신 레포지토리의 auth_daldalso.js 파일이 아닌 것 같습니다.
최신 레포지토리의 auth_daldalso.js 파일로 교체해주세요.

**Comment by graykkutu** [comment]
저 6월달에 다운 한건데

**Comment by lshqqytiger** [comment]
auth_daldalso.js 파일 내용 좀 볼 수 있을까요?

**Comment by CHEEY-BORIN** [comment]
그거 저도 겪은건데 그 달달소 서버 설정할때 권한 여행자 어쩌구 저쩌구였나 그거 설정해야 합니다

**Comment by graykkutu** [comment]
어떻게 하다 보니까 해결 됐네요
