### ISSUE TITLE
달달소 로그인

### ISSUE THREAD

**Issue by adad1323** [JJoriping/KKuTu#931]
달달소로 소셜 로그인을 하려니까
TypeError: Cannot read property 'image' of undefined
    at Strategy._verify (C:\Users\LGPC\Desktop\KKuTu-master\Server\lib\Web\auth\auth_daldalso.js:25:24)
    at C:\Users\LGPC\Desktop\KKuTu-master\Server\lib\node_modules\passport-oauth2\lib\strategy.js:186:24
    at C:\Users\LGPC\Desktop\KKuTu-master\Server\lib\node_modules\passport-daldalso\lib\strategy.js:54:3
    at passBackControl (C:\Users\LGPC\Desktop\KKuTu-master\Server\lib\node_modules\oauth\lib\oauth2.js:134:9)
    at IncomingMessage.<anonymous> (C:\Users\LGPC\Desktop\KKuTu-master\Server\lib\node_modules\oauth\lib\oauth2.js:157:7)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)라고 뜹니다

**Comment by lshqqytiger** [comment]
가장 최신 커밋의 레포지토리인가요?

**Comment by adad1323** [comment]
고쳐졌네요
