### ISSUE TITLE
처음 보는 오류가 발생하여 이슈 남깁니다.

### ISSUE THREAD

**Issue by godmoonl** [JJoriping/KKuTu#953]
```
TypeError: Cannot read property 'passport' of undefined
    at Server.use (/home/ubuntu/KKuTU2/Server/lib/Web/main.js:81:17)
    at Layer.handle [as handle_request] (/home/ubuntu/KKuTU2/Server/lib/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/ubuntu/KKuTU2/Server/lib/node_modules/express/lib/router/index.js:317:13)
    at /home/ubuntu/KKuTU2/Server/lib/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/ubuntu/KKuTU2/Server/lib/node_modules/express/lib/router/index.js:335:12)
    at next (/home/ubuntu/KKuTU2/Server/lib/node_modules/express/lib/router/index.js:275:10)
    at SessionStrategy.strategy.pass (/home/ubuntu/KKuTU2/Server/lib/node_modules/passport/lib/middleware/authenticate.js:338:9)
    at SessionStrategy.authenticate (/home/ubuntu/KKuTU2/Server/lib/node_modules/passport/lib/strategies/session.js:75:10)
    at attempt (/home/ubuntu/KKuTU2/Server/lib/node_modules/passport/lib/middleware/authenticate.js:361:16)
    at authenticate (/home/ubuntu/KKuTU2/Server/lib/node_modules/passport/lib/middleware/authenticate.js:362:7)
```

라고 오류가 뜨는데, 뭐가 문제인지  잘 모르겠네요..
아시는 분은 답변해주시면 감사하겠습니다.

**Comment by godmoonl** [comment]
감사합니다 해결했습니다.
