### ISSUE TITLE
서버가 열리지 않습니다.

### ISSUE THREAD

**Issue by ingari** [JJoriping/KKuTu#96]
node lib/Web/cluster.js 1 를 콘솔에다 입력하면
/root/JJuTu/Server/node_modules/dddos/index.js:36
  let rule = this.paths.get(path);
  ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/root/JJuTu/Server/lib/Web/main.js:25:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
Worker 21583 died

라는 오류가 뜹니다.
서버 운영체제는 Ubuntu 16.10입니다.

**Comment by ingari** [comment]
일단 몇몇 문제를 해결하긴 했습니다만..
root@ourplan:~/JJuTu/Server# node lib/Web/cluster.js 1
[2017-05-21 10:27:09] << KKuTu Web >>
[2017-05-21 10:27:09] Game server #1 has an error: Error: connect ECONNREFUSED 127.0.0.2:8080
[2017-05-21 10:27:09] Game server #1 closed: 1006
[2017-05-21 10:27:09] Error from Redis: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
[2017-05-21 10:27:09] Run with no-redis mode.
[2017-05-21 10:27:09] Error when connect to PostgreSQL server: error: password authentication failed for user "postgres"
라고 뜨네요. PostgreSQL 문제인 거 같은데 해결 방법이 있나요?

**Comment by JJoriping** [comment]
안녕하세요. 해당 오류는 계정 "postgres"로의 접속에 실패한 경우 발생합니다. README에도 기재해
 놓았듯이 PostgreSQL 서버 설치 중 입력한 데이터베이스 암호를 파일 `./Server/lib/sub/global.json`의 `PG_PASS` 값에 기입한 후 서버를 실행시켜야 합니다.

**Comment by ingari** [comment]
감사합니다. global.json에 DB 암호를 입력했으나 아직도 오류가 뜹니다.
root@ourplan:~/JJuTu/Server# node ./lib/Web/cluster.js 1
[2017-05-22 08:50:39] << KKuTu Web >>
[2017-05-22 08:50:39] Game server #1 has an error: Error: connect ECONNREFUSED 127.0.0.2:8080
[2017-05-22 08:50:39] Game server #1 closed: 1006
[2017-05-22 08:50:39] Error from Redis: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
[2017-05-22 08:50:39] Run with no-redis mode.
[2017-05-22 08:50:39] DB is ready.
제 생각에는 'Game server #1 has an error: Error: connect ECONNREFUSED 127.0.0.2:8080'에 문제가 있는 거 같은데 해결 방법이 있나요?

**Comment by ingari** [comment]
이 문제는 해결된 거 같으니 이슈 닫겠습니다.
