### ISSUE TITLE
오류가 없어야하는데 오류가........

### ISSUE THREAD

**Issue by kogunggom111** [JJoriping/KKuTu#968]
제가 서버 여는 과정 준비 제대로 하고 열었는데 이런 오류가 뜨네요........?
[2022-02-02 14:07:35] &lt;&lt; KKuTu Server:8496 >>
[2022-02-02 14:07:35] &lt;&lt; KKuTu Web >>
[2022-02-02 14:07:35] OAuth Strategy naver is not loaded [2022-02-02 14:07:35] OAuth2Strategy requires a clientID option
[2022-02-02 14:07:35] OAuth Strategy facebook is not loaded [2022-02-02 14:07:35] OAuth2Strategy requires a clientID option
[2022-02-02 14:07:35] OAuth Strategy google is not loaded
[2022-02-02 14:07:35] OAuth2Strategy requires a clientID option
[2022-02-02 14:07:35] OAuth Strategy twitter is not loaded [2022-02-02 14:07:35] OAuthStrategy requires a consumerKey option
[2022-02-02 14:07:35] OAuth Strategy kakao is not loaded [2022-02-02 14:07:35] OAuth2Strategy requires a clientID option
[2022-02-02 14:07:35] OAuth Strategy discord is not loaded [2022-02-02 14:07:35] OAuth2Strategy requires a clientID option
[2022-02-02 14:07:35] OAuth Strategy twitch is not loaded
[2022-02-02 14:07:35] OAuth2Strategy requires a clientID option
[2022-02-02 14:07:35] OAuth Strategy github is not loaded [2022-02-02 14:07:35] OAuth2Strategy requires a clientID option
[2022-02-02 14:07:35] OAuth Strategy line is not loaded [2022-02-02 14:07:35] OAuth2Strategy requires a clientID option
[2022-02-02 14:07:35] OAuth Strategy instagram is not loaded [2022-02-02 14:07:35] OAuth2Strategy requires a clientID option
[2022-02-02 14:07:35] OAuth Strategy spotify is not loaded
[2022-02-02 14:07:35] OAuth2Strategy requires a clientID option
[2022-02-02 14:07:35] Game server #1 has an error: Error: connect ECONNREFUSED 127.0.0.2:8080
[2022-02-02 14:07:35] Game server #1 closed: 1006
postsql 비번 문제는 없었고, redis 설치 잘 되고, 실행 잘되고, 모두 문제 없어 보이는데  서버 매니저에서 오류가 뜨네요......
어떻게 해야 잘 열리나요?

**Comment by lshqqytiger** [comment]
#958 
또는 Node.js 버전을 v12로 다운그레이드

**Comment by kogunggom111** [comment]
> #958 또는 Node.js 버전을 v12로 다운그레이드

이번엔 이렇게 뜨는데요....?
C:\Users\ksh-0\Desktop\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\Server\lib\Web\cluster.js:23 console.log(`Invalid CPU Number ${CPU}`); ^ SyntaxError: Unexpected token ILLEGAL at exports.runInThisContext (vm.js:73:16) at Module._compile (module.js:443:25) at Object.Module._extensions..js (module.js:478:10) at Module.load (module.js:355:32) at Function.Module._load (module.js:310:12) at Function.Module.runMain (module.js:501:10) at startup (node.js:129:16) at node.js:814:3
C:\Users\ksh-0\Desktop\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\Server\lib\Game\cluster.js:30 console.log(`Invalid Server ID ${process.argv[2]}`); ^ SyntaxError: Unexpected token ILLEGAL at exports.runInThisContext (vm.js:73:16) at Module._compile (module.js:443:25) at Object.Module._extensions..js (module.js:478:10) at Module.load (module.js:355:32) at Function.Module._load (module.js:310:12) at Function.Module.runMain (module.js:501:10) at startup (node.js:129:16) at node.js:814:3
W: CLOSED WITH CODE 1
G: CLOSED WITH CODE 1

**Comment by lshqqytiger** [comment]
사용 중이신 Node.js 버전이 어떻게 될까요

**Comment by kogunggom111** [comment]
> 사용 중이신 Node.js 버전이 어떻게 될까요

지금 재설치해서 0.12.0 이요

**Comment by kogunggom111** [comment]
> 사용 중이신 Node.js 버전이 어떻게 될까요

제설치해서 0.12.0 이요

**Comment by kogunggom111** [comment]
> 사용 중이신 Node.js 버전이 어떻게 될까요

.......... 답변 부탁드립니다.......

**Comment by lshqqytiger** [comment]
제가 v12라고 말씀드렸던건 12.xx.x입니다.
0.12.0은 템플릿 리터럴이 자바스크립트에 도입되기 전에 나온 버전이라 저런 오류가 발생합니다.

**Comment by Carlo-Woo** [comment]
> > 사용 중이신 Node.js 버전이 어떻게 될까요
> 
> .......... 답변 부탁드립니다.......

저분은 무조건 답변드려야 하는 의무가 없습니다. 답변 강요하지 마세요.
