### ISSUE TITLE
끄투 웹서버 오류

### ISSUE THREAD

**Issue by ingari** [JJoriping/KKuTu#99]
root@ourplan:~/JJuTu/Server# node lib/Web/cluster.js 1
[2017-05-24 10:42:53] << KKuTu Web >>
[2017-05-24 10:42:53] Error from Redis: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
[2017-05-24 10:42:53] Run with no-redis mode.
[2017-05-24 10:42:53] DB is ready.
/root/JJuTu/Server/lib/node_modules/ws/lib/WebSocket.js:219
    else throw new Error('not opened');
         ^

Error: not opened
    at WebSocket.send (/root/JJuTu/Server/lib/node_modules/ws/lib/WebSocket.js:219:16)
    at /root/JJuTu/Server/lib/Web/main.js:94:26
    at Array.forEach (native)
    at Timeout._onTimeout (/root/JJuTu/Server/lib/Web/main.js:93:15)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
Worker 4750 died

소셜 로그인 건들은 거 같더니 이렇게 뜹니다.

**Comment by ingari** [comment]
재부팅 했더니 갑자기 잘 됩니다.
