### ISSUE TITLE
카카오 로그인을 사용하니까 오류가 발생합니다

### ISSUE THREAD

**Issue by 1325ok** [JJoriping/KKuTu#995]
로그인 화면에서 카카오 로그인 눌러서 로그인하니

TypeError: Cannot read property 'profile_image' of undefined
    at Strategy._verify (/home/ubuntu/KKuTu/Server/lib/Web/auth/auth_kakao.js:25:45)
    at /home/ubuntu/KKuTu/Server/lib/node_modules/passport-kakao/node_modules/passport-oauth2/lib/strategy.js:188:22
    at /home/ubuntu/KKuTu/Server/lib/node_modules/passport-kakao/dist/Strategy.js:74:20
    at passBackControl (/home/ubuntu/KKuTu/Server/lib/node_modules/oauth/lib/oauth2.js:134:9)
    at IncomingMessage.<anonymous> (/home/ubuntu/KKuTu/Server/lib/node_modules/oauth/lib/oauth2.js:157:7)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

이렇게 오류가 발생합니다

InternalOAuthError: failed to fetch user profile 오류가 아니라서 잘 모르겠네요

**Comment by lshqqytiger** [comment]
Scope와 애플리케이션 권한 설정 문제입니다.
#934

**Comment by 1325ok** [comment]
> Scope와 애플리케이션 권한 설정 문제입니다. #934

그럼 동의항목을 뭐뭐 추가하면 되나요??
Scope는 어떻게하고요???
못찾겠어요 ㅠㅠ

**Comment by lshqqytiger** [comment]
![Screenshot_20220421-152521_Samsung Internet.jpg](https://user-images.githubusercontent.com/39524005/164387946-eb221534-57ff-4041-83b6-165a0fa64feb.jpg)
![Screenshot_20220421-152603_GitHub.jpg](https://user-images.githubusercontent.com/39524005/164387960-f1c7106a-fb80-40ad-ac0f-a8da846f046a.jpg)

**Comment by 1325ok** [comment]
덕분에 성공!!!
